MerginMaps/mobile

- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/qml/InputStyle.qml
- app/qml/main.qml
Custom opacity for highlights depending on feature's geometry.
Possible improvements could be create general function for getting feature's geometry if it will be used more in the future.
Feel free to check and comment on opacity values defined in InputStyle.
closes #100
> Custom opacity for highlights depending on geometry

- app/loader.cpp
- app/loader.h
- app/qml/FeaturePanel.qml
- app/qml/PreviewPanel.qml
Until now we were showing just value of the first field, but this changes it to show the proper name (or expression) defined in layer properties in QGIS.
> Show title in preview as specified in display field (expression)

- app/inpututils.cpp
- app/inpututils.h
- app/qml/main.qml
Current implementation updates extent only if feature would be hidden under preview panel. Possible improvement would be to make a transition while updating extent, so change wouldn't be sudden and can be used to centered any identified feature.
Notes: Currently identify color is set to red - it differs from record feature highlight.
closes #172
> Update map extent to a selected feature if its below preview panel.

- app/qml/FeaturePanel.qml
Default feature form toolbar is overlapping form in 'Add' state. Its unused anyway, therefore invisible.
However, it need proper fix in qgsquick lib.
> Overlapping components in the feature form in 'Add' state

- app/merginapi.cpp
- app/merginapi.h
Sending size info in data-sync changes json.
Changed order of headers.
> [Mergin] - changes after mergin parser update

- app/projectsmodel.cpp
- app/projectsmodel.h
If sync hasn't been successful, skip adding project
If such project exists according project folder name, update reference (a project can become invalid/valid after sync, has to be updated also reference in model)
closes #202
> Fix of doubling project while doing sync

- app/merginapi.cpp
Firstly, when a cache is read before fetching a list from server and merging info - if project folder doesnt exists, cache info is ignored and project status is purely based on server data. This is just to get proper status before mergin info from cache and server.
Secondly, when cache is created/overwriten after fetch. This is actual cleanup of cache.
closes #237
> Double check if a project folder exists

- app/merginapi.cpp
- app/merginapi.h
Get latest modification datetime out of all files rather than from only project's folder.
In case of shapefiles, project's folder has the same mod timestamp although shapefile has been changed.
possibly closing #264
> Modification time issue

- app/merginprojectmodel.cpp
Has no impact at all except for suppressing warnings.
> Fix some compiler warnings

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Added removal of a testCreateProjectTwice test project
Added timeout attribute and increased timeout for uploading a big file.
Tests are **sometimes** failing and generating `Received signal 11` fatal error. Happens mostly on dev.dev server, but also on local instance.
> Small improvements

- app/merginapi.cpp
- app/merginapi.h
The issue was that a transaction may be deleted at the time its project dir
is being passed by a const reference to slots. Fixed by making sure that
the project dir object is valid.
> Try to fix test crashes on mac

- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- removes a message box triggered from mergin api (closes #324)
- more precise server version check (using most recent server version instead of cached)
- added a test for this situation
> Improve "update before upload" handling in mergin client

- app/loader.cpp
- app/loader.h
- app/qml/LoadingIndicator.qml
- app/qml/MerginProjectPanel.qml
- app/qml/ProjectLoadingScreen.qml
- app/qml/main.qml
- app/qml/qml.qrc
Added loading indicator for rendering
Added loading screen for loading projects - therefore added signals in Loader class.
Since loading projects seems to be blocking GUI for redrawing a new component just before, a short event loop has been added. 
Note: Current implementation shows loading screen even if a loading is super quick which might be annoying in a user-perspective.
closes #321 
closes #354
> Loading indicators

- app/loader.cpp
Check if clearing project before sending loadingStarted signal. Suppose to fix stuck loading screen on deleting active project.
> Fix of a stuck loading screen while removing active project

- app/inpututils.cpp
- app/inpututils.h
Copy function was ended after the first problem with copying a file (QFile::copy returns false if a file at destination already exists). Therefore some files might be skipped afterwards. However, in the cases where functions is used, it should be in overwrite mode anyway.
The investigation and change has been invoked by https://github.com/lutraconsulting/qgis-mergin-plugin/issues/50
> Overwrite mode in copy function

- app/merginapi.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Fixed relative path to project's .mergin folder while uploading files to the server
closes #534
> Fix of uploading subdir gpkg file

- app/inpututils.cpp
- app/inpututils.h
- app/merginapi.cpp
- app/merginapi.h
Default request constructor with custom agent header and optional auth.
Sample: "Input/0.4.90; (osx/10.14)"
closes #490
> App data in each request

- app/qml/MerginProjectPanel.qml
Sets y-offset of context menu. Takes into consideration relative y value of the parent item to show it either below or above the related item if there is no space.
Tested on iOS and Android with long project list.
closes #540 
Examples of context menu related to `gallery_test`.
> Fix of stuck context menu at the bottom [iOS]

- app/loader.cpp
- docs/users/project_config.md
#577
If user specifies WMS Extent inside QGIS, `Zoom to project` in input automatically zooms to this extent, no longer to the entire project. If WMS Extent is not provided, behaviour stays the same - zoom to entire project.
Can be tested with this project: https://public.cloudmergin.com/projects/tomas/SlovakiaTrees/tree
> Zoom to WMS Extent

- app/localprojectsmanager.cpp
- app/localprojectsmanager.h
- app/positiondirection.h
- app/projectsmodel.cpp
An option to make error messages more readable, not only: _invalid project_
> Add different text for multiple projects

- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/featuresmodel.cpp
- app/featuresmodel.h
- app/img/mIconTableLayer.svg
- app/img/pics.qrc
- app/layersmodel.cpp
- app/layersmodel.h
- app/merginapi.cpp
- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/BrowseDataLayersPanel.qml
- app/qml/BrowseDataPanel.qml
- app/qml/BrowseDataToolbar.qml
- app/qml/BrowseDataView.qml
- app/qml/FeaturePanel.qml
- app/qml/Notification.qml
- app/qml/main.qml
- app/qml/qml.qrc
Added possibility to `add` and `edit` features without geometry.
When user selects layer in `browse data` (attribute table), there are three possible screens:
<table>
<tr>
<th>Features with geometry</th>
<th>Features without geometry</th>
<th>Features without geometry <br> (over limit *)</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/88152297-1a377900-cc04-11ea-8d0e-9e194a2aa597.png" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/88152301-1b68a600-cc04-11ea-8197-45e4ddd79adc.png"  width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/88152666-a47fdd00-cc04-11ea-8ebf-5886914037bc.png"  width="300"/></td>
</tr>
</table>
***limit** is set to 10.000 ~ Input queries first 10.000 features from a layer …
> Attr table - add/edit features in no geometry layers

- app/merginapi.cpp
Auth has been updated always when a user info was called. That caused wiping out the expiration token data which resulted into infinite authorization loop.
closes #814
> Fix of infinite projectList reloading due to always expired auth.

- app/purchasing.cpp
Input Purchasing backend is created at the very beginning. However it is cleaned and recreated once again after merginStatus has been changed - also called at the beginning while pinging mergin and getting its status. Each call of `createBackend` resets `mBackend` pointer and creates also new connections to already existing mMerginApi connections and new connections to reseted mBackend pointer. The call of the function caused multiplying of connections and therefore calling some (even server) functions multiple times.
This is simple fix of disconnecting existing connection on clean.  
closes #824
> Fix of multiplying connections

- app/qml/MerginProjectPanel.qml
- app/qml/SubscribePage.qml
Note: Would be good to have a single improved Busy Indicator for Input. Currently we use one for several screens where loadings may interfere to each other.
closes #805
> Added busyIndicator for the SubscribePage

- app/qml/FeaturePanel.qml
- app/qml/MerginProjectPanel.qml
There is a bug in Qt Dialog (seems to affect v1.1 - v1.3) with sending same signal twice
[https://bugreports.qt.io/browse/QTBUG-40613](https://bugreports.qt.io/browse/QTBUG-40613?jql=project%20%3D%20QTBUG%20AND%20component%20%3D%20%22Quick%3A%20Dialogs%22%20AND%20text%20~%20%22twice%22)
Tested and confirmed that `onAccept` and `onRejected` have been called twice. Handling only buttons signal fixes the issue.
TODO: `mFeatureLayerPair` in `QgsQuickAttributeModel` is after calling `QgsQuickAttributeModel::deleteFeature` not reseted - PR in QGIS:
closes #786 - a real issue was due to combination of ogr data provider and shapefile.
> Fix of twice called slots for Feature delete dialog

- app/qml/main.qml
Autopan only in record/edit mode. Otherwise updates screen center point according gps position only single time on gpc button clicked.
Autocenter allowed only for viewing
closes #847 
closes #499
> Fix of GPS autopanning

- app/qml/ExternalResourceBundle.qml
When an image has been captured or chosen from a gallery, wrong prefixPath has been used to extract relative path. TargetDir (actual final location of the image) and prefixDir (to which dir has to be value relative to) were mixed up.
This fixes also duplicating captured photos that occurrs when default path is different from project path.
Tested with following settings with project_folder `./lutra/mergin/projects_mergin/image_paths` :
value: `JPEG_20200908_184942_1945163542.jpg`<br/>
actual location: `./lutra/mergin/projects_mergin/image_paths/JPEG_20200908_184942_1945163542.jpg`. 
value: `JPEG_20200908_184937_271523668.jpg` <br/>
actual location: `./lutra/mergin/projects_mergin/image_paths/photos/JPEG_20200908_184937_271523668.jpg`. 
value: …
> Fix of wrong prefix path in the final value of selected/captured image.

- app/layersmodel.cpp
- app/layersmodel.h
- app/layersproxymodel.cpp
- app/layersproxymodel.h
- app/qml/ActiveLayerPanel.qml
- app/qml/BrowseDataLayersPanel.qml
- app/qml/BrowseDataPanel.qml
- app/qml/LayerList.qml
- app/qml/main.qml
Indexes from listview (and possibly other views) were used for communication with BE models. Solution replaces these with featureIds.
<table>
<td><img src="https://user-images.githubusercontent.com/22449698/92963790-50121480-f473-11ea-87a9-153421ae4ca7.png" width="400"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/92963812-56a08c00-f473-11ea-8143-2ea3e019e0fa.png"  width="400"/></td>
</tr>
</table>
Closes #845
> Fix issue with recoring layer selection

- app/qml/AuthPanel.qml
- app/qml/LoginForm.qml
- app/qml/RegistrationForm.qml
Added scroll view and simplified calculation of height/margins of the register form. The height of Qt.InputMethod and keyboard rectangle was used using implicit changed signal to change form's height/margins. However, after init of the virtual keyboard, its size wasnt being changed anyway. More promising way is to use visible property.
Fixed resizing of the login form with same pattern - the whole form was lifted when keyboard was shown, but it wasnt put back afterwards.
closes #863
> Register form adjusted for smaller screens or virtual keyboard

- app/geodiffutils.cpp
- app/geodiffutils.h
- app/merginapi.cpp
Currently set logging level to `info`. 
Just an idea: it might be useful to set log level according type of build (production, dev, debug,..)
closes #688
> Forwarding logs from geodiff

- app/loader.cpp
Invalid layer from postgis provider (and potentially other providers as well) returns null, not invalid layer. We did not check it. 
Closes #877
> Fix invalid layer loading - postgis

- app/qml/main.qml
Android back button did not work when app was opened with active project.
Solution ~> force focus on start to `MainPanel` component
Closes #876
> Fix android back button on startup with active project

- app/loader.cpp
- app/loader.h
- app/main.cpp
- app/qml/TextHyperlink.qml
Added logs for state change of the application:
- **minimizing** and **maximizing** 
- **quit**
- **start**
- **lock and unlock** 
> Note: lock and unlock logs are the same as minimizing and maximizing logs due to the same state in Qt:ApplicationState
States: https://doc.qt.io/qt-5/qt.html#ApplicationState-enum
Closes #894 
**EDIT:**
There was bug with wrongly typed variable name in `TextHyperlink.qml`, `paren` instead of `parent` so I added it here
> Add logs to the app

- app/digitizingcontroller.cpp
- app/qml/main.qml
We forgot to clean array of recorded points in `digitizing controller` when recording mode stops.
Closes #883
> Fix: Previous geometry used bug

- app/qml/SubscribePage.qml
Defined height and bottom margin.
Note that it is still not optimised for super small screens - it can be wrapped in ScrallView. Should work on the most screens though.
closes #899
> Position fix of notice text for Subscribe page

- app/inpututils.cpp
- app/inpututils.h
- app/localprojectsmanager.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
What has changed:
- Added temp file to `.mergin` folder to indicate (first time) download in progress
- File is removed once the project is successfully downloaded, but is kept within the project if application was closed during download ~ unsuccessful download
- If this file is found during startup check, given project is considered invalid
- Also we now clear the temp folder of given project when it should be downloaded for the first time in case there was previous unsuccessful attempt to download and some chunks were left here
Closes #884
> Fix unfinished download files 

- app/qml/MerginProjectPanel.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
While working on #916 I found 2 other issues that this PR addresses, original bug should be fixed by refactoring in #917. 
**One with log panel**: Hitting back on android in log panel was not consistent with back button in header. (android back leaded immediately to map view while in-app back led to settings panel)
**Second issue**: Wrong component received focus when application started without active project.
These changes should not conflict with #917
> Update: Android back button #916

- app/qml/main.qml
Auto-centering option was "ignored" due to not initialised state of stateManger.
The condition with empty state was not satisfied, so even though auto-center was on, nothing happen.
Related code (condition): https://github.com/lutraconsulting/input/blob/master/app/qml/main.qml#L377
closes #927
> Added initial state for stateManger

- app/ios.pri
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/ios/iosutils.mm
Rathe simple solution by disabling idle timer which prevents screen to sleep.
QUESTION (suggestion): Would be good to consider if we want to have this behaviour always or only during the sync.
closes #563
> Prevents screen from sleep

- app/qml/AboutPanel.qml
- app/qml/AccountPage.qml
- app/qml/InputStyle.qml
- app/qml/LogPanel.qml
- app/qml/LoginForm.qml
- app/qml/RegistrationForm.qml
- app/qml/SubscribePlanItem.qml
Screenshot of MerginProjectPage with customized text sizes on tablet 
closes #957
> Updated text sized

- app/ios/iospurchasing.h
Issue reported by @saberraz that `manage subscription` button always comes out with an error message instead of opening AppStore/Subscriptions.
Tested on local iOS build and desktop
Source: https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/handling_subscriptions_billing
> Fixed subscription URL

- app/loader.cpp
Input was ignoring custom datum transformations set in QGIS projects which may have been causing subtle shifts in on-the-fly reprojection when the default coordinate operation was different from the preferred one.
> Fix reprojection when datum transformations are set in project

- app/qml/Highlight.qml
- app/qml/main.qml
Enriches UI/UX experience while recording new linestrings and polygons by adding leading line / polygon as can be seen below:
<table>
<tr>
<th>Capturing Linestring</th>
<th>Capturing Polygon</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/97553792-2d619e00-19d6-11eb-9868-18debcc8e9ea.gif" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/97553892-4d915d00-19d6-11eb-996e-be558789595c.gif"  width="300"/></td>
</tr>
</table>
Closes #309
> Add guide lines and polygons when recording new features

- app/qml/AccountPage.qml
- app/qml/AuthPanel.qml
- app/qml/LoginForm.qml
- app/qml/MerginProjectPanel.qml
- app/qml/ProjectStatusPanel.qml
- app/qml/RegistrationForm.qml
There were several issues with current implementation of pages - components from pages were sometimes overlapping to each other. This fixes uses StackView to simplifying paging and key (press) handling.
Generally it might be better to refactor all pages similarly and use single stackView component for that.
TOFIX: Currently "Subscription plans" always open browser instead of showing Subscription page.
NOTE: such change needs to be properly tested. It has been tested on Android and iOS, but it could happen that some use cases were not covered.
closes #906
> REBASED: Wrapped all MerginProjectPanel related pages into stack view

- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/FeaturePanel.qml
- app/qml/ValueRelationWidget.qml
PR fixes 2 bugs with value relation page:
- search text were not being cleared on Android. We read `displaytext` property and looks like it is not being updated immediately
- back button now working
Fixes #952
> Value relation page - android problems

- app/merginapi.cpp
- app/merginapi.h
- app/qml/LoginForm.qml
Simple link to forward to mergin web.
Questions/suggestions: Shall the reset password link be located next to the `Sign up` button with backslash delimiter?
closes #914
> Added link to reset password

- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/BrowseDataPanel.qml
- app/qml/BrowseDataToolbar.qml
- app/qml/BrowseDataView.qml
- app/qml/FeaturePanel.qml
- app/qml/LeftCheckBox.qml
- app/qml/SearchBar.qml
- app/qml/ValueRelationWidget.qml
Added possibility to select multiple values in value relation field and also filtering values in value relation based on filter expression.
Example:
Relates heavily on https://github.com/qgis/QGIS/pull/39959
Closes #740 and closes #741
> Cascade value relations and Multiple selections

- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
Reason: Sometimes config do not provide field type (passes empty string). In these scenarios we were showing textfield by default. However, in recent changes we have introduced check for undefined widget type (due to another bug), but empty string was resolved as false in condition too and field would not get generated.
> change condition for widget loading

- app/qml/SearchBar.qml
There is a new function to clear text of textfield. We now use that one instead of hard setting empty string to textfield.
Notice: there is something wrong either in Input or Qt (I could not get rid of) yelling this error when one clicks on **x** to clear text:
`W Input   : QMetaObject::invokeMethod: No such method QQuickContentItem::inputMethodQuery(Qt::InputMethodQuery,QVariant)` 
This closes #1038 however above message stays and should be looked at in future.
> Clear search text

- app/android/AndroidManifest.xml
Removed automatic expand of permissions from Qt to get rid of RECORD_AUDIO permission which we do not use.
Previously we have used these permissions:
In Android app settings it looked like this:
After this change, **Microphone** permission is not there, however, user can use speech-to-text feature provided by keyboard (it is up for a virtual keyboard to opt for RECORD_AUDIO permission).
Let's wait for CI builds to see if everything works properly (I lost splash screen, not sure if it is only problem with my local build or not)
Resolves #1069
> Remove automatic permissions from Qt and remove RECORD_AUDIO permission

- app/androidutils.cpp
Fixed by opting for a permission when starting a camera, if user do not provide permission camera wont start
+ also removed opting for permission in the application start
Resolves #1078
> Camera permission crash

- app/localprojectsmanager.h
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
- app/qml/InputStyle.qml
- app/qml/MerginProjectPanel.qml
- app/qml/ProjectDelegateItem.qml
- app/qml/components/DelegateButton.qml
- app/qml/qml.qrc
Listing all projects has been replaced with listing with paging functionality.
Note: `NonProjectItem` project status has been introduced to easily distinguish real project items and fetch button item in a model (and view). This approach of introducing an extra item in the list has been agreed before the implementation.
UPDATED:
- fixed sorting by name 
- fixed jumping at the beginning after fetching new project items
- partially fixed searching
Known issues:
- Inconsistent project list when a content of a page has been changed on server in a meanwhile of browsing - user already fetched a batch of projects, a project has been deleted on Mergin and therefore another project is lost since order of project has been changed. Reloading the whole page resolves the issue. …
> Paging project list

- app/androidutils.cpp
- app/androidutils.h
- app/inpututils.cpp
- app/inpututils.h
- app/qml/MerginProjectPanel.qml
When user did not grant storage permission, app behaved not in UX friendly way (showing projects with error, leading user to learn how to download first project)
We now detect missing storage permission and opt for it when user wants to download a project. 
https://user-images.githubusercontent.com/22449698/104316379-ad2edd00-54dc-11eb-87a5-f91fd511218c.mp4
Due to an implementation, it is hard to recover application and load projects after gaining storage permission so right now we ask user to restart application in order to apply changes.
This change affects only Android users. Resolves #1084
> Storage permission

- app/qml/BrowseDataView.qml
- app/qml/InputStyle.qml
- app/qml/LayerList.qml
- app/qml/MerginProjectPanel.qml
Speed of scrolling is now fast also on Android devices.
Resolves #1079
> Faster Android scrolling in views

- app/appsettings.cpp
- app/appsettings.h
- app/qml/FeaturePanel.qml
- app/qml/SettingsPanel.qml
- app/qml/components/InputSwitch.qml
- app/qml/qml.qrc
- qgsquick/from_qgis/attributes/qgsquickattributeformmodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributeformmodel.h
- qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.cpp
- qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.h
- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributemodel.h
- qgsquick/from_qgis/plugin/CMakeLists.txt
- qgsquick/from_qgis/plugin/components/qgsquickcheckboxcomponent.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
- qgsquick/from_qgis/plugin/qmldir
Added possibility to reuse last entered values while creating new features. This option allows user to faster record new features.
To use this feature:
- go to settings and check "Save last values"
- create new feature = you will see checkboxes next to each attribute
- click some of the checkboxes = these values will be saved for next feature
- creat feature and try to create another one = selected attributes will be prefilled
Note:
- this also works when switching between multiple layers.
- setting is saved to QSettings and thus even when app is restarted, this check stays the same. (Though saved values are not preserved)
- look of checkboxes will be changed
**EDIT:**
- new UI
https://user-images.githubusercontent.com/22449698/106280790-a9ba8600-623e-11eb-9b53-698bc3c89076.mp4
Resolves …
> Reuse last entered value

- app/appsettings.cpp
- app/appsettings.h
- app/main.cpp
Introducing `isAppInitialized` qsettings variable to see if the app has been already launched or it is the first time run.
Demo projects are copied only on the very first run. This should allow user to delete demo project or kept demo project data from previous runs. 
closes #1109
> Initialize demo project only on the first run

- app/fieldsmodel.cpp
- app/fieldsmodel.h
- app/inpututils.cpp
- app/inpututils.h
- app/localprojectsmanager.cpp
- app/localprojectsmanager.h
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/projectwizard.cpp
- app/projectwizard.h
- app/qml/FeatureToolbar.qml
- app/qml/InputStyle.qml
- app/qml/MerginProjectPanel.qml
- app/qml/ProjectWizardPage.qml
- app/qml/components/DelegateButton.qml
- app/qml/components/FieldRow.qml
- app/qml/components/Symbol.qml
- app/qml/qml.qrc
- app/sources.pri
Implementation of project wizard to locally create a new project according specification. Allows to create a project with point gpkg layer. Three fields are predefined with option to add or remove a field. To simply workflow, user defined a name and widget type (with default simple configuration). Accordingly field type is set.
Feel free to comment. I think there are some things to improve, but Id rather share some ideas before spending some more time on it.
Manual test updated.
NOTE: Please use `Squash and merge`  option.
Possible enhancement:
* support for more widget combined with more field types (e.g real + slider) - from discussion, now out of scope of this PR
* better handling of having two fields with same names
* floating "Create project" button with reserved space bellow the …
> Project wizard

- app/inputprojutils.cpp
- app/inputprojutils.h
- app/main.cpp
Bundle and data dir has different hash in absolute path
closes #1131
Android seems to have an issue with `fallbackOperationOccurredReported` - investigation in progress. 
To reproduce:
* clean install of app
* download test project with custom proj
* open project - a dialog about restart is opened
* restart app
* open the project
> Custom proj fix for iOS

- app/merginapi.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Prepare basefile for changeset for a newly added files (mainly for a new project).
By adding migration to Mergin functionality, a new use case has been introduced with it. The only way how to obtain a project that can be synced with Mergin, was to donwload it. After download, a basefile for .gpkg files are copied. However, by migrating a new project to mergin, the basefile preparation was omitted (not needed before though), therefore geodiff couldnt work properly.
closes #1127
> Fix missing basefile for a new projects

- app/qml/RecordToolbar.qml
closes #1161 
Might be worth to extract necessary code from TextWithIcon component and use it for all icon+text components.
before:
after:
> Centered text for record toolbar

- app/config.pri.default
- app/linux.pri
Linux would not compile due to a missing GDAL path.
> Add OGR to Linux deps

- app/layersproxymodel.cpp
- app/layersproxymodel.h
- app/main.cpp
- app/merginprojectmodel.h
- app/models/projectsmodel_future.cpp
- app/models/projectsmodel_future.h
- app/models/projectsproxymodel_future.cpp
- app/models/projectsproxymodel_future.h
- app/project_future.cpp
- app/project_future.h
- app/sources.pri
Added classes with suffix `_future` for the sake of time (so that old version is still working). 
I though we could start separating code to subfolders - at least models from start, what do you think?
There are basically three classes, it might look messy right now, but the idea is:
- `ProjectsModel_future` will contain QList of `Project_future` (either struct or object)
- `ProjectProxyModel_future` handles search
- `MerginApi` will have no idea about `projectModels` nor (probably) `localProjectManager`, it will just emit signals
- `Project_future` can be a GUI type (registered for QML) and offer all necessary information
> [Refactoring] Structure - new classes

- app/merginapi.cpp
- app/merginapi.h
Added:
- Mergin API `listProjectsByName` that accepts list of projects (their names) and returns project info (same as in `listProjects` API)
- RequestId that is returned from methods calling `listProjectsByName` and `listProjects` API. In future project model will compare this Id with its own to make sure projects list are not being overwritten (#1050)
Merging to Refactoring branch.
> [Refactoring] Change MerginAPI - add listByNames API and request id

- app/qml/FeaturePanel.qml
- app/qml/InputStyle.qml
- qgsquick/from_qgis/plugin/editor/qgsquickcheckbox.qml
- qgsquick/from_qgis/plugin/editor/qgsquickdatetime.qml
- qgsquick/from_qgis/plugin/editor/qgsquickeditorwidgetcombobox.qml
- qgsquick/from_qgis/plugin/editor/qgsquickexternalresource.qml
- qgsquick/from_qgis/plugin/editor/qgsquickrange.qml
- qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
- qgsquick/from_qgis/plugin/editor/qgsquickvaluemap.qml
- qgsquick/from_qgis/plugin/editor/qgsquickvaluerelation.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
Fixes:
- better horizontal and vertical spacing of the label above the fields
- better font for labels (not bold, not completely black, maybe a bit larger than it is now)
- better padding of content inside of widgets to align them horizontally with labels
- some hardcoded values replaced by configurable variables in the form styling
- Pixel and Point values for fonts and margin used from [Rado's design](https://www.dropbox.com/home/_Projects/input/graphic%20materials/2021-02/edit%20form?preview=_input_app_Edit_Feature_3-03.png). However, all numbers are devided by 2
closes #1146
> Unified feature form layout

- app/appsettings.cpp
- app/main.cpp
closes issue related to not be able to save gspTolerance
> Fix of writing/reading QSettings

- qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
- qgsquick/from_qgis/plugin/editor/qgsquickvaluerelation.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
- Centered last value checkboxes in new form layout
- Text widget and value relation widget starting position fixed
- Added space after last widget
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/109349661-9cf97400-7876-11eb-88fa-ddcdd1d75449.jpg" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/109349156-c9f95700-7875-11eb-8e41-19dbca57460a.jpg"  width="300"/></td>
</tr>
</table>
Based on https://lutraconsulting.slack.com/archives/CC95JK1T9/p1614350655028200
> Minor UI Fixes

- app/qml/FeaturePanel.qml
- app/qml/FeatureToolbar.qml
- app/qml/PanelHeader.qml
- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributemodel.h
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
* save button turned red if hard constrain are not met (similar to how was it before when save button was disabled in this case)
* added check if a feature has been changed - either if is newly created or edit buffer has uncommitted changes for the feature. Note that saving geometry is committed immediately after geometry edit, therefore was omitted for this function. This also effects attributes changed before geometry has been changed and committed.
* Cancel discard changes
* Save saves all changes
* Back button throws a dialog to choose action
Feel free to comment on how checking uncommitted changes should work or any uix related issues.
closes #384
closed #445
> Relocated save button from Feature form toolbar to header

- app/qml/main.qml
There were leftover references to old project when new one was loaded. This led to application crash on different places.
Resolves #1204
> Reset old references on project reload

- scripts/update_all_versions.bash
It looks like `sed` on linux does not like the space between `-i` and its value:
```
sed: -e expression #1, char 1: unknown command: `.'
```
This fixes it. @PeterPetrik can you check if the script still works for you on :apple: ?
> Fix sed error when running update_all_versions.bash

- qgsquick/from_qgis/plugin/editor/qgsquickeditorwidgetcombobox.qml
In special scenarios value map and value relation fields did not show text. The reason was that new icons were consuming all the place in widget.
Resolves #1231
> Not visible value map/ value relation

- app/qml/FeaturePanel.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
* border tab has the same color as labels (color picker shows me some weird color from the design image on dropbox - #7A7368)
* from a design, the tab toolbar's height seems to be the same as the one header has. However, now is set to 90% of the rowHeight. This ratio is rather random though, couldn't find any reference about its height.
Generally, fonts have to be adjusted to Rado's design.
closes #1151
> Feature form tab styling

- qgsquick/from_qgis/qgsquickfeatureslistmodel.cpp
Another dangling pointer found. `mCurrentLayer` and `mCurrentFeature` not being reset when project gets reloaded.
Added handler for `QgsProject::cleared` signal, is this good approach @wonder-sk?
> Reset features list model when project is reloaded

- qgsquick/from_qgis/plugin/editor/qgsquickrange.qml
Would be good to introduce a variable for custom indicator height (checkbox, slider)
Disabled form:
Enabled form:
closes #1023
> Range widget ui fixes

- app/qml/InputStyle.qml
- app/qml/LayerList.qml
- app/qml/MapThemePanel.qml
- app/qml/ProjectDelegateItem.qml
Just small note about colors which were changed according the ticket: `#9abfa0` used instead of `#689d71`. However, color that was used before was actually `#679d70`. Maybe a color picker or an image itself might cause that small difference, but maybe better to have also color palette from Rado.
Also fixed border style in Layer and Theme panel.
Color changed in:
* record layers panel
* map theme panel
* projects page
closes #1247
> Better selection color

- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
Group and Tab panel have not the same height though (not introduced in this PR).
closes #1248
> Borders of flickable tab component visible only if there is the tab

- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/AboutPanel.qml
- app/qml/LogPanel.qml
- app/qml/SettingsPanel.qml
- Added scrolling for settings for both landscape and portrait mode
- Fixed visual overlap of about page when in landscape
- Fixed some UI in log panel (see video)
- Now using stackview in settings like:
- It starts with Item that holds `StackView` 
- Initial item of Stackview is component settingsContent that holds all settings items
- When one clicks on about / log panel, corresponding page is pushed to stack (this also results to lazy loading of Logs list)
- When that page closes, stackview is cleared to only contain `initialItem`
- Visibility of settings is handled by setting `visible` state of the root `Item`
- Added link for [Mergin Terms of Service](https://public.cloudmergin.com/assets/mergin_terms_of_service.pdf) - Resolves #1239 
Resolves #1234 
Resolves #1125 
Previous visual …
> Landscape for settings + link to Mergin Terms

- app/merginapi.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
The reason was that `+` was converted into a space.
[https://doc.qt.io/qt-5/qurlquery.html#handling-of-spaces-and-plus](https://doc.qt.io/qt-5/qurlquery.html#handling-of-spaces-and-plus)
Simply, `item.filePath.replace("+", "%2b")` was needed. Fixed by using toPercentEncoding() on `file` query parameter.
A test added as well.
NOTES
* maybe better to check if the same issue may occur elsewhere. So far found with search query on explore page (fix included in this PR).
* better notification - server is returning just filename as error message in a case, when filepath is not existing (or filename has been decoded).
[Mergin #638](https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/638)
closes #1246
> Fix of downloading a file containing a special character

- app/android/build.gradle
- app/android/src/uk/co/lutraconsulting/CameraActivity.java
- app/android/src/uk/co/lutraconsulting/EXIFUtils.java
- app/android/src/uk/co/lutraconsulting/OrientationSensor.java
- app/androidutils.cpp
- app/androidutils.h
Writes azimuth direction as EXIF GPSImgDirection attribute.
Azimuth is read from sensors and stored with a timestamp. When the camera activity is finished, the proper azimuth value is fetched according the capture photo file timestamp. Note that we use temporary photo file created by a camera, not the copied that is used as value for a field. This suppose to ensure to get a timestamp of the event when user actually hits the capture button.
The azimuth degree takes into consideration device screen rotation and tilt. The value is written with flag `GpsImgDirection`.
LIMITATIONS:
- currently only rear camera is supported for a correct result
- may take sometime ~1s to init sensors at the beginning of capturing
This is not ideal solution, but couldn't get onCapture listener working in …
> Write image direction angle to EXIF when capturing pictures on Android

- qgsquick/from_qgis/plugin/components/qgsquickicontextitem.qml
- qgsquick/from_qgis/plugin/editor/qgsquickexternalresource.qml
Replaced using `paintedWidth` that causes icon with text to shrink/expand based on text width. We are now using better Layouts.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/110473494-e3549b80-80de-11eb-8687-69b76a51379b.jpg" width="250"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/111531163-75eedd80-8764-11eb-96df-56cc17cdbd32.jpg"  width="250"/> <img src="https://user-images.githubusercontent.com/22449698/111531400-c36b4a80-8764-11eb-83af-c9bdf980cb5d.jpg"  width="250"/></td>
</tr>
</table>
Resolves #1244
> Fix photo widget width

- app/qml/FeaturePanel.qml
- app/qml/InputStyle.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
Added vertical space before group header. It is now wrapped in container that has `topMargin` same as fieldName.
Closes #1230
> Add vertical space before group header

- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributemodel.h
- qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
This fixes updating attributes for fields with default values and when`Apply default value on update` checked.
A new function `QgsQuickAttributeModel::updateDefaultValuesAttributes` is introduced which is called after an attribute has changed.
It is similar to `QgsQuickAttributeModel::resetAttributes` which seems to not be (explicitly) called. I think the idea was to use it in similar manner, however as description says, it should reset all attributes which is not the case now. Since it not used, I suggest to delete it. If not, it would be good to refactor it with `QgsQuickAttributeModel::updateDefaultValuesAttributes` a bit since it also evaluates expression for fields. So far, I kept it untouched before we asses it in the review.
NOTES:
* If a field has such default value definition, it …
> Applies default values on update

- core/localprojectsmanager.cpp
iOS build missed `#inlude <QDebug>`, used CoreUtils instead to have it in logs.
> Fix debug include

- app/qml/CodeReaderHandler.qml
To clean all possible sources of issues for crashes for current release.
This was a leftover from spelling fixes in QGIS Quick 
closes #1312
> Back compatibility with QGIS causing qml error

- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
Crash was caused by a null pointer of edit buffer. Therefore added some checks to avoid the situation.
Will be good to create PR to QgsQuick afterwards - note that this fix and previous changes were not added there yet at all. 
closes #1301
> Fix of crash due to hasChanges function

- app/projectsmodel.cpp
- app/projectsmodel.h
- app/projectsproxymodel.cpp
- app/qml/components/ProjectList.qml
- core/merginapi.cpp
There are four fixes included (one fix pre commit):
- 0ff8ff1 click on project that is being first time downloaded brought _Download window_ again, now does not
- 78b8a98 project that is being downloaded **for the first time** is now visible also in home page in local projects list
- 5ad9d42 removed custom sorting in public projects list and use Mergin sorting instead (changed it to use namespace for time being, there will be an option in Mergin to sort by namespace and name in future)
- 97c3f6d clears list of projects in model when request is sent, not after response is received - this led to UI issues (listview still holding projects though request already sent to refresh it)
- 6939b15 hides no projects text when model is loading projects
> Refactoring, solving multiple issues

- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
Show compatibility issue notification only for not null values.
Null values have to be handled more properly for widgets though.
closes #1315
> Incompatible type notification

- app/qml/Highlight.qml
The crash was caused by:
`"qAbs(m_vertices.at(i).x) < (1 << 21)" in file painting/qtriangulator.cpp`
It seems that triangulation is sensitive to extreme values in path dataset (if a vertex is way away from average coordinates of other vertices).
Extreme values for our case were obtain by wrong parsing multipolygon coordinates into an array - it was handled as single polygon feature which resulted into invalid data. Instead, each polygon data should be rather split to be in valid format.
Fix changes how data are parsed - data are in one array, where each rings starts its part with two elements: index 0 - geometry type and index 1 - no. of vertices. Those values are used as indicators that interior ring data starts from there.
This fixes the crash but rather not data format itself. 
PR has …
> Multipolygon highlight crash

- app/inputhelp.cpp
- app/inpututils.cpp
- app/main.cpp
- app/purchasing.cpp
- app/qml/AccountPage.qml
- app/qml/ProjectPanel.qml
- app/qml/SubscribePlanItem.qml
- app/test/testingpurchasingbackend.cpp
- app/test/testpurchasing.cpp
- app/test/testpurchasing.h
- core/core.pri
- core/merginapi.cpp
- core/merginapi.h
- core/merginsubscriptioninfo.cpp
- core/merginsubscriptioninfo.h
- core/merginuserauth.cpp
- core/merginuserinfo.cpp
- core/merginuserinfo.h
Changes due to support for CE Mergin server. The idea is to use primary mergin core endpoints. Request related to subscription are sent extra. Therefore login and userInfo request were changed.
Note that there is a possibility to corrupt data by mixing projects from different servers ATM: https://github.com/lutraconsulting/input/issues/1347
**Squash and Merge** option can be ideally used.
Account page with server supporting subscription:
Account page with server NOT supporting subscription (looks quite empty):
related to #1289
> CE support

- qgsquick/from_qgis/qgsquickfeatureslistmodel.cpp
Attributes marked as `not searchable` are filtered out from QgsFeature request (scope) as well as from informative text for features shown on the BrowseDataPage.
Note that values for such attributes are still present in features fetched from the request (request.subsetOfAttributes() is kept unset and therefore a user see all attributes while browsing).
PR for QgsQuick will be made after this PR would be approved.
closes #1354
> Restrict "non searchable" attributes in a feature request query

- app/qml/ProjectPanel.qml
- app/qml/StorageLimitDialog.qml
- app/qml/main.qml
- app/qml/qml.qrc
- core/merginapi.cpp
- core/merginapi.h
Introduced a new dialog when a storage limit has been reached during the sync. Includes some information according the related ticket. Data are fetched between when MerginApi sends a signal of reached limit and when dialog is opened. Since the userInfo/subscription info request may take some time, information labels in the dialog could be empty/out-dated till the request is finished.
Things to consider:
* design/content of the dialog (e.g. labels, text sizes,...)
* what should be done when a user clicks on text - currently opens subscription page.
* request user/subscription info in advance - currently there is no need to have those info before user opens AccountPage, therefore requests are sent also when the page is about to be opened. …
> Added StorageLimitDialog

- app/qml/components/FieldRow.qml
I couldn't replicate the issue, but I could replicate similar problem with auto uppercase - when a user types into an Attribute field with fixed uppercase option (usually double click on shift to "lock" shift), it always switches back to lower case. It doesn't happen for a project name field.
This PR fixes the issue described above. However, the reported issue could be very related and fixed as well. Best to test.
Now the field value is bound to `text` without an extra handling for displayText.
closes #1334
> Fixed behaviour of TextField in ProjectWizard

- core/merginapi.cpp
- core/merginapi.h
Fix of really annoying bug that has been introduces after CE support PR.
**Story behind:**
When a user signs out, userInfo, subscriptionInfo and authData are cleared. After CE support PR a new signal has been introduced to update user info, when subscription has changed (storage has to be updated - this extra call was needed mostly for tests). 
**The cause:**
This extra call for userInfo triggers authorization, which opens an extra Login page in the stackview. This extra page is unexpected and stackview pops out Login page instead of Account page (where user clicks on Sign out button). Therefore AccountPage was still present (and empty)
**Solution:**
Since after the sign out, all user data are cleared, there is not need to request userInfo at all. Simple condition was added to prevent it. …
> Fix of opening account panel after sign out

- .github/workflows/autotests.yml
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/projectsmodel.cpp
- app/sources.pri
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
Nice format of last update of a project - `<duration><period_name> ago`, where 
- duration is length (number) of a period
- period name - one of: minute, hour,  week, month, year
Things to consider:
(**A**) The formatting is applied for both server and local projects (items), but the logic is untouched. Currently (or after models refactoring), it could be confusing what is actually "update" time. Current logic is that if a project is (also) local, it takes last modified timestamp of projectDir, otherwise takes serverUpdated timestamp. So if there is an update on server after your local changes, a user will see only time difference after local update. I guess this can be consider as bug or feature, so its up to discussion.
(**B**) A lastModified timestamp of a projectDir is used, which …
> Format time of sync

- app/projectsmodel.cpp
Fix of incorrect cleaning of the project model after fetch more project action.
After each request of listing project, the model was cleared. Therefore Input loses projects fetched in previous request. Additionally, fetch more option was always there even if there were no more projects to fetch on Mergin, because projects model never reached the same amount of project as were on the server due to cleaning. That caused the issue reported in 1360.   
closes #1360
> Fetch more bug

- app/qml/main.qml
Reverted code to use showMessage as in previous versions.
closes #1379
> Fixed auth failed message

- app/qml/LoginForm.qml
- app/qml/components/PasswordField.qml
Virtual Keyboard on Android steals Key event and therefore to unfocus a field, a user has to double click on return/back button to lost focus which updates the page to its default state.
Therefore focus handling was improved.  
Altogether with #1384 (scrollable Login form) should enhance user experience of Login form.
closes #1333
> Correct handling of focus of LoginForm fields

- app/qml/FeaturePanel.qml
Replaced old reference for attribute model with attributeController (deleteFeature)
closes #1398
> [new forms] delete feature

- app/attributes/attributecontroller.cpp
- app/attributes/attributetabmodel.cpp
- app/attributes/attributetabmodel.h
- app/qml/FeatureForm.qml
Fixes tab visibility. Needs to be further tested with more complex projects, `1_form_test` is working
Problem was, that expression result for visibility was not being saved and used. Also added `TabIndex` to TabModel to be able to reference specific tab from QML.
Resolves #1399
> Group visibility

- app/attributes/attributecontroller.cpp
- app/qml/FeatureForm.qml
Cannot replicate issue with hasChanged dialog, however there were some related minor issues:
* Forwarded key events from widgets 
* fixed tab button stealing a focus
* New feature registered as change
> Fixed back button of FeatureForm

- app/attributes/attributecontroller.cpp
Shows fields that are outside of groups (not tabs) as it was before refactoring.
Added check if group is a tab or not and behave based on that 
Example project from the issue now renders correctly:
resolves #1412 
credits to PP
> Fields outside groups

- app/qml/editor/inputrange.qml
For following field config:
precision =  _p_, step precision = _sp_, that _p_ < _sp_ (e.g _p_=0, _sp_= 1 for step=0.1)
was range widget not working properly.
Another issue was that if `Minimum` or `Maximum` in config was out of range for QML Integer, the spinbox got broken.
Since QML spinbox works with QML integers for its properties (value, from, to, stepSize), all these properties have to be multiplied. This shrinks actual range that could cause overflow issue. Best to get spinbox working with doubles/reals.
However, not sure if it should be done in scope of this PR (?).
Tested on lutraconsulting/decimal_issue and  lutraconsulting/test_decimals projects.
docs: https://github.com/lutraconsulting/input-docs/pull/35
test (E): https://github.com/lutraconsulting/input-manual-tests/issues/6 …
> Range widget improvement

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
Default values were always being applied when form was opened for newly created feature. 
In this case default value expressions were being evaluated on every update even when `apply-on-update` was switched off.
Resolves #1421
> Fix condition for default value evaluation

- app/attributes/attributecontroller.h
- app/qml/FeaturePanel.qml
- app/qml/main.qml
Edit geometry of a (point) feature was originally implemented for existing features, so the case for new features was not working properly. This PR fixes this case.
https://user-images.githubusercontent.com/6735606/120173991-e4402980-c204-11eb-8592-f16a84853fce.mp4
closes #1380
> Fixed geom edit of a new feature

- app/projectsmodel.cpp
- core/merginapi.cpp
- core/merginapi.h
This is a hotfix of #1437
This is what we did when project should migrate to Mergin:
1. Create empty Mergin project with the same name as local project
2. Send start uploading request
3. If the previous request failed with storage limit, we would show to user that he does not have sufficient storage left 
But the project created in step 1 remained! 
This PR removes the project from step 1. Although it would be better to not create it at all, we need a support for this on Mergin, created ticket: https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/703
> Autoremove of empty project

- app/qml/PreviewPanel.qml
Wrong enum has been used in preview panel, therefore photo preview was not working at all.
Beside it, display name work as expected and its shown correctly as title in preview Panel - tested with lower, upper case and also when field name contains some special chars (e.g !@#$,..).
Demonstration of image preview + display name as the title using fields with upper case.
closes #1276
> Fixed attributePreview type enum in QML

- app/qml/AccountPage.qml
Added ScrollView wrapper for its content and the footer.The footer has been simplified as well - dummy spacer replaced by property config for the footer. 
Header stays always on the top - back button and title is located which is always handy.
Also thinking about having generic scrollable wrapper component so it can be used for all pages. Currently, at least Subscribe page is still not optimised for landscape mode.
https://user-images.githubusercontent.com/6735606/120474607-b267c800-c3a8-11eb-8c58-3db6377f58e6.MP4
closes #933
> Scrollable account page

- core/merginapi.cpp
- core/merginsubscriptioninfo.cpp
Changed endpoint and handling of the reply accordingly.
There is also a second part of the ticket that is rather user-related: to unify loading of userInfo + userSubscription data, so the page content will be shown after both request are finished. 
Do we want to add there a loading indicator and have a blank page till data will be fetched?
closes #1375
> Changed endpoint for subscription info

- app/loader.cpp
- app/loader.h
- app/qml/main.qml
See #1452 
> I wanted to remove the `setActiveLayer` function with string parameter, however we use it here: https://github.com/lutraconsulting/input/blob/master/app/loader.cpp#L110
EDIT:
JS/QML handling of overriden function is different, so the most probable scenario was that qml tried to call the pointer version of this function with string argument (resulting in nullptr). https://stackoverflow.com/questions/28529776/qt-qml-and-method-overloads thus I have removed the `Q_INVOKABLE` keyword
> Replaced name property with instance itself for map layer

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/test/testattributecontroller.cpp
- app/test/testattributecontroller.h
- test/test_data/planes/MixedTabsFieldsForPlanesLayer.qml
- test/test_data/planes/SimpleGroupsForPlanesLayer.qml
Evaluation of the form is done in advance before creating form items. If field and container elements are mixed, then tabs are ignored and all elements are put into single root container. This should be the same behaviour as it was before (v0.9.6 before form refactoring).
For having tabs, all elements must be put into a tab.
Some use-cases may not be considered and for sure some not covered by tests. Also best to write documentation what is expected behaviour for each use-case. Shall it be added in the scope of this ticket?
Test with `documentation/form_setup` and `documentation/form_cascade` and the project from issue.
Added automatic tests.
NOTE that iOS build is failing due to version clash.
https://user-images.githubusercontent.com/6735606/122062174-73e1fc80-cdef-11eb-9c4e-05307fe131db …
> fix mixed tabs & fields in form [regression 0.9.6->0.9.7]

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/inpututils.cpp
- app/inpututils.h
- app/projectwizard.cpp
- app/projectwizard.h
- app/qml/ProjectWizardPage.qml
If widget setup is empty, Input tries to guess widget automatically - note that only numbers, date/time, bool fields are straightforward - for instance, external (photo) widget cannot be guessed only according field type (any ideas how handle such case?)
Added also QgsQuick import in WizardPage (its using QgsQuick.Utils.dp)
tested with project provided within the issue.
closes #1464
> Guess widget type for an empty field config

- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/SearchBar.qml
Also ProjectPanel needs the same fix as it was applied for BrowsingData panel.
Most likely, it would be needed always for the search bar.
Verified that this is Android issue and cannot be replicated on iOS
closes #1420
> Applied focus fix for search bar

- app/attributes/attributecontroller.cpp
- app/attributes/attributedata.cpp
- app/attributes/attributedata.h
- app/attributes/attributeformmodel.cpp
- app/attributes/attributeformmodel.h
- app/featureslistmodel.h
- app/inpututils.cpp
- app/main.cpp
- app/qml/FeatureForm.qml
- app/qml/FeatureFormStyling.qml
- app/qml/FeaturePanel.qml
- app/qml/editor/inputrelation.qml
- app/qml/main.qml
- app/qml/qml.qrc
- app/relationfeaturesmodel.cpp
- app/relationfeaturesmodel.h
- app/sources.pri
We are currently able to show relations in new widget called `inputrelation.qml`
How it work:
- relation widget type (form qgis) is handled as another form item (see `AttributeController::flatten`)
- relationFeaturesModel (derived from featureslistmodel) receives `QgsRelation` and provides the data to relation widget
- relation widget has 3 states: 
- _initial_ = there is only text saying how many features are linked
- _expanded_ = widget expands to three lines with features listed (their display text is used). If feature contains more linked features than can be displayed (see attached video in 0:10), we only show the first n.
- _page_ =  (not yet implemented) separate page with all linked features listed ~> will be implemented in **future PR**, because some qml changes need to be done …
> Show relations in form

- app/featureslistmodel.cpp
Added test if related layer has any field and if the layer has fields needed for creating relation.
Note that both key and value fields have to be present (might be the same field though).
Also simplified code since we already got field names from the config, so we dont need to fetch field itself and get name out of it. Only if it handles also aliases or any other case? From quick look on QgsFields implementation it looks safe though. What do you think?
Tested with project provided in https://github.com/lutraconsulting/input/issues/1226
closes #1257
> Fix of crash when value relation is missing referenced table/fields

- app/qml/editor/inputtextedit.qml
Issue affects not only multiline, but also simple textEdit widget (after range widget PR).
As it was reported, value has not been applied when user scrolls away - so a widget gets out of the feature form's viewport and is destroyed afterwards. There was no other signal emitted (e.g of losing focus or editingFinished), so value has not been committed. 
Such extra handling has been added on destroy event.
The condition of saving a new value is that it has to be different from original value. So its questionable if after changing a value and then reverting it back without committing it in between should or should not trigger `valueChanged` (and updating the form afterwards). Current implementation ignores such case.
test project `tin1/form_widgets`
Note that PurchasingTest failed.
closes …
> Use onTextChanged for multiline-text edit widget.

- app/inpututils.cpp
- app/inpututils.h
- app/qml/ExternalResourceBundle.qml
- app/qml/editor/inputexternalresource.qml
- app/qml/editor/inputrelation.qml
- app/relationfeaturesmodel.cpp
- app/relationfeaturesmodel.h
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
Added gallery widget for relations with images.
**When is shown:** (can be discussed)
The widget is shown if there is an image field if field widget type is 'ExternalResource'.
Note that it can be also beneficial to use some keyword as part of a field name, to clearly specify which field suppose to be used to show relation image. Input would give it priority before the first 'ExternalResource' field.
If we want to have it, what would be the keyword?
**Behaviour:**
Gallery can be browsed from left to right. Opening related feature or showing a preview is not implemented yet.
If image is not available or is missing, an icon is shown instead.
In order to resolve path for images, some functions were moved from inputexternalresource.qml to input utils.
Also test have been added for those …
> Added gallery widget for relations

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/featureslistmodel.cpp
- app/featureslistmodel.h
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/FormsStackManager.qml
- app/qml/editor/inputrelation.qml
- app/qml/form/FeatureForm.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FormWrapper.qml
- app/qml/main.qml
- app/relationfeaturesmodel.cpp
- app/relationfeaturesmodel.h
Added ability to work with child features in relations. 
When creating new child feature, `Relation Reference` field is automatically prefilled with its parent id. This is done by assigning the AttributeController with `parentController` (of type AttributeController) and `linkedRelation` (of type QgsRelation). When both properties are assigned, (child) controller looks for relation reference field and updates its value with parent's id.
However, if parent id is not yet valid (in case the parent feature is also being just created), we first commit the parent feature to get its id and then update the child feature relation reference field. To be able to do this, child controller is listening on `featureIdChanged` signal from parent controller.
When you cancel creation of parent feature that …
> Add, edit and remove features in relation

- app/attributes/attributecontroller.cpp
The issue seems to be related with evaluation of cascade expressions, when expression value depends on another expression value that has been evaluated just before.
Seems like updating expression context has fixed it.
closes #1543
> Fixed of cascaded expression evaluation

- app/featureslistmodel.cpp
- app/qml/editor/inputvaluerelation.qml
- The widgets generates the error while calling string function on QVariant (with number value): closes #1522 
- Removed white spaces from value comparison: closes #1498
> Fixed value relation widget error

- .github/workflows/qgsquick.yml
We are currently not using the most recent qgsquick version from QGIS and so qgsquick check is always failing. 
I changed it to be compared to the version from Input-SDK https://github.com/lutraconsulting/input-sdk/blob/2d4d7623320df72c1c779196d62ccd47305caba5/android/recipes/qgis/recipe.sh#L10
> Temporary fix qgsquick check by comparing Input-SDK QGIS version

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
- test/test_data/mergin-config-project-dir.json
To prevent download images files to Input client from the server.
Selective sync is supported only on Input (client) and has to be configured manually ATM by defining a config file. The idea is to have a tool for setting a configuration up in the mergin plugin.
Note that only images files (not case sensitive extensions: *.jpg, *.jpeg, *.png) are restricted from the sync which are located at `input-selective-sync-dir` or its subdirectories - a client can upload images, but doesn't download images from the server according the configuration. However, all images files are listed in `.mergin.json`. 
The config file:
- named as `mergin-config.json`
- is located in the project directory
- has JSON format
- is rather generic so can be used not only for selective-sync
- contains following …
> Selective sync

- app/qml/FormsStackManager.qml
- app/qml/editor/inputrelationreference.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FormWrapper.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
This PR mainly adds possibility to create linked features in relation widget with geometry. 
Workflow: 
1. Open form with relations widget 
2. Click on `edit` (if it is form of existing feature)
3. Click on `+ add` in relations widget
4. If the linked layer has geometry, forms will hide and you will see map in record mode. After geometry is recorded, form will show up (including previously opened forms)
5. If the linked layer is no geometry layer, just new form will be opened 
Technical details:
- we have one map with different states (`view` / `edit geometry` / `record features` / `record features in specific layer only` <- used to create linked features )
- we hide opened forms (close them without destroying, in state `hidden` ) when geometry is being edited or new feature is being …
> Add features with geometry from relations widget

- app/qml/components/ProjectDelegateItem.qml
Synchronization is now allowed for projects that are _grayed out_ - invalid due to having no project files or more than one. 
I also changed the color of the sync and three dots (more menu) icons for invalid projects from grey to orange to indicate that they are working (see `tomas/selective-test` below).
Resolves #1547 
NOTE: In order to change the validity of a project (when synchronization fixes a project), app must be restarted.
> Allow synchronization of invalid projects

- app/test/testmerginapi.cpp
- core/merginapi.cpp
- core/merginapi.h
- core/project.cpp
Changed selective sync behavior to download mergin config file in advance of updating a project.
Current project update behavior:
a) request project info
b) if server project contains `mergin-config.json`: 
1. request it
2. cache mergin config to transaction
c) proceed with project update and ignore files based on the cached config
Note: we also download the mergin-config file in order to be able to ignore files when doing upload (in this case we read the local version of the config). We also read the local config version when computing project state - because files that are not downloaded would be considered as `local deleted` in next sync
Note 2: If user would create `mergin-config.json` directly on his device, he needs to first sync it to server in order that it works!
Closes #1590
> Cache mergin config before update

- core/merginapi.cpp
When synchronization is interrupted by loosing internet connection (e.g. turning off the wifi), Qt on Android _sometimes_ (unknown what causes this) returns reply with error message filled with extremely long (sometimes > 80.000 lines) hex message with random characters. Probably they did not put string terminating sign at the end or something similar. 
In Input we show user the response from server. On Android we use toasts for that. Android thus tried to display 80.000 lines of random chars in toast which resulted in ANR. 
Fixed this on two places: 
- First, limited the number of chars we accept from network response (when the response is not in json format)
- Second, we no longer show server error messages to user. Instead, general error message is showed in qml to user stating that …
> Fix network unlimited error message

- app/qml/map/MapWrapper.qml
When state of `_gpsState` did not meet any criteria, it defaulted to black color.
Fixed by 1) initializing the gps indicator color and 2) making sure there is always one GPS state valid
Fixes #1601
> Fix black GPS dot

- app/attributes/attributecontroller.cpp
Uses `QgsRelation::name` when label is empty.
fixes #1569
> Show relation name when no label is provided

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
- test/test_data/mergin-config-corrupted.json
There was a case when `mergin-config.json` was invalid, Input would repeatedly ask Mergin for new one.
Fixed it by considering invalid config as if it would not exist. 
Fixes #1618
> Fix inifnite loop when config is invalid

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/qml/editor/inputdatetime.qml
- app/qml/form/FeatureFormPage.qml
PR fixes several bugs from #1630:
- `Save` button in feature form did not respond correctly with `hasValidationErrors` of the AttributeController - `hasValidationErrorsChanged` signal was not being emited
- Typo in `editorValueChaged` signal in `DateTime` editor made some fields to not save their value
Moreover, popup with text _Feature could not be saved, please check all required fields_ is now shown each time user clicks on `Save` button (when controller has any validation error).
> Validation fixes

- app/featurelayerpair.cpp
There was an issue that when you set up project with no geo layer having relation to other no geo layer, relations in forms did not work (you could not see any features).
This issue was actually in a way we check if feature is valid. For no geometry features, we **were always returning False!** 
Resolves #1624 
@wonder-sk could this potentially break something else?
> Fix nested relations - geometry check

- .github/workflows/autotests.yml
- .github/workflows/ios.yml
Use specific `macos-10.15` for iOS builds, latest is not working. Created bug #1690
> Use specific macos version for CI

- app/qml/editor/inputtextedit.qml
We used to commit text right after user typed in a character to avoid uncommitted text on Android. This however made iOS to input characters on some keyboards twice. Fixed it to apply commit only on Android devices
Resolves #1708
> Autocommit input text only on Android to avoid iOs double typing

- app/qml/editor/inputvaluerelationcombobox.qml
- app/qml/editor/inputvaluerelationpage.qml
- app/valuerelationfeaturesmodel.cpp
- app/valuerelationfeaturesmodel.h
This PR fixes two different issues that led to binding loops and subsequently to app crashes:
1. When value relation had incorrect path set in `LayerSource` config key (referenced layer was invalid), editor still tried to use convert functions from/to qgis vr format. This however led to unnecessary emission of `invalidate` signal, which resulted in loop and 💥. Fixed this by adding flag to VR model indicating if the model is ready to use ~ found a valid referenced layer.
2. Emission of `invalidate` signal had one more issue - we emitted it even when value of the editor is already NULL. Added check that prevents emission of the signal in such case.
PR is marked as draft, because we want to imitate QGIS in case of the first issue - QGIS is somehow capable of resolving layer even with wrong …
> Fix value relations binding loops

- app/i18n/input_en.ts
- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/ProjectListPage.qml
- app/qml/ProjectPanel.qml
- app/qml/components/TextWithIcon.qml
- app/qml/misc/AttentionBanner.qml
- app/qml/qml.qrc
- core/merginsubscriptioninfo.cpp
- core/merginsubscriptioninfo.h
PR adds 'Attention required' banner in Project Panel. Its purpose is to draw attention of user that there is some issue which needs to be resolved in Mergin dashboard.
Appearance of the banner depends on flag coming from server response (`/v1/user/service`). Status is refreshed on panel open action to ensure current state is reflected before sync.
Resolves #1731
> Add attention banner

- .github/workflows/qgsquick.yml
Removed comparison of qgsquick lib from a specific commit to the latest qgis master.
Also changed that qgsquick check now runs on each change in app/* too.
> Compare qgsquick to latest QGIS again

- app/test/testmerginapi.cpp
Any changes to `gpkg_contents` meta-table are ignored...
> Fix mergin api tests after upgrade to geodiff 1.0

- .github/workflows/macos.yml
macos workflow file contained old name of `autotest workflow` and thus did not rerun when only the workflow file changed.
> Fix MacOs workflow file name dep

- .github/workflows/ios.yml
- app/ios/Info.plist
- core/coreutils.cpp
- scripts/ci/ios/ccache_clang
PR fixes iOS build after changing infrastructure of SDK to static builds.
**Important change**
We changed the way of constructing version numbers if IPAs. 
- Previous format: `<1/2 depending if branch is master or not>.<ios sdk version>.<timestamp>` 
- New format `<1/2 depending if branch is master or not>.<input sdk run number of used sdk release>.<timestamp>`
> iOS CI build after AAB

- .github/workflows/android.yml
- app/version.pri
PR fixes CI build for Android. There was an issue with environment and local variables comparison in qmake. Renaming helped.
There was also an additional slash which resulted in some weird values being assigned to vars.
> Remove env vars ambiguity

- app/qml/AccountPage.qml
- app/qml/SubscribePlanItem.qml
- app/qml/misc/AttentionBanner.qml
TextWithIcon has changed and we missed to upload its needed properties. PR sets height to all occurences of `TextWithIcon`.
Resolves #1773
> Height issue for TextWithIcon

- app/qml/InputStyle.qml
- app/qml/components/DateTimePicker.qml
- app/qml/editor/inputdatetime.qml
- app/qml/qml.qrc
Previous calendar used `quick controls 1`. We thus needed to replace it with new one.
New calendar look:
https://user-images.githubusercontent.com/22449698/145367793-37b15f82-a3ca-475e-b850-4fa6be31fd76.mp4
@jozef-budac if you want, I created project `tomas/test_datetime`(dev) that contains all different combinations of datetime widgets.
> Replace datetime(calendar) widget from controls1

- app/main.cpp
Without this, Input would fail to do _some_ transforms (where the database access is needed). For example, GPS info window would show project X/Y coordinates with the same values as lat/lon even when using a projected CRS (such as web mercator) - it's possible to test e.g. with `lutraconsulting/test_digitizing` project.
Output error messages such as
```
PROJ6 error: The Input has failed to load PROJ6 database./proj/proj.db\n"
InputPROJ: Input Search Paths ("/proj")
InputPROJ: Custom Search Path "/proj_custom"
InputPROJ: found 0 projects with custom projections
...
proj_create_from_wkt: Cannot find proj.db
proj_create_from_database: Cannot find proj.db
proj_identify: Cannot find proj.db
proj_create: Error -38: failed to load datum shift file
...
pj_obj_create: Cannot find proj.db
...
```
> Fix path to proj database (proj.db) on desktop builds

- app/qml/components/TextWithIcon.qml
PR adds right padding to component that is used in attention banner ~ the same padding is applied on left (before icon).
Resolves #1802
> Attention banner padding

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- app/compass.h
PR adds `concurrency` to workflow files for ios/mac/linux/android. When you push new changes to a branch, already running workflows **on the same branch** are going to be stopped automatically.
Moreover, to make autotests a little bit more stable, I added concurrency also for autotests file. It does not have the `cancel-in-progress` option set, so already runnning tests **on different branch** are not going to be canceled. However, if there would be some workflows waiting to start autotests, this queue will be cleared. See more here: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency
Resolves #1843
> Set up concurrency between workflow runs

- scripts/copy_to_qgis.bash
`qgsquickutils` class has been removed from QgsQuick. `copy-to-qgis` was previously checking its existence in order to determine whether it has correct paths. Changed the utils class to mapcanvas.
> Change test file in copy-to-qgis script

- scripts/update_all_versions.bash
whitespace in `VERSION_FIX` made the script unable to update point version number for android in `versions.pri`
> Fix version script for Android point release update

- .github/workflows/qgsquick.yml
- qgsquick/qgsquickmapsettings.h
PR updates used version of QGIS for comparison of `up-to-date` qgsquick sources. It is still 3.22 QGIS but contains backported changes to qgsquickmapcanvas.qml and other quick files. These files are already released in the latest (1.2.0) Input version  
> Note: QGIS version has **not yet** been updated in Input-SDK!
> Update compared qgis version with latest changes to mapcanvas

- app/appsettings.cpp
- app/appsettings.h
- app/bluetoothdiscoverymodel.cpp
- app/main.cpp
- app/position/bluetoothpositionprovider.cpp
- app/position/internalpositionprovider.cpp
- app/position/positionkit.cpp
- app/position/positionprovidersmodel.cpp
- app/position/positionprovidersmodel.h
- app/qml/InputStyle.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/misc/AddPositionProviderPage.qml
- app/qml/misc/PositionProviderPage.qml
- app/qml/qml.qrc
- app/sources.pri
- app/test/testpositionkit.cpp
PR adds UI for position providers page and adding new GPS receiver page based on design doc. To change position provider navigate to settings -> `Select GPS receiver`.
Internal GPS provider is the default device GPS receiver. Desktop platforms have there also additional simulated provider.
Showcase video:
https://user-images.githubusercontent.com/22449698/150008161-c6e2c8c4-296a-4007-ba29-f86bdb91482d.mp4
**Note: connection to BT device still needs a little love, we need to show somehow that mobile is trying to connect to a device.**
Note2: that `eeee` device is just test, it is thus duplicated on video. With normal devices it does not happen.
@PeterPetrik I have not removed all TODOs from previous PR. There will be another one :)
> Selection of position providers

- app/loader.cpp
- app/loader.h
- app/main.cpp
- app/position/positionkit.cpp
- app/position/positionkit.h
- app/qml/NavigationPanel.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/PositionMarker.qml
- app/qml/misc/AddPositionProviderPage.qml
- app/qml/misc/GpsDataPage.qml
- app/qml/misc/PositionProviderPage.qml
Changed position kit to be a singleton in QML. Previously we needed to pass `PositionKit` qml instance all over the place. It is handy to be able to access device position from any part of the app.
> PositionKit as QML singleton

- app/bluetoothdiscoverymodel.cpp
- app/main.cpp
- app/position/bluetoothpositionprovider.cpp
- app/position/internalpositionprovider.cpp
- app/position/simulatedpositionprovider.cpp
There were two cpp issues with providers:
1. lambda functions did not have context so after a provider was deleted, lambda became dangling pointer and crashed
2. constructor called on overridden virtual method without explicitly noting which version to take (I found out that it is a _no no_ in cpp https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP50-CPP.+Do+not+invoke+virtual+functions+from+constructors+or+destructors)
> Position providers cpp fixes

- app/position/internalpositionprovider.cpp
- app/position/internalpositionprovider.h
`InternalPositionProvider` previously had to have both geo sources (position and satellite) valid in order to start receiving updates. This is wrong on few devices including Apple, where `QGeoSatelliteInfoSource` does not work.
Provider now works in a separates validity of each of the two sources and acts based on that (turns them on/off).
Position can now be read also on mac! :)
> Make satellite source optional (fixes Apple)

- .github/workflows/ios.yml
- .github/workflows/macos.yml
- app/main.cpp
- app/qml/misc/PositionProviderPage.qml
From position providers list user could click on the same item multiple times which resulted in instantiation of x providers (of that type).
Even though position kit do not accept the same provider, this was dangerous for bluetooth providers as they rely on Android sockets and instantiation of them multiple times (~ > 8) led to a crash.
> Disable building the same provider twice

- app/androidutils.cpp
- app/androidutils.h
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/qml/misc/AddPositionProviderPage.qml
Added check if bluetooth is turned on before starting discovery process. 
If:
- bluetooth is turned on, discovery process starts automatically
- bluetooth is turned off, show system dialog to enable bluetooth, if:
- user enables bluetooth in the dialog, discovery process starts
- user do not enable it, app goes back to list of existing providers and toast message pops up with text "You need to enable Bluetooth in order to connect new GPS receiver"
> Opt to enable bluetooth when it is disabled

- app/qml/components/DateTimePicker.qml
Previously we used manually translated months and days names in calendar. This is unnecessary step, Qt is provides us with translated names based on current `Qt.locale()`
> **Note:** This mean that even languages that are not translated on transifex yet will have moths and day names translated in their language.
Resolves #1865
> Use Qt translations in calendar

- app/bluetoothdiscoverymodel.cpp
- app/main.cpp
- app/position/abstractpositionprovider.cpp
- app/position/abstractpositionprovider.h
- app/position/bluetoothpositionprovider.cpp
- app/position/bluetoothpositionprovider.h
- app/position/internalpositionprovider.cpp
- app/position/positionkit.cpp
- app/position/positionkit.h
- app/position/simulatedpositionprovider.cpp
- app/qml/NotificationBanner.qml
- app/qml/components/BluetoothConnectionDialog.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/misc/PositionProviderPage.qml
PR adds option for bluetooth receivers to autoconnect after lost connection.
BT Provider tries to connect to receiver each 10 seconds after connection was lost. 
BT Provider now contains countdown system to keep user informed about next reconnect try.
Accuracy button now shows when app is connecting to GPS.
I have also replaced position provider's status and signals with unified `State`.
https://user-images.githubusercontent.com/22449698/151196887-46cf0aa6-7fa4-45f3-8d03-8b9d31d87dd1.mp4
> Autoreconnect for BT GPS receivers

- app/android.pri
- app/bluetoothdiscoverymodel.cpp
- app/bluetoothdiscoverymodel.h
- app/input.pro
- app/ios/Info.plist
- app/linux.pri
- app/macx.pri
- app/main.cpp
- app/position/internalpositionprovider.cpp
- app/position/positionkit.cpp
- app/qml/misc/PositionProviderPage.qml
- app/sources.pri
As iOS does not allow us to read serial from bluetooth device, this PR removes all connections to bluetooth API for ios build.
There is a new define "HAVE_BLUETOOTH" that is used on max/android/linux.
> Do not use bluetooth qt API on iOS platform

- app/position/bluetoothpositionprovider.cpp
- app/qml/components/BluetoothConnectionDialog.qml
As we added auto-reconnect  for bluetooth position provider, connection dialog window was jumping between states of "connecting" and "failed" and was very misleading.
I added another state "waitingToReconnect". It will be visible when you are connecting to **unreachable, but paired** device.
https://user-images.githubusercontent.com/22449698/151543470-0e1c25d0-4130-4dd6-abf3-45f4cfa50957.mp4
> Update connection dialog after reconnect 

- app/position/bluetoothpositionprovider.cpp
We need to invalidate position when user looses connection to its GPS. Previous fix did not work, we now invalidate it when he/she really loses the connection (in error handler).
> Invalidate position fix

- app/inputprojutils.cpp
This is still a workaround, just a subtle one.
I think the real issue is in qgis, where `PROJ_VERSION_MAJOR` is used in https://github.com/qgis/QGIS/blob/31ac4082f849c14e0aa6c6c16ca93e63c59756c0/src/core/proj/qgsprojutils.h#L215 and https://github.com/qgis/QGIS/blob/31ac4082f849c14e0aa6c6c16ca93e63c59756c0/src/core/proj/qgscoordinatereferencesystem.h#L51 without importing `proj.h` that defines it.
> Fix building with qgis built on proj 8

- app/qml/InputStyle.qml
- app/qml/map/Highlight.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/NavigationHighlight.qml
Instead of using map coordinates for line/polygon shapes and then `Transform` for map to screen conversion, we now use screen coordinates at the time the highlight is constructed ("reference") and the `Transform` just adjusts to the change of scale/offset when the map is moved/zoomed. While both of these approaches seem equivalent, the difference is that in the former case, the `Transform` would deal with big numbers (for offsets), causing numerical issues due to single precision floating point math. Now the calculation with big numbers is done with doubles before creating shapes, and the transform deals with much smaller transforms. This does not make the issue go completely away, but it should be much less apparent under normal circumstances.
Also fixes typos "highligh" -> "highlight" …
> Fix highlight numerical precision issues

- .github/workflows/linux.yml
- app/compass.cpp
- app/inpututils.cpp
- app/inpututils.h
- app/position/abstractpositionprovider.cpp
- app/position/abstractpositionprovider.h
- app/position/mapposition.cpp
- app/position/positiondirection.cpp
- app/position/simulatedpositionprovider.cpp
- app/position/simulatedpositionprovider.h
- app/qml/NavigationPanel.qml
- app/qml/components/InputText.qml
- app/qml/components/SimpleTextWithIcon.qml
- app/qml/components/Symbol.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/qml.qrc
- app/test/testposition.cpp
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
PR adds short mode for stakeout. 
Short mode is activated when your position is below one meter from the destination point. It allows users with high-precision GNSS receivers to better orientate in the field when going close to a feature.
When distance between your position and target point is under 10 cm, navigation goes green.
Showcase:
https://user-images.githubusercontent.com/22449698/152962912-d8c143b0-14b6-45f8-adbe-ebeb154b8883.mp4
**Visual UPDATE:**
https://user-images.githubusercontent.com/22449698/153176776-96313f01-4d20-46e1-86fb-fae9598699a7.mp4
For test purposes I also added another feature - long tap on a map changes your position to the place you tapped. _This is working only when you use simulated provider_
There are few issues to address in next PR:
- make the navigation …
> Stake out - short mode

- app/qml/NavigationPanel.qml
PR changes calculation of map extent to include size of gps marker (+ direction indicator). Previously, you did not see GPS marker when approaching a target from the bottom of the screen
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/153198735-10f4a19a-5ebf-404a-8a21-aee9646daf4b.png" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/153198732-af2a87c6-8fd2-44af-b4c0-53f7558dca48.png"  width="300"/></td>
</tr>
</table>
> Make navigation extent bigger to show GPS marker

- app/qml/FormsStackManager.qml
- app/qml/NavigationPanel.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/NavigationHighlight.qml
- app/qml/misc/GpsDataPage.qml
PR adds possibility to open GPS panel during stakeout. It no longer stops stakeout. Stakeout continues after GPS data panel is closed. In order to do that, I needed to do a small refactoring of how we do the stakeout. It now goes like this:
`
PreviewPanel (FormsStackManager) ---(sends signal that user wants to stake out)--> MapWrapper (starts navigation highlight and emits signal that stakeout started) --> NavigationPanel handles the signal and shows itself.
`
Previously `FormsStackManager` directly called NavigationPanel.
I also started to name new components "stakeout<xyz>" instead of navigation. Navigation is more like routing. I will rename all remaining components once this one is merged - did not want to make this one unreadable :) 
It also includes few other enhancements:
- back …
> Stake out - show gps panel

- app/qml/StakeoutPanel.qml
PR alters close-range stakeout window so that it correctly represents distances on different screens. Two circles inside close-range stakeout represents distances:
- inner circle -> 0.5m from target
- outer circle -> 1m from target
Previously on different screens this did not show properly
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/153548024-0bcbc379-70b5-4b40-8e0f-a3214cc0a34e.png"  width="350"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/153547995-7f341228-a975-40c0-b359-da3ffb478e13.png" width="350"/></td>
</tr>
</table>
> scale close range mode window

- app/position/bluetoothpositionprovider.h
Changes reconnection "try again" timeout to 5 secs (from previous 10). It turned out to be too long to wait 10 secs
> Change reconnection time to GPS receiver to 5 sec

- app/android/AndroidManifest.xml
- app/android/build.gradle
Android introduced property `queries` in manifest that should contain information about our use of external applications. It is called `Package visibility`. As we did not declare it, they disabled our access to device's camera.
In order to use the new `queries` keyword **we needed to update Gradle version** to new point release that Google released for [this use case](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html).
In the end the issue had nothing to do with `HIGH_SAMPLING_RATE_SENSORS` permission. However, on Android 12, sensor `TYPE_MAGNETIC_FIELD` (we use it in `OrientationSensor.java` to determine orientation when taking a photo) does not allow us to read data like we read it now (ASAP). 
_One more thing to note: …
> Fix camera issue on Android 12

- app/inpututils.cpp
- app/inpututils.h
- app/position/mapposition.cpp
- app/position/mapposition.h
- app/qml/StakeoutPanel.qml
- app/qml/form/PreviewPanel.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
- qgsquick/plugin/qgsquickmapcanvas.qml
Previous movement of map extent during stakeout was "very shaky". Extent have been unlimitedly zoomed in resulting in scales like 5mm or even smaller -> in that case even smallest change of gps position looked like movement of a 1 meter.
We are now moving extent based on conditions mentioned here: https://github.com/lutraconsulting/input/compare/stakeout-extent?expand=1#diff-7855d101d45d951847ae00d48eb0839f4cae76de50783fd4a4db4682b781e522R1334-R1341 Generally, we use distance between GPS and target point to determine the correct scale factor. We also do not zoom in more than 1:25 scale.
There were also several other issues fixed / enhancements:
- in `PreviewPanel.qml` I removed redundant `Connections` component and  used property binding
- in `PreviewPanel.qml` edit icon was shifted to …
> Stakeout extent movements

- app/ios/Info.plist
Updated list of translated languages in `Info.plist` based on current list of translated languages in `i18n/input_i18n.qrc`: https://github.com/lutraconsulting/input/blob/a4a0dbf4942db0240f70b1696bd8d803d7931ca1/app/i18n/input_i18n.qrc
> Add missing languages to ios

- .github/workflows/qgsquick.yml
We added new signal to qgsquick when user interacts with map canvas.
_Note: We no longer compare with QGIS 3.22 branch_
> Update QGIS version in qgsquick check

- app/qml/StakeoutPanel.qml
When connection to external GPS was lost (e.g. when user minimizes the app) during stakout, stakeout panel had undefined behaviour (gets closed).
> Handle situation when position is lost during stakeout

- app/inpututils.cpp
- app/qml/misc/GpsDataPage.qml
`QGeoCoordinate::toString` function takes input in order `(lat, long)` which is different than in QGIS (and Input too) - `(long,lat)`.
Good catch @jozef-budac!!
#26mg000[review]
Closes #1960
> Fix replaced lat/long in GPS data panel

- app/qml/map/Highlight.qml
In #1950 I removed the entire `updateGuideline` function as we moved to a different handling of transformations in `Highlight.qml`.
However, I forgot to add a piece of code that triggers repaint of QML shape when the geometry is empty. Here: https://github.com/lutraconsulting/input/commit/59ed5f89ee45d5031fbae19725073a6eab7ab6a2#diff-c1350d1e69584b4f380f7721e2721f360b8f1417f9b94629abfd240dfd3df883L94-L98
Thus, the issue was that QML shape responsible for painting guideline did not repaint itself when it received empty geometry (newGuideLineElements was empty).
I have also added a little optimization - we do not need to reconstruct highlight when position changed in _NOT_ recording state. It is used only in guideline and that is visible only when we are in recording state.
Closes #1958
> Trigger repaint for empty geometry of guideline path

- app/test/testmerginapi.cpp
`testListProject` has been using listProjects API without tag `created` which returned all public projects created on test server. This was fine when we had only one test user. Created project was always found in the first 50 public projects on the server (50 due to a pagination).
However, with #1953 each user creates tens of projects, so now the created project was not in the returned list (it would be on some other page).
I changed the test so that it queries only `created` projects of the current user - it is like this in other tests too.
> Fix autotests - use created projects instead of all public projects

- .github/workflows/macos.yml
- app/test/testmerginapi.cpp
- app/test/testpurchasing.cpp
- app/test/testutils.cpp
- app/test/testutils.h
- core/merginapi.cpp
- core/merginapi.h
PR makes auto tests fine to run in parallel by adding a unique user that is used during auto tests.
Autotests can now be used in two ways:
1. We either pass env variables as we used before - in this case Input will use the provided credentials, or
2. Do not pass credentials via env variables - in this case Input will register new unique user and fills its credentials to env var
I also made all test projects public, so that we have easier access to them if something goes wrong
Resolves #902 
#23dnz99[Review]
> Unique user for autotests

- app/inputhelp.h
We had this issue in the console:
```
QQmlExpression: Expression qrc:/RegistrationForm.qml:214:9 depends on non-NOTIFYable properties:
InputHelp::merginTermsLink
```
`merginTermsLink` property was missing a required signal when its value changes. It must be there even though it is a constant value.
> Add missing notify property

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
Calling `listProjectsByName` API was missing a check for auth token expiration. 
When token was expired, server returned for private projects 401, which in Input was understood as user without sufficient rights and did not allow user to sync the project.
I also added check for API status - it is in all other calls too.
Resolves #1499
> Handle expired token in listProjectsByName API call

- .github/workflows/linux.yml
- .pre-commit-config.yaml
- docs/developers/README.md
- docs/developers/code_formatting.md
- scripts/format_cpp.bash
I wanted to add our `format_cpp.sh` script as pre-commit hook, but I came across this cool software called [pre-commit](https://pre-commit.com/#installation). It utilizes different pre-commit hooks and let's you easily set them up via yaml configs.
There are tons of already created hooks (https://pre-commit.com/hooks.html) we can try to add (in future). I tried the `check-yaml` and it seems to work fine.
I added docs so that anyone else can install it, but it is trivial actually - just `brew`/`pip` install and then one command: `pre-commit install` in the repo root.
> Add pre-commit hooks

- core/merginapi.cpp
- core/merginapi.h
In last sprint we fixed an issue with expired token in `ListProjectsByName` API.
This fix, however, did not only refresh the expired token, but also opted user to log in when his/her credentials were not set (not logged in).
Now it really just refreshes the token is auth data are set.
Before fix:
https://user-images.githubusercontent.com/22449698/158348713-940270cb-dd7b-4111-8a00-1613c95efb79.mp4
Now with fix it does not happen :)
> Let ListProjectsByName API call not opt for credentials

- app/codefilter.cpp
- app/codefilter.h
- app/qml/CodeReader.qml
- app/qrdecoder.cpp
- app/qrdecoder.h
PR fixes two things:
1. Fixes QRCode autofocus - it was there, but not enabled
2. Fixes / Adds ability to scan the same code twice in a row. There was a `Q_PROPERTY` that did not signalize its change (as the new scanned value was the same one as previous). I changed this to simple signal emission that we listen to in QML called `dataCaptured( data )`
https://user-images.githubusercontent.com/22449698/159451861-8693ed64-78b3-45d9-a936-0b217009b7f2.mp4
Resolves #1949 
Resolves #1647
> QRCode autofocus & ability to scan the same code twice

- app/qml/components/ProjectDelegateItem.qml
Some users/organisations have long names. This results in non-readable project names on small screens, as the names are eldided from the right side. To make project names more readable better to elide their names from the left.
Fixes #1996.
Before
After
> elide project name from the left side to keep project name more readable (fix #1996)

- app/ios/Info.plist
- scripts/check_ios_translations.py
We have way too many translations to check if Info.plist contains all of them manually. 
PR adds script `scripts/check_ios_translations.py` that goes via `input_i18n.qrc` languages and finds those that are missing in `Info.plist` file.
Run it like `scripts/check_ios_translations.py PATH_TO_INFOPLIST PATH_TO_INPUT18N_QRC`
Would be good to add this script to CI in future. Related to #1966
> Add script to check if info.plist contains all translated langs

- .github/workflows/qgsquick.yml
- app/qml/map/MapWrapper.qml
- qgsquick/plugin/qgsquickmapcanvas.qml
- qgsquick/qgsquickmapcanvasmap.cpp
- qgsquick/qgsquickmapcanvasmap.h
Without this user needs to pan/zoom canvas to see new/deleted features after sync.
Fixes #2007.
> clear render cache and refresh canvas after sync (fix #2007) + QgsQuick update

- app/test/testcoreutils.cpp
- app/test/testcoreutils.h
- core/coreutils.cpp
- core/coreutils.h
- core/merginapi.cpp
- core/merginapi.h
As discussed in https://github.com/lutraconsulting/qgis-mergin-plugin/issues/382 add `~` at the end of the conflicted copy if this is a QGIS project file.
> add special handling for the names of the conflicted files for QGIS project files

- app/attributes/attributecontroller.cpp
- app/qml/form/FeatureToolbar.qml
Hides "Delete" button when new features are created. To cancel editing session user should use Cancel button in the top left corner.
Fixes #2101.
> hide delete button when adding new features (fix #2101)

- app/attributes/attributecontroller.cpp
Request layer repaint request on successful commit, so any changes made in it will be immediately visible.
Fixes #2100.
> trigger layer repaint after successful commit (fix #2100)

- app/inpututils.cpp
- app/inpututils.h
- app/qml/ExternalResourceBundle.qml
This is needed as geodiff works only with files and empty directories are not synced. As a result if attachment widget is configured to use subfolder and this path does not exists capturing photos will fail.
Also show a warning dialog if copying image to the destination directory fails.
Refs #1611 and https://github.com/lutraconsulting/qgis-mergin-plugin/issues/278
> create directories used in the attachment widget configuration if they are not exists.

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/macos.yml
- app/qml/AccountPage.qml
- app/qml/ProjectPanel.qml
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
Add button to the Account page allowing user to remove Mergin Maps account.
When account removal requested user is informed that all local projects will be removed from the device and that he should manually cancel Apple subscription if there is one. Also user should type his username in the text field before proceeding.
In case if account removal failed an error message is shown.
Fixes #1896.
> Add delete account functionality (fix #1896)

- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/inpututils.cpp
- app/inpututils.h
- app/qml/StakeoutPanel.qml
PR just removes some old unused code and fixes one place (stakeout panel) that still referenced `__loader` instead of `__activeProject`
> Minor updates - remove unused code and fix old name for loader

- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/maptools/abstractmaptool.cpp
- app/maptools/abstractmaptool.h
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/maptools/splittingmaptool.cpp
- app/maptools/splittingmaptool.h
- app/position/mapposition.cpp
- app/position/positionkit.cpp
- app/position/positionkit.h
- app/sources.pri
This PR completely rewrites `DigitizingController`, there is a separate class for it now called `RecordingMapTool`. 
I have not yet removed the `DigitizingController`, it is still used inside QML.
Our current _"digitizing"_ process is a bit of spaghetti 🍝 ,  this is a first improvement out of few (next one `Highlight.qml` and `MapWrapper.qml`)
There are two TODOs in code I need to figure out, maybe @wonder-sk could help me there? 🙏🏻 (: 
The basic idea how the digitizing is going to work:
- `RecordingMapTools` will be instantiated from QML only for the time of recording a new feature (previously 🆙 all the time)
- `RecordingMapTools` holds recorded points, can add and remove them; on each change generates new `QgsGeometry ~ recordedGeometry` that will be used by `Highlight.qml` to show the …
> Add maptools - Refactoring of digitizing controller & splitting map tool

- .github/workflows/macos.yml
> Ignore QT and Input-SDK in CI coverall check

- .github/workflows/ios.yml
New builds submitted to Apple now need to have the `CF_BUNDLE_VERSION` higher than any previously sent builds. 
We used to compare branch names and based on that set the initial number, like this: `1(PR build)/2(build on master).xx.yyy`.
I changed it to `2.xx.yyy`, where 2 is constant, `xx` is INPUT_SDK build number and `yyy` is timestamp.
Resolves #2104 
Resolves #1786 
CU-2h19u7b
> Fix iOS CI

- app/snaputils.h
As can be seen on the video: https://lutraconsulting.slack.com/files/UT782RCHE/F03N0SD7TSM/recordit-1656507059.mp4 crosshair was invisible when "splitting" started. It was due to uninitialised properties.
> Initialize snapping properties

- .github/workflows/linux.yml
Linux CI build tried to install the `libcurl4-gnutls-dev` as part of some dependency. This lib was, however, unavailable until `apt-get update` runs.
> Fix linux broken curl link

- app/test/testutils.cpp
- app/test/testutils.h
Changes email address for autotest users from (non-existing) `@autotest.xy` domain to our domain. Emails can be filtered via `+`.
> Change email address for users created in autotests

- app/qml/map/RecordingTools.qml
Simply listens on `clicked` signal of map canvas in `RecordingTools`
> [GEOEDIT] catch mouse clicks in RecordingTools

- app/guidelinecontroller.cpp
- app/guidelinecontroller.h
This needs a lot of testing, but it can be an initial skeleton.
`GuidelineController` has activeVertexId to know which vertex to move in guideline, it changes its position to crosshair position.
> [GEOEDIT] Alter guideline - move vertex with crosshair

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/test/testmaptools.cpp
- app/test/testmaptools.h
Add method to retrieve vertex id from screen coordinates. Takes into account both real and "virtual" (mid points and start/end points) vertices, supports search threshold.
If there no veritices found within search threshol returns invalid vertex id.
> Look up vertex id from the clicked position

- .github/workflows/android.yml
- core/merginapi.cpp
- core/merginapi.h
We had a broken sync on Windows because `QDirIterator` on Unix systems ignores the hidden folders, but lists them on  Windows (as the folder can start with a dot). It resulted in `.mergin` folder files being scheduled for synchronisation. They were assigned a chunk id, but Mergin correctly ignored these files. This led to 404s due to chunk IDs mismatch.
I fixed this by ignoring all files in `.mergin` folder in `MerginApi::isInIgnore`. It should not change anything on UNIX systems as this folder was never listed (always ignored).
Note, our Windows release is still just experimental, so it includes other bugs.
> QDirIterator on Windows - Fix Windows sync

- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/map/RecordingToolbar.qml
- app/qml/map/RecordingTools.qml
More work on geometry editing support:
- update RecordingMapTool to edit geometry directly instead of rebuilding it from list of points.
- add Release button to recording toolbar and corresponding signal hanler (does nothing at the moment)
- connect RecordingMapTool with crosshair position
Small demo
> recording tool and toolbar updates

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/map/RecordingToolbar.qml
- app/test/testmaptools.cpp
More fixes and updates to the geometry editing:
- better threshold for selecting active vertex
- hide marker for active vertex
- hide handle and start/end marker if start/end point of the line is selected
- fix toolbar buttons availability depending on the current state
- show crosshair when new feature is recorded
- fix broken test
- remove unused code
> Editing fixes

- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
This issue is well described here: https://github.com/MerginMaps/input/issues/1417#issuecomment-863382773 
QT tries to exactly match systems' locale with a translation file we provide. This is a problem for codes like `en_US`, `fr_CA`, where we only provide file with name `en` or `fr`. These translation files would never be picked, despite being translated. To fight this issue QT has a following system: https://doc.qt.io/archives/qt-5.14/qtranslator.html#load-1 (TL;DR - if it can not exactly match any system language, it tries to cut out the country code and match only language codes). 
---
Imagine situation like this:
- Your system languages
1. `en_US`
2. `kr_KR`
- Input provides these translation files:
- `en`
- `kr_KR`
- QT tries to match it in two rounds:
1. exact match:
- `en_US` …
> Fix language selection for several languages

- app/android/src/uk/co/lutraconsulting/InputActivity.java
- app/androidutils.cpp
- app/androidutils.h
- app/inpututils.cpp
- app/qml/main.qml
This is an effort to reduce the number of crashes happening on Huawei devices when exiting the app with back button.
There are two fixes:
- First: we do not close the app immediately after the back button is tapped; instead, we show toast saying "hit the back button again to close the app". This way we reduce the number of accidental hits of the back button.
- Second: instead of letting QT quit the app, we now call Java to exit the app. This is due to some blogs/stackoverflow's that tried to find a workaround to this issue. See: https://developernote.com/2022/03/crash-at-std-thread-and-std-mutex-destructors-on-android/#comment-694101 and https://stackoverflow.com/questions/61321845/qt-app-crashes-at-the-destructor-of-stdthread-on-android-10-devices
So far the second fix is applied only to …
> Reduce Huawei crash rate on back button

- app/qml/map/RecordingTools.qml
- qgsquick/plugin/qgsquickmapcanvas.qml
- qgsquick/qgsquickmapsettings.cpp
- qgsquick/qgsquickmapsettings.h
Adds "jump" animation to map canvas. It animates a movement between two positions.
This is an initial implementation of animations in QgsQuick, we might want to better incorporate this into cpp map canvas when adding more animations.
https://user-images.githubusercontent.com/22449698/182368517-e3937610-336c-473a-912a-7c51fed33d24.mp4
> add jump animation when selecting vertex

- app/maptools/recordingmaptool.cpp
- app/test/testmaptools.cpp
Fixes tests by adjusting test polygons to match our edge cases (invalid polygon containing only two or one point). Also fix vertex collection code to take into account these edge cases.
> Fix failing tests

- .github/workflows/android.yml
- .github/workflows/ios.yml
PR unifies build versions between iOS and Android **(not app versions!)**
Previous iOS build version schema: 2(constant).XY(input-sdk version).TIMESTAMP
New iOS schema: YY.MM.number of commit with offset
New Android schema: number of commit with offset
> Note: Android supports only one number, while iOS build code can be in form X.Y.Z
New versions have a common Z, f.e.:
- Android build version: `112620`
- iOS build version: `22.08.112620`
Having SDK version in the build version was not an ideal solution. If someone updated SDK version in one branch, CI jobs in all other branches were failing then because their build versions were always smaller.
> Unify build version numbers on mobile platforms

- .github/workflows/i18n.yml
Translations CI now also automatically checks if `Info.plist` file includes all files listed in `input_i18n.qrc`
> Add Info.plist check step to translations CI

- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/form/FeatureToolbar.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingToolbar.qml
- app/qml/map/RecordingTools.qml
- app/test/testmaptools.cpp
Fixes some issues in geometry editing:
- expose active vertex geometry as a map tool property
- hide midpoints around active vertex
- fix removal of points in single- and multipart point geometries
- fix saving geometry changes in multipoint layers
- fix creation of empty multipart polygons (fixes redrawing)
- when editing singlepart point layer start edit with grabbed point
> Edit buffer support (pt 3) 

- .github/workflows/android.yml
- scripts/android-aab.bash
- scripts/android-apk.bash
Scripts to build apk/aab were previously changed (build path has changed), but workflow uploaders were not updated correspondingly. PR unifies those paths and updates the workflow file.
> Fix upload to artifacts on Android

- .github/workflows/android.yml
- .github/workflows/ios.yml
CI/CD version codes used `git rev-list` to come up with build numbers. This is not a good way of doing it due to force pushes, squashing and rebasing... iOS then often failed with duplicated/smaller versions being uploaded than are already on the testflight.
We now use GITHUB_ACTION_NUMBER and GITHUB_ACTION_ATTEMPT to determine the build number. This way it should be prone to any git operations and manual rerun of workflows.
PR also renames Android artefacts from out-release-signed.apk to something more meaningful :)
> Fix ios submission & rename artefacts

- app/android/AndroidManifest.xml
- app/android/gradle.properties
- app/main.cpp
PR sets default Qt quick theme back to `Basic`, resulting in our previous style.
PR also fixes an issue when `AndroidManifest.xml` could not be parsed by Qt Creator
> Fix ui for Qt6 and manifest parse error

- app/android/AndroidManifest.xml
For future reference and if someone comes along fighting errors like `QColor::fromRgbF: Alpha parameter out of range`  - set `android:allowNativeHeapPointerTagging="false"` in the `application` tag in `AndroidManifest.xml`.
It made the app unable to parse hex colour strings and simple colour names like "red" and others.
Qt Qt6 colour issue
See https://bugreports.qt.io/browse/QTBUG-97009
See https://github.com/qt/qtbase/commit/54576b3dd9990a62434cfb805b2f9158e3eaf8c4
See https://source.android.com/docs/security/test/tagged-pointers
> Disable native heap pointer tagging - fix Android color errors

- app/inpututils.cpp
- app/inpututils.h
- app/qml/ExternalResourceBundle.qml
Fixes opening of feature form.
`shortcuts.pictures` was a Qt5 way to get a path to the gallery on different platforms. `QStandardPaths` is a way to do it in C++.
Note: it is used only on macOS/Linux/Windows, iOS and Android have a native implementation. Unfortunately, this code runs each time form is opened no matter the platform.
> Replace unavailable qt5 shortcuts with standard paths in qt6 ~ fix opening of feature form

- app/android.pri
- app/android/AndroidManifest.xml
- app/android/build.gradle
- scripts/android-apk.bash
`AndroidManifest.xml` and `build.gradle` are now aligned with Qt 6.3.2 version of these files.
Things that has changed:
- `AndroidManifest.xml`:
- added:
- `android:allowBackup="true"` (see https://github.com/qt/qtbase/commit/56dee3de5e4ac1c4d37a2c5e27361e7ddbdea1a7)
-  `android:fullBackupOnly="false" ` (see https://github.com/qt/qtbase/commit/56dee3de5e4ac1c4d37a2c5e27361e7ddbdea1a7)
-  `android.app.arguments` <-- uncommented
- removed:
- `uses-sdk android:minSdkVersion="24" android:targetSdkVersion="31"` - setting minSdk and targetSdk has been moved to build.gradle file (see https://github.com/qt/qtbase/commit/519ea72108fae7f5c4ed7c3e9fed3a999a16ed73#diff-790ad42137a254b3eaddfe7fc2d7e0722ca055ebeec76a0beeab7a0bcf87e074)
- `android:extractNativeLibs="true"` - moved to build.gradle (see …
> Upgrade AndroidManifest and build.gradle files based on Qt6.3.2 version

- app/qml/editor/RelationPhotoDelegate.qml
- app/qml/editor/inputrelation.qml
- app/qml/form/FeatureForm.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- qgsquick/plugin/qgsquickmapcanvas.qml
Due to a Qt6 bug (https://bugreports.qt.io/browse/QTBUG-108821), tap events were being propagated to map canvas no matter what window was visible. 
This workaround changes the size of TapHandler's active area if a feature form is opened AND ignores clicks if any other window covers the map canvas.
Resolves #2363
> Fix autoclosing feature form

- app/android/AndroidManifest.xml
- app/main.cpp
BT permissions changed in Android 12, see https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher 
Legacy BT permissions are set to affect only up to Android 11, new permissions from Android 12 on.
The default allocation limit for uncompressed photos was not big enough to show photos taken with >30 megapixels cameras (128 MB). Images taken with such a camera were not loaded in the image preview.
Resolves #2385 
Resolves #2388
> New BT permissions for Android 12 and allocation limit for photos

- app/bluetoothdiscoverymodel.cpp
- cmake_templates/inputconfig.h.in
QGIS_QUICK_DATA_PATH resulted in ""\<path\>"" (note the double quotes) - MM could not read it then, it read something like "\\"\<path\>\\""
Therefore, assets could not be read.
> Do not wrap define value in string

- app/qml/main.qml
Enlarging the scope of the workaround for auto-closing form.
See more details at https://github.com/MerginMaps/input/pull/2387
We now block clicks (change size of TapHandler's area to 0) when something else than the map is visible.
Fixes #2409 
#326m37b
> Qt6 fixes/Do not propagate clicks to canvas when not using map

- app/qml/editor/RelationTextDelegate.qml
- app/qml/editor/inputrelation.qml
Previously we used signal `setInvisible` to indicate whether a child delegate should be invisible (no more space available in the editor).
It seems that some things changed in Qt6 and this signal was called several times due to dependencies between properties in `RelationTextDelegate`.
I changed it so that now each time a delegate decides if it is visible or not, `Repeater` recalculates the number of invisible items and updates the `x more` button accordingly.
Fixes #2413 
#326m2gq
> Qt6 fixes/Fix number of child relations

- app/qml/editor/AbstractEditor.qml
- app/qml/form/FeatureForm.qml
Replaces `MouseArea` in `AbstractEditor`(base class to refactored editors) with `TapHandlers` that receive clicks all the time.
>Note: The reason why `MouseArea` stops listening to clicks after double-clicking in this scenario remains secret.
Due to a Qt bug https://bugreports.qt.io/browse/QTBUG-109124 `SwipeView` steals grab on `Slider`'s handle which results in page swap instead of handle movement.
Fixed by making the `SwipeView` not interactive.
---
Fixes #2411 
#326m313
> Qt6 fixes/Range editor fixes

- app/qml/form/FeatureFormPage.qml
- app/qml/form/FormWrapper.qml
- app/qml/layers/LayersPanelV2.qml
Includes 2 fixes:
1. back button now closes only the topmost page in the layer's list, not the entire layers' panel
2. the topmost form receives an active focus when opened
Fixes #2407 
#326m3dk
> Qt6 fixes/Fix back button in layers list

- app/qml/editor/inputvaluerelationpage.qml
Fixes #2412
It turns out everything was working fine under the hood, it was just that the text of the widget was not appearing properly.
It looks like there is a Qt bug (at least as of Qt 6.4.1) in Text/Label item that will keep the item off the screen even if it was meant to render, in conditions like this:
- clipping is enabled
- the text is initially empty
- the text gets changed while the item is hidden, only then in gets visible
In any case, we should be using elide rather than clipping for text items, and that fixes the issue with visibility as well.
> Fix value relation widget that was sometimes missing labels

- app/qml/AuthPanel.qml
- app/qml/editor/AbstractEditor.qml
- app/qml/editor/inputrangeeditable.qml
Fixes a few things:
- Registration form, fixes #2406 
- Listen to a different signal in `AbstractEditor`, previous `onPressed` were called too many times, worsening the UX of forms
- Number inputs could end up hidden under the system keyboard in feature form if they were on the end of the form. They had an invalid width set
> Qt6 fixes/Fix focus in forms

- CMakeLists.txt
- app/test/inputtests.cpp
- app/test/testactiveproject.h
- app/test/testmerginapi.cpp
- app/test/testutilsfunctions.cpp
- use test_data from build dir
- and fix crashes
- fix autotests - problem was that the INPUT_TEST_DATA_DIR (from qmake) was no longer defined in our cmake build -> we need to use TEST_DATA_DIR from inputconfig.h
> fix auto tests

- app/activeproject.cpp
fix #2436 
note: on macOS desktop, if I click outside the window, it stays on the "opening project" and I need to kill the app. not sure why the `MessageDialog` does allow it?
CU-32qr2k9
> fix second open of broken project

- app/qml/misc/PositionProviderPage.qml
`deviceAddress` and `deviceName` were simply swapped, which resulted in undefined behaviour 🙂 
#32qr2h2
Fixes #2437
> Qt6 fixes/Fix swapped BT arguments

- .github/workflows/android.yml
Sign Android CI builds with our upload key. 
Note: We need to sign our builds prior to upload to Google Play otherwise they would be rejected. GP then signs generated APKs with their own distribution key.
4 new env vars must be defined + 2 cmake vars, see more here: https://doc-snapshots.qt.io/qt6-6.4/cmake-variable-qt-android-sign-aab.html
> Qt6 fixes/Enable Android signing

- app/qml/main.qml
Closing GPS data page change map state to view - this is wrong as GPS data page can be opened while recording, staking out, etc. 
In order to not propagate clicks on map canvas, I added the GPS panel to mapExtentOffset. 
Resolves #2438
> Add gps data page to map extent offset [fix stakeout freeze]

- app/qml/editor/inputrangeeditable.qml
- app/qml/editor/inputtextedit.qml
Issue was introduced by https://github.com/MerginMaps/input/commit/2ae5326e907283e14b1fc267575b54a05bfc7f79 
Overall, in order to make #1956 (and similar expression issues) working we needed to start calling `QgsField::convertCompatible` each time value in a field is changed. This brought us here, because for input `123.` `convertCompatible` returns `123` removing the trailing decimal separator. Each decimal separator thus got ignored.
The mentioned commit also introduced another issue - no FieldValidator validation from Mergin Maps, it is more described here https://github.com/MerginMaps/input/issues/2496 and needs a deeper fix.
Fixes #2474
> Fix decimal separator in forms

- app/qml/main.qml
Workaround for https://bugreports.qt.io/browse/QTBUG-108821 - Qt's bug with event distribution.
Made the `mainpanel` disabled when other windows occupy the space.
Re: QA Workspaces doc - Input - RC Full regresion with EE server (mergin related), else public - issue num. 6
> Disable main panel when it is not visible

- app/projectsmodel.cpp
- app/projectsmodel.h
- app/qml/ProjectPanel.qml
- app/test/testmerginapi.cpp
- core/merginapi.cpp
- core/merginapi.h
WE should not apply tag to list projects request if we are fetching projects from the specific workspace, as user might be not an author of the project.
Also re-enable use of order_params.
> Fix displaying of projects where user is not an author (e.g. was invited)

- app/appsettings.cpp
- app/appsettings.h
- app/qml/ProjectPanel.qml
- app/qml/components/PanelHeaderV2.qml
- core/merginapi.cpp
- core/merginapi.h
- core/merginuserinfo.cpp
- core/merginuserinfo.h
You can now switch workspace only from `account page`.
<table>
<tr>
<th>Previous</th>
<th>Now (see page title - ws)</th>
<th>With tooltip</th>
</tr>
<tr>
<td>
</td>
<td><img width="300" alt="Screenshot 2023-01-25 at 10 03 50" src="https://user-images.githubusercontent.com/22449698/214523405-2d5e579b-ca8f-4985-b26b-f3501cdb5af9.png">
</td>
<td><img width="300" alt="Screenshot 2023-01-25 at 10 03 45" src="https://user-images.githubusercontent.com/22449698/214523373-78bb1ebf-6521-4c23-9381-dceeca9cfc7a.png"></td>
</tr>
<tr>
</tr>
</table>
Also fixes a bug that `/workspace/<id>` was not called on profile page.
> Change switch workspace button and add toast to explain how to switch a workspace

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
For instance, displays meaningful error for the case when workspace name is too short.
> extract error message from the server reply containing automatic validation results

- core/merginsubscriptioninfo.cpp
Action required flag was still shown even when user logged out / switched accounts
> Reset action required flag when clearing subscription information

- app/qml/ManageInvitationsPage.qml
- app/qml/ProjectPanel.qml
- core/merginapi.cpp
We did not clearly show that a user has a pending invitation previously - now we show that there is a pending invitation each time the app is opened or the user logs in.
I needed to add call to `/v1/user/profile` right after server type is recognized to get list of invitations.
> Note: this implementation is not the best solution 🫣 We need a slight redesign to MerginAPI now with workspaces.
> Show invitations page on startup and  after user logs in

- app/map/inputcoordinatetransformer.cpp
- app/map/inputcoordinatetransformer.h
- app/map/inputmapcanvasmap.cpp
- app/map/inputmapcanvasmap.h
- app/map/inputmapsettings.cpp
- app/map/inputmapsettings.h
- app/map/inputmaptransform.cpp
- app/map/inputmaptransform.h
- app/qml/map/MapCanvas.qml
https://github.com/qgis/QGIS/pull/51347#issuecomment-1410060355
revert back (c) and attribution removed in https://github.com/MerginMaps/input/commit/bbc5cb845a528d264f579163e5623e89812e3711#diff-093e243bd0c5c7aac05b323490375ea112dfa0ed63f36828e4125b6db7192ed7
> clarify fork origin for qgsquick files

- app/qml/editor/inputrelation.qml
- app/qml/editor/inputrelationreference.qml
- app/relationfeaturesmodel.cpp
3 minor issues were fixed with help of @alexbruy : 
- `Repeater` (generator) component for an unknown reason does not detect model reset (it probably does not bother destroying delegates that are invisible immediately). This had consequences like "x more" button in a relations widget being visible even if there were no child features
- another parameter injection
- do not request child features if a parent feature id is not valid yet (when it is new: <0). QGIS API returns some random values then
Note: do not believe the commit message, it is an ugly lie (it does not fix the issue, #2548 will)
> Do not retrieve child features if parent feature is invalid

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/attributes/attributedata.cpp
- app/attributes/attributedata.h
- app/attributes/attributeformmodel.cpp
- app/attributes/attributeformmodel.h
- app/attributes/fieldvalidator.cpp
- app/invitationsmodel.cpp
- app/invitationsmodel.h
- app/invitationsproxymodel.cpp
- app/qml/ManageInvitationsPage.qml
- app/qml/editor/inputrangeeditable.qml
- app/qml/editor/inputtextedit.qml
- app/qml/form/FeatureForm.qml
- app/test/testattributecontroller.cpp
- app/test/testattributecontroller.h
- app/test/testformeditors.cpp
Bring back field validations by storing value entered by the user as a "raw" value and running validations against this value instead of using value converted to the compatible form for the field.
> Fix field validations

- app/attributes/attributecontroller.cpp
- app/attributes/attributeformmodel.cpp
- app/attributes/attributeformmodel.h
- app/qml/form/FeatureForm.qml
- app/test/testattributecontroller.cpp
Fixes enetering of minus sign in the range field, as per https://app.clickup.com/t/861mctcbe
> fix entering negative values in range field

- app/main.cpp
Fixes #2572 
Qt5 has HTTP/2 disabled by default, Qt6 has HTTP/2 enabled by default.
Users have reported that WMS server of Danish SDFI is not working anymore and it turns out it is due to a bug in Qt ([QTBUG-111417](https://bugreports.qt.io/browse/QTBUG-111417)) so let's avoid HTTP/2 for the time being.
> Disable HTTP/2 requests to work around a networking bug

- cmake/InstallStep.cmake
fix #2563
TLS plugin was missing in the installation on windows (and lnx and macos, but we do not package/ship there and in development you use lib from QT's installation)
> SSL error on windows

- app/purchasing.cpp
- app/purchasing.h
- app/qml/ProjectPanel.qml
Adds `?workspace=` query parameter to the subscriptions URL.
> add an active workspace id to the subscription url

- .github/workflows/android.yml
Renames Android artifacts so that one knows which version he/she downloads.
Having a common name without version becomes an issue if you download 20 different versions 🙂
> Rename android artifacts

- app/android/build.gradle
fixes https://github.com/MerginMaps/input/issues/2147
- for APK there is file: `build-input-android/app/android-build/build/outputs/native-debug-symbols/debug/native-debug-symbols.zip` which has `29M`
- AAB in `build-input-android/app/android-build/build/outputs/bundle/release/android-build-release.aab` has now `561M`
- AAB now contains files like
``` 
BUNDLE-METADATA/com.android.tools.build.debugsymbols/arm64-v8a$ find . | grep -i input
./libInput_arm64-v8a.so.dbg
``` 
limit is 300MB based on https://developer.android.com/studio/build/shrink-code#strip-native-libraries, but I hope for symbols file, so it should be fine?
I am not sure how to test it, symbols are now part of AAB, but probably for testing we need to somehow upload it to google play and test in there in some betatesting …
> generate debug symbols in AAB

- app/qml/MainPanel.qml
Use correct button name when checking for menu item visibility
> fix duplicated buttons in the project toolbar and menu (fix #2639)

- app/appsettings.cpp
- app/appsettings.h
- app/qml/main.qml
As workspaces migration completed we don't need it anymore.
> do not show what's new dialog and remove corresponding setting

- app/qml/ProjectPanel.qml
Do not set state for project panel explicitly as this prevents fetching/refreshing project list on the first load of the component.
> fix endless spinner in the project panel

- app/qml/map/MapCanvas.qml
PR applies the fix ( see https://github.com/MerginMaps/input/pull/2425 ) for map canvas clicks propagation to desktop builds.
-> fixes the issue that feature form closes itself randomly on Windows (and other desktop builds)
Fixes https://github.com/MerginMaps/input/issues/2556
> Apply Qt6 click propagation fix to desktop builds

- app/CMakeLists.txt
- app/position/tracking/iostrackingbackend.cpp
- app/position/tracking/iostrackingbackend.h
- app/position/tracking/iostrackingbackend.mm
- app/position/tracking/iostrackingbackendimpl.h
- app/position/tracking/iostrackingbackendimpl.mm
- app/position/tracking/positiontrackingmanager.cpp
- cmake/FindAppleFrameworks.cmake
- cmake_templates/iOSInfo.plist.in
Adds native `CLLocationManager`(https://developer.apple.com/documentation/corelocation/cllocationmanager?language=objc) implementation of position tracking backend. Used only on iOS devices (iPhones, iPads)
- supports background use
- notifies PositionTrackingManager about change in position. 
- uses `CLLocationManager distanceFilter` ( see https://developer.apple.com/documentation/corelocation/cllocationmanager/1423500-distancefilter?language=objc ) to update frequency of position updates
- does not use signal/slot connections as these are not delivered when app is minimised on iOS
> Add native iOS CLLocationManager tracking backend

- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
Qt 6.x already tries Locale without country in QTranslator::load() function
fix https://github.com/MerginMaps/input/issues/1417
see Qt6 logic in https://doc.qt.io/qt-6/qtranslator.html#load which is good.
tested on Android with EN (us) + FR (Canada) languages.
> remove Locale workaround

- app/projectwizard.cpp
- app/projectwizard.h
When creating a new project use Lutra's vector tiles instead of OSM XYZ layer. Vector tile layer loaded with the predefined style coming from the Lutra server.
> use Lutra's vector tile layer for background map 

- .github/workflows/code_style.yml
- INSTALL.md
- README.md
- gallery/CMakeLists.txt
- gallery/helper.cpp
- gallery/helper.h
- gallery/hotreload.cpp
- gallery/hotreload.h
- gallery/main.cpp
- scripts/format_all.bash
- scripts/format_cpp.bash
- scripts/format_qml.bash
fix https://github.com/MerginMaps/input/issues/1799
add CI check for formatting QML; QT's qmlformat removes empty lines from function bodies, so stick with qmlfmt tool for now. 
The `./scripts/format_qml` is not run intentionally , so the mergin between dev-2.3 and master is without conflicts for now.
> qmlfmt (formatting QML)

- .github/workflows/gallery.yml
- README.md
- gallery/CMakeLists.txt
- gallery/helper.cpp
Builds and Packages gallery app for windows, ubuntu and macos - creates package and uploads the tar.gz as artefact in gallery build - so it can be downloaded and directly started.
> Gallery App to CI

- app/android/src/uk/co/lutraconsulting/PositionTrackingService.java
- app/qml/main.qml
FUSED_PROVIDER is available only from SDK level 31 (Android 12). 
Let's use GPS_PROVIDER (available for all versions) in case the FUSED one is not available.
> Add support for position tracking for Android versions lower than 12

- .gitignore
- CMakeLists.txt
- app/CMakeLists.txt
- cmake_templates/build.gradle.in
Problem1: we do not have native debug symbols in AAB ; fix https://github.com/MerginMaps/input/issues/2147
Problem2: current APKs are now ~500MB, with old build it was ~90MB
**Explanation of the existing situation:**
New vckpg based android SDK is not compiled with `-g` as before (compare https://github.com/MerginMaps/input-sdk/blob/378d1bf861c940fb995ecdfaef9d22b0f4663992/vcpkg-overlay/triplets/arm64-android.cmake#L9 and  https://github.com/MerginMaps/input-sdk/blob/472f8daee008f33a9d08c8c0f51904b114f2306d/android/distribute.sh#L361)
As NDK's cmake toolchain adds it by default (see https://github.com/android/ndk/issues/243) we need to either compile with `-g0` as before for release, or RATHER `stripDebugDebugSymbols` from gradle. This would allow us to have debug symbols too, so it is …
> Reduce APK size, add debug symbols to AAB

- app/android/src/uk/co/lutraconsulting/PositionTrackingService.java
Moved the call to parent destructor to the last line and added a check if the `locationManager` is already NULL.
Though it is not clear why it would be NULL
https://app.clickup.com/t/862ke67ea
> Attempt to fix locationManager crash on Android

- app/attributes/attributecontroller.cpp
fix https://github.com/MerginMaps/input/issues/1905
fix https://github.com/MerginMaps/input/issues/2569 (no test case attached so hard to test)
fix CU-862ke6fkg
fix CU-862ke6jx6
For test suite - I think it is such an edge case that it may not be worth to add it to regular test suite (automatic or manual). Better to add validation to plugin https://github.com/MerginMaps/qgis-mergin-plugin/issues/298 for this case and caught it early
it is now possible to identify crashing feature `b39` from [lutraconsulting/issue_1905](https://public.cloudmergin.com/projects/lutraconsulting/issue_1905/tree)
and the diagnostics log shows the error
> fix crash with broken relations

- app/qml/form/PreviewPanel.qml
Fixed overflow in the preview panel of `fields` type.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/MerginMaps/input/assets/22449698/02ad01d5-7b12-49b6-8c5b-6a474149f105" width="300"/></td>
<td><img src="https://github.com/MerginMaps/input/assets/22449698/8dded5bc-1ea8-4833-8363-613c7e868801"  width="300"/></td>
</tr>
</table>
> Fix text overflow in preview panel

- app/ios/iosinterface.mm
- app/ios/iosviewdelegate.h
- app/ios/iosviewdelegate.mm
fix https://github.com/MerginMaps/input/issues/1540
fix CU-862keccax
it looks like if the user is really quick he can select another photo in the gallery when the first one is being processed in `imagePickerControllerDidFinishPickingMediaWithInfo` and unfortunately I do not see a way to hide that dialog fast enough. The view delegate is not reused between 2 select/capture actions so I added `BOOL` to block the second (another) selection while the first one is being proceeded.
> fix crash ios gallery

- app/inpututils.cpp
- app/inpututils.h
- app/qml/StakeoutPanel.qml
CU-861nbagwq
https://wishlist.merginmaps.com/p/yards-as-unit-for-stakeout
In case of distance in feet:
> Use distance unit from project's CRS for Stakeout panel

- app/androidutils.cpp
- app/androidutils.h
- cmake_templates/AndroidManifest.xml.in
Android introduced a new set of storage permission types. 
From API level 33 (Android version 13.0), we can not request `READ_EXTERNAL_STORAGE` to get photos from the gallery, but `READ_MEDIA_IMAGES` instead.
Fixes the issue that user can not pick image from gallery on android >13 (CU-862keem0n)
See https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE
> Use new storage permissions on Android >13

- app/qml/form/FeatureForm.qml
We disabled this gesture previously because of a QT bug, but it seems to be fixed now.
The issue was that previously `SwipeView` used to steal grab from `Slider`, see video in the related QT bug: https://bugreports.qt.io/browse/QTBUG-109124
Note: Even though the related QT bug is not closed, this seems to be working
https://github.com/MerginMaps/input/assets/22449698/77daf939-13ff-461a-bc4c-54e47676c120
Fixes #2473 
Related #2675
> Enable swipe gesture in forms to switch between tabs

- app/qml/CMakeLists.txt
- app/qml/NumberSpin.qml
- app/qml/SettingsPanel.qml
- app/qml/components/MainPanelButton.qml
- app/qml/components/MapFloatButton.qml
- app/qml/editor/AbstractEditor.qml
- app/qml/main.qml
- app/qml/map/MMMapCanvas.qml
- app/qml/map/MapCanvas.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingTools.qml
This PR is a complete rewrite of MapCanvas gesture handlers. 
Due to multiple issues in Qt (like QTBUG-108689, QTBUG-108821 and more..), `TapHandlers`, `DragHandlers` and `PinchHandlers` were a pain to use and maintain.
- they were fighting who should get an exclusive grab (often resulting in no one and frozen UI)
- taps were propagated to parent scopes even though they should not
The new implementation is minimal and contains only `PinchArea` with nested `MouseArea`. Drags and double-clicks are implemented on our own now. 
**Important: we no longer support tap&drag gesture to zoom in/out the map**. 
If needed, it will not be hard to add it to the current implementation though 
There are still some bits and pieces needed to get rid of the propagation issues (will be a part of this PR):
We …
> Revamp mapcanvas gesture handlers & fix propagation issues

- app/qml/components/DateTimePicker.qml
- app/qml/editor/inputdatetime.qml
CU-862kf11u9
1/ fix #1671 wrong calendar day with 
- Run app (deskop) with ENV: TZ=America/Mexico_City
- Left fixed app ; Right - current app
- Reason: https://bugreports.qt.io/browse/QTBUG-72208 `model.date` returns wrong date in different timezones
https://github.com/MerginMaps/input/assets/804608/9c531d57-eac2-4632-885c-392cac4995de
2/ fix #2827 wrong calendar pick with text field 
https://github.com/MerginMaps/input/assets/804608/2919b7cb-ff75-4ba5-9df4-6f271767315b
Testing project @jozef-budac 
- (public): https://app.merginmaps.com/projects/peter.petrik/test-date-picker 
- for testing 1/ you need to go to timezone with at least -6GTM (e.g. Mexico_City!)
> calendar widget fixes

- app/androidutils.cpp
- app/androidutils.h
- app/position/tracking/androidtrackingbackend.cpp
- cmake_templates/AndroidManifest.xml.in
Android system notification for tracking won't be visible on Android 13+ unless we ask for specific permission (`POST_NOTIFICATIONS`).
This permission is not needed to start the service, so it is up to a user if they want to see the tracking in the notifications tray or not.
See https://developer.android.com/develop/ui/views/notifications/notification-permission
Resolves #2833
> Ask for notification permission

- app/qml/editor/inputdatetime.qml
CU-862kfd5yu
follow up of https://github.com/MerginMaps/input/pull/2829
problems with original implementation
1/ We need to patch date coming from C++ also for calendar, not just for `formatText`
2/ We need to NOT patch date after it is already patched once
3/ We need to correctly transform (string) date in all occurrences (also for now() action, not just for calendar)
> fix datetime picker 2

- app/map/inputmapcanvasmap.cpp
> revert symbol size

- app/qml/map/Highlight.qml
CU-861n417r8
Highlighting geometries with lots of vertices was slow because a shape path with many PathMove/PathLine was apparently doing loads of internal updates when constructing it. Qt introduced PathPolyline in a latter qt5 release (5.14) which makes parsing of dynamically constructed complex paths much more efficient.
On desktop build: a polygon with 15K vertices was taking 5-10 seconds to highlight, now it is less than a second.
Fixes #833
> Highlight: use PathPolyline instead of PathMove/PathLine

- app/relationfeaturesmodel.cpp
fix #2058
fix https://github.com/MerginMaps/input/issues/2586
project `support/BugZapper2058` or any project where photo photo field is not set as layer display field (usually when user does does not have photo widget as second in the form)
> fix photo in relation preview 

- app/qml/map/MMMapCanvas.qml
**Update, ready for review**
These things are fixed/added:
- The formula for calculating vector distance was missing `+` 🤦🏻‍♂️ 😃  , resulting in wrong distances calculated when you dragged the map vertically 
- Added distance threshold for double clicks - now the second click must be within a _threshold_ from the first point.
- Added time elapsed threshold for detecting drag movement - sometimes, if you move a map just by a tiny bit to fit the point, you might not exceed the distance threshold to detect the movement as a drag. It would be detected as a simple tap. This caused unexpected actions while recording new/updating existing geometries. Now to detect the drag gesture we use a combination of a distance threshold and a time threshold (_"how long the tap lasted"_) 
- Thresholds are …
> Fix mapcanvas UX issues

- app/projectwizard.cpp
fix #1613 
Replace deprecated QGIS API writeAsVectorFormatV2 with writeAsVectorFormatV3 (it has different position for error code in  arguments)
also removed artificial call to `QgsVectorFileWriter::create`, it should not be used at all when `writeAsVectorFormatV3` is used. This also removes bunch of warnings like `ERROR 1: sqlite3_exec ...` visible on desktop from the initial implementation https://github.com/MerginMaps/input/pull/1103
https://github.com/qgis/QGIS/blob/1f1e8b5de70a8a1c1e6a639f08fd15b9aeea6f8b/src/core/qgsvectorfilewriter.h#L663
> remove deprecated QGIS API for writeAsVectorFormatV2

- app/android/src/uk/co/lutraconsulting/PositionTrackingService.java
🫢 Java's `String::format` uses a default locale when no locale is provided to it. It means that for US/UK locale it used `.` as the decimal separator. However, for example for `SK`, it used `,` -> Qt was unable to parse double with such decimal separator aaaand 💥
We will use the common `Locale.US` for writing doubles. A workaround until this bug is released is to change the system language to English 🇬🇧🇺🇸 ... or some other place where they use `.` as decimal separator
Resolves #2781 
See https://developer.android.com/reference/java/util/Locale#default_locale:~:text=Be%20wary%20of%20the%20default%20locale
I checked other occurrences of `String::format` but they look alright.
> Fix position tracking (0,0) coordinates on Android - fix locale when writing decimals

- app/qml/layers/FeaturesListPageV2.qml
The problem was when the replace function was called from a number and not from a string
Fixes: #2871
> Fixed feature list - used replace function always for a string

- core/merginapi.cpp
- core/merginapi.h
- core/merginprojectmetadata.cpp
- core/merginprojectmetadata.h
Fixes #2808
- JSON parsing: use toInteger() instead of toInt() for big numbers (returns qint64 instead of int)
- store sizes and file offsets as qint64 instead of int
> Fix download of files >= 2GB

- app/inputhelp.cpp
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
fix https://github.com/MerginMaps/mobile/issues/2258
docs: https://github.com/MerginMaps/docs/pull/387
qgis: https://docs.qgis.org/3.4/en/docs/user_manual/managing_data_source/opening_data.html#postgresql-service-connection-file
Tested on desktop: peter.petrik/[Pgtest](https://app.merginmaps.com/projects/peter.petrik/Pgtest)
(note that pg_service.conf is part of the project, but in production it should not be)
```
// Start container
docker run --name some-postgis -p 5432:5432 -e POSTGRES_DB=gisdb -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis
// Test in QGIS
export PGSERVICEFILE=/Users/peter/Projects/mergin/data/Pgtest/pg_service.conf
open /Applications/QGIS.app/
// Test in app (desktop)
cp /Users/peter/Projects/mergin/data/Pgtest/pg_service.conf …
```
> add support for pg_service.conf file

- app/synchronizationmanager.cpp
- app/test/inputtests.cpp
- app/test/testutils.h
- app/test/testvariablesmanager.cpp
- app/test/testvariablesmanager.h
- app/variablesmanager.cpp
- app/variablesmanager.h
- core/merginapi.cpp
- core/merginapi.h
add `mergin_user_email` as new global variable
fix https://github.com/MerginMaps/input/issues/2905
> add mergin_user_email as new global variable

- app/position/providers/bluetoothpositionprovider.cpp
- app/qml/main.qml
- app/qml/misc/AddPositionProviderPage.qml
We now use Qt API for location and BT permissions.
Advantages:
- one codebase
- works fine ✔️ 
- we ask for permissions in context, not at the app startup
Location permission is requested when:
- project is opened
- user clicks on the GPS button
- user holds the GPS button
BT permission is requested when:
- opening "add BT gps receiver" page
- when device can't connect to saved GPS receiver because of missing BT permission
Camera and gallery permissions stay untouched and work for both platforms.
Fixes #1101 (indirectly, upgrade of Qt 6.6 did the job actually)
Fixes #2433
Fixes #1057
> Fix bluetooth and location permissions for Qt 6.6.0

- app/inpututils.cpp
Fixes #2910 
In the following code:
```cpp
QgsPoint point;
point.setX(1);
point.setY(2);
point.setZ(3);
point.setM(4);
```
`Z` and `M` values will be null. This happens on the version of QGIS that we use atm.
Not sure if this is a QGIS bug or feature though.
Needed to explicitly mention the WkbType.
Checked other places in the code, and they seem to be ok. Should be tested though if we record Z values atm
> Initialize QgsPoint with the correct WkbType to store Z and M values

- app/qml/inputs/MMButtonInputEditor.qml
- app/qml/inputs/MMPasswordEditor.qml
- gallery/qml.qrc
- gallery/qml/pages/EditorsPage.qml
MMButtonInputEditor {
title: "MMButtonInputEditor"
placeholderText: "Write something"
text: "Text to copy"
buttonText: "Copy"
buttonEnabled: text.length > 0
onButtonClicked: console.log("Copy pressed")
}
> Added Input with button

- app/icons/Minus.svg
- app/icons/Plus.svg
- app/icons/icons.qrc
- app/mmstyle.h
- app/qml/inputs/MMNumberEditor.qml
- gallery/qml.qrc
- gallery/qml/pages/EditorsPage.qml
- gallery/qml/pages/IconsPage.qml
MMNumberEditor {
title: "MMNumberEditor"
number: 124
}
> Added new integer input editor with buttons + and -

- app/qml/InputStyle.qml
- app/qml/map/Highlight.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingTools.qml
- app/qml/map/StakeoutTools.qml
- Updated `Highlight.qml` component with the new graphics
- Replaced use of `InputStyle` in the highlight
| Header | Header | Header |
|--------|--------|--------|
|<img width="300" alt="Screenshot 2024-01-22 at 15 20 09" src="https://github.com/MerginMaps/mobile/assets/22449698/31f66c78-3324-4bea-8e48-0c300acb1571"> | <img width="300" alt="Screenshot 2024-01-22 at 15 19 50" src="https://github.com/MerginMaps/mobile/assets/22449698/1a39f952-d09d-412a-b184-4bdf38ead110"> |<img width="300" alt="Screenshot 2024-01-22 at 15 19 48" src="https://github.com/MerginMaps/mobile/assets/22449698/058a2cdc-352c-4a74-9751-8be95c6516cf"> |
> Redesign highlight.qml

- gallery/main.cpp
Must be done in order to make `QSettings` working properly in the gallery app (already there for our app)
> Initialize QSettings in the gallery

- app/qml/components/MMSelectableToolbarButton.qml
- app/qml/components/MMToolbar.qml
- app/qml/components/MMToolbarButton.qml
- app/qml/components/MMToolbarMenuButton.qml
- gallery/qml/pages/ToolbarPage.qml
- buttons/icons are centered
- as per new design emphasises button is same size as others
> fix gallery with new emph toolbar button

- app/test/testmerginapi.cpp
Sleep for a second to allow `::lastModified()` datetime of copied file to change, otherwise its checksum is fetched from the cache instead of getting calculated.
Care should be taken whenever we read the checksum cache too shortly after writing to it (probably only applies to tests).
> Fix testMerginApi

- app/qml/misc/MMGpsDataDrawer.qml
- "Manage GPS receivers" button always visible.
- Scrolling fixed in mobile. 
- Margins fixed.
> Fix of the MMGpsDataDrawer

- app/qml/onboarding/MMHowYouFoundUs.qml
- app/qml/onboarding/MMOnboardingController.qml
- core/merginapi.cpp
Send post-registration data when onboarding is completed (endpoint `/v1/post-register` is not yet available in test.dev server)
Success/failure is only logged and not shown to the user. He only cares that his workspace was created, so always show this.
The back button was also removed from `MMHowYouFoundUs` so that users can't skip _how you found us_ and _which industry_ questions.
> Send post-registration data when onboarding is completed

- app/featuresmodel.cpp
- app/featuresmodel.h
- app/qml/main.qml
- app/qml/map/MMMapCanvas.qml
- app/qml/map/MapWrapper.qml
Initial implementation of selection of overlapping features.
Use _tap and hold_ to bring up a list of features if at least one is under the tap point.
Pick from the list to open the feature preview drawer.
The current item delegate is too simple for this use case, we should use an item delegate that displays more info about the features (layer, fid?, icon)
> Multi-feature selection initial implementation

- app/qml/onboarding/MMHowYouFoundUs.qml
- app/qml/onboarding/MMWhichIndustry.qml
We were passing the translated string to the endpoint.
Keys are checked to match the ones also used in the web front end.
> pass keys instead of values to post-register endpoint

- gallery/qml/pages/DrawerPage.qml
- gallery/qml/pages/ImagesPage.qml
- To fit more buttons in the gallery, it was necessary to place the main column of Drawers Page inside a Scroll View.
- Sync Failed and No Permissions dialogs images added to gallery.
> Drawers page column in scroll view

- app/mmstyle.h
- app/qml/components/MMPageHeader.qml
Fixed the back button on page header that was not aligned properly with safeArea
**PR also fixes the same thing for the right item in the page header.** The usage of the `MMPageHeader` changes a little bit, instead of setting `rightMarginShift`, define your items via `rightItemContent` property, like this:
```qml
MMPageHeader {
...
rightItemContent: MMProgressBar {
width: 60 * __dp
height: 4 * __dp
anchors.verticalCenter: parent.verticalCenter
color: __style.grassColor
progressColor: __style.forestColor
position: 2/3
}
}
```
Header will take the `width` of the rightItemContent automatically, so you do not need to set it up manually anymore (via `rightMarginShift`)
> Fix header back button top margin

- gallery/CMakeLists.txt
- gallery/hotreload.cpp
Should work everywhere now.
Also make sure to always overwrite the sync script on start (because why not) to make sure we're using up-to-date paths.
> Fix hot reload paths

- app/mmstyle.h
- app/qml/components/MMToolbarLongButton.qml
- gallery/qml/pages/MapPage.qml
fix margin of long button in toolbar  (as per figma)
make map buttons 50 (as per figma)
> WIP: Smallfixes5

- app/test/testcoreutils.cpp
- core/coreutils.cpp
- core/coreutils.h
- core/merginuserinfo.cpp
Changes to the nameAbbr method in ```coreutils.cpp```:
"Barry Allen Joe", "[bjallen@gmail.com]"
"Barry Allen", "[bjallen@gmail.com]
"Barry", "[bjallen@gmail.com]
Other cases:
"", [] -> ""
"Barry", [] -> BA
"B", [] -> B
"", [bjallen@gmail.com] -> BJ
> Core utils nameAbbr method changes

- app/qml/components/MMToolbar.qml
- app/qml/components/MMToolbarButton.qml
- app/qml/main.qml
Position tracking button in ```MMToolbar.qml``` visibility adjustment with new property in ```MMToolbarButton.qml```:
- ```visibilityMode```, which manages the overall visibility of a toolbar button. If set to ```false```, the button will not be displayed on the toolbar under any circumstances. The default value is ```true```, ensuring standard behavior for the button.
```visibilityMode true``` for Position Tracking button
```visibilityMode false```  for Position Tracking button
> Position tracking button visibility adjustment

- app/qml/project/MMProjectController.qml
The storageFill value for ```MMAccountPage``` now has two decimal places.
> Rounding the storage fill calculation

- app/qml/components/MMToolbar.qml
- app/qml/map/components/MMCrosshair.qml
`MMLongButton` in toolbar was not visible because it was filtered out in the `MMToolbar::setupBottomBar` function
> Fix recording toolbar and errors

- app/featuresmodel.cpp
- app/featuresmodel.h
- app/qml/components/MMListDrawer.qml
- app/qml/components/MMListDrawerItem.qml
- app/qml/main.qml
Add an icon according to layer's geometry type, add layer name as a secondary _description_ text.
Also fixes scrolling in MMListDrawer, it would always snap-return to top of list.
issues:
Spacing between primary and secondary text probably needs some adjusting to match the design docs.
List items overlap the Header when scrolled, as seen on the screenshot above (was the case before this pr too)
> Add layer name and layer geometry icon to multi-identify results

- app/qml/project/components/MMProjectDelegate.qml
From "Synchronising..." to "Please don't close the app."
> Adjustment of the text displayed during synchronization

- app/qml/components/MMMorePhoto.qml
- app/qml/components/MMPhoto.qml
- app/qml/components/MMPhotoPreview.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
Bug fix: ISS-102
Fixed: Photos attached from gallery / captured are rotated in the form
The issue was occurring on iOS only.
Similar bug also fixed: image rotation in MMPhotoPreview:
| Before | After |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/9980d4cc-9a9b-42fe-8fe5-7b1c0845ebdf" width="200">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/ff6dd0b4-d689-437e-aeb3-1919dcc2d63b" width="200"> |
> Fixed rotation of photos in the MMFormPhotoViewer

- app/qml/dialogs/MMFormDeleteFeatureDialog.qml
ISS-101
Changing  from  ```__style.positiveMMSymbolImage``` to ```__style.negativeMMSymbolImage```
> Changing image of the MMFormDeleteFeatureDialog.qml

- app/qml/account/MMAccountController.qml
- app/qml/account/MMHowYouFoundUsPage.qml
- app/qml/account/MMWhichIndustryPage.qml
| MMHowYouFoundUsPage |
|----------------|
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/3767a9e7-9040-4944-871e-560acda87973" width="300"> <img src="https://github.com/MerginMaps/mobile/assets/155513369/35060bfa-0e9f-4194-b2be-0ca916af8fbb" width="300"> |
| MMWhichIndustryPage |
|----------------|
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/b3c6e9b3-ba16-4349-9724-35d43d58ec61" width="300"> <img src="https://github.com/MerginMaps/mobile/assets/155513369/b2746254-ef85-4a5a-a049-3dbca31a7e42" width="300"> |
Obs: Option "other" always last.
> Randomizing order of "where did you hear about us" and "industry" options

- app/android/src/uk/co/lutraconsulting/InputActivity.java
Adjusting the ```getSafeArea``` and ```setCustomStatusAndNavBar``` methods in ```InputActivity.java``` to accommodate Android versions 10 and earlier.
- <img src="https://github.com/MerginMaps/mobile/assets/155513369/9a261b09-2853-4c4b-9f0f-90baf7f14536" width="300">
- <img src="https://github.com/MerginMaps/mobile/assets/155513369/9c36467d-5611-4a6d-aa90-e308fe3b862a" width="300">
> Handle Android versions 10 and below

- app/qml/components/MMToolbar.qml
if screen size is >= 240px 4 buttons will be shown now (I hope there are no smaller mobile phones :) )
https://github.com/MerginMaps/mobile/assets/804608/f89b9215-c871-4a3a-a763-b06201d69067
> always try to show 4 buttons in toolbar

- app/mmstyle.h
- app/qml/CMakeLists.txt
- app/qml/components/MMCodeScanner.qml
- app/qml/components/MMDrawerDialog.qml
- app/qml/dialogs/MMDiscardGeometryChangesDialog.qml
- app/qml/dialogs/MMDownloadProjectDialog.qml
- app/qml/dialogs/MMFormDeleteFeatureDialog.qml
- app/qml/dialogs/MMFormEditFailedDialog.qml
- app/qml/dialogs/MMFormSaveChangesDialog.qml
- app/qml/dialogs/MMMigrateToMerginDialog.qml
- app/qml/dialogs/MMMissingAuthDialog.qml
- app/qml/dialogs/MMNoPermissionsDialog.qml
- app/qml/dialogs/MMOutOfDateCustomServerDialog.qml
- app/qml/dialogs/MMPositionTrackingDialog.qml
- app/qml/dialogs/MMProjErrorDialog.qml
- app/qml/dialogs/MMProjectLimitDialog.qml
- app/qml/dialogs/MMProjectLoadErrorDialog.qml
- app/qml/dialogs/MMProviderRemoveReceiverDialog.qml
- app/qml/dialogs/MMRemovePhotoDialog.qml
- app/qml/dialogs/MMRemoveProjectDialog.qml
- app/qml/dialogs/MMSplittingFailedDialog.qml
- app/qml/dialogs/MMStorageLimitDialog.qml
- app/qml/dialogs/MMStreamingModeDialog.qml
- app/qml/dialogs/MMSyncFailedDialog.qml
- app/qml/dialogs/components/MMDialogAdditionalText.qml
- app/qml/main.qml
- app/qml/settings/components/MMSettingsInput.qml
- gallery/qml.qrc
- gallery/qml/pages/DrawerPage.qml
`MMDrawerDialog` now inherits `MMDrawer`, it is scrollable and adjusts its height based on the content height.
I replaced `specialComponent` done via `Loader` with approach that we use in other places (`property alias xyz: xyzm.children`), the new property is called `additionalContent`. This way I extracted the "boundedMessage" to a standalone component that can be used when needed.
With the `additionalContent` it can look like this:
but you can inject any other item to it to get something custom, like:
> Fix layout of dialog drawers

- core/merginapi.cpp
- core/merginuserauth.cpp
- core/merginuserauth.h
Fixes #3194 / ISS-142
This was caused by the fact we were trying to get user info even when login failed, which in turn triggered another login request, getting into an endless loop. Could be triggered by not having network, or by using a wrong server URL.
> Fix endless login loop

- app/scalebarkit.cpp
I was getting black screen upon app start on linux. It was quite horrible to debug, but in the end this is how it goes:
- at some point during init, when ScaleBarKit::updateScaleBar() tries to figure out good scale bar width, the InputUtils::screenUnitsToMeters() function returns NaN because we're trying to do ellipsoid calculations with bad coordinates
- NaN gets propagated and the scale bar gets width = -2147483600
- ShaderEffectSource used for the blur box gets sourceRect set to -2147483600 and that gets the code stuck somewhere in Quick Scene Graph code forever
Before:
After:
> Fix freeze on start

- app/qml/gps/MMStakeoutDrawer.qml
Make Stake out drawer non-modal so the user may interact with the map canvas.
Fixes iss-136
> Enable map interaction when staking-out

- app/qml/gps/MMPositionProviderPage.qml
> small tweaks to GPS panel

- app/qml/gps/MMStakeoutDrawer.qml
- app/qml/main.qml
- app/qml/map/MMMapCanvas.qml
- app/qml/map/MMMapController.qml
- app/qml/map/MMStakeoutTools.qml
Fixes #3257 
Also fixes:
- Stakeout line is now rendered below cursor
- Jump-to is used when in `view` state and `centerToGPS` is enabled 
- ^ Jump-to is triggered when moving outside the central 20% of the screen
- Jump-to animation is now straight and not split in two axes
- In stakeout mode the gps accuracy and center to gps buttons are visible
> rework center to gps

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/win.yml
fix: https://github.com/MerginMaps/mobile/issues/3258
update SDK with new libpq (see https://github.com/MerginMaps/mobile-sdk/pull/109)
TODO: fix iOS with output of https://github.com/MerginMaps/mobile-sdk/actions/runs/8570821847/job/23489629404
> WIP: update sdk (fix postgis crashes)

- app/position/providers/internalpositionprovider.cpp
Ignore `QGeoPositionInfoSource::UpdateTimeoutError` when writing error logs. It consumed the entire log file.
Fixes #3029
> Do not print UpdateTimeoutError to diagnostic logs

- app/qml/project/MMProjectWizardPage.qml
Fixes #3209
- `root.rowHeight` and `root.rowheight` were undefined, so footer was incorrectly sized
- height of list view was not correctly calculated
- page had unnecessary margin above the toolbar
https://github.com/MerginMaps/mobile/assets/193367/130b1c6f-b439-4fe8-9f02-453f35fcc77b
> Fix "Add field" button visibility in project wizard

- app/inpututils.cpp
- app/inpututils.h
- app/qml/form/MMFormController.qml
- app/qml/form/MMFormStackController.qml
- app/qml/main.qml
- app/qml/map/MMMapCanvas.qml
- app/qml/map/MMMapController.qml
Fixes #3260
- Preview panel height is taken into account when centering to the identified feature
- Animation is used while centering
- If _follow gps_ was enabled, map pans back to gps position after closing the preview panel
> fix centering when preview panel is opened

- app/CMakeLists.txt
- app/main.cpp
- gallery/CMakeLists.txt
- gallery/main.cpp
Apparently you only need to define QT_QML_DEBUG for qml debugging to work.
Fixes #3303
> define QT_QML_DEBUG instead of manually instantiating debugging helper

- app/qml/project/components/MMProjectDelegate.qml
Fixes #3206
Do not show download button while download is in progress... Debug build would crash on assert anyway.
This fixes the problem (1) and it should not be possible to get problems (2) and (3) anymore
https://github.com/MerginMaps/mobile/assets/193367/cc6042ec-732e-46e4-92db-1c4a8087831e
> Fix download button

- app/qml/components/MMPhotoPreview.qml
- app/qml/dialogs/MMRemovePhotoDialog.qml
- app/qml/form/editors/MMFormPhotoEditor.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
Fixes multiple issues with the photo editor:
- show trash icon even when the image is not available (previously it showed the icon only when the Image was loaded successfully)
- update the text of the `MMRemovePhotoDialog` to better represent what it does
- photos were not removed from the project even if the `Delete photo` was selected. The issue was that the callback function `onFormSaved` was placed in the private `QtObject` and thus could not be called from the form
- we used to call `root.editorValueChanged( "", false )` where the boolean value represents if the new value is null. We were passing `false` even when removing the photo. Changed it to `true`.
> Fix photo editor

- app/mmstyle.h
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/projectsproxymodel.cpp
- app/projectsproxymodel.h
- app/qml/project/MMProjectHomeTab.qml
- app/qml/project/MMProjectList.qml
- app/qml/project/MMProjectServerTab.qml
- app/qml/project/components/MMProjectDelegate.qml
- app/test/testmodels.cpp
- app/test/testmodels.h
Fixes #3214
Change the way the active project is displayed on top of the list in Home tab into a less hacky one.
Now the ProjectsModel gets a `activeProjectId` property which _if_ set, then one can use the new `Roles::ProjectIsActiveProject` role on the model's contents.
We then split the projects list into two sections based on this new role.
`Roles::ProjectIsActiveProject` may be a bit misleading, as it might not return true on the active project, rather on the one passed into `ProjectsModel::activeProjectId`
> Rework the project list in home tab

- app/qml/main.qml
Call to non existing `syncInProgressAnimation.stop()` was breaking the sync button logic
Fixes #3216
> remove syncInProgressAnimation leftover

- app/projectwizard.cpp
When creating a new project using a name that already exists in the local projects, then the projectDir is modified and a ` (1)` is appended / incremented.
However the notification was still using the project name, which is _not displayed_ in the list of projects.
Now the notification says _Project myProject (1) created_
> Use actual project folder in the created project notification

- core/merginapi.cpp
- core/merginapi.h
Partially fixes #3217 : 1. which was happening on all operations that can be cancelled
2. and 3. are not fixed and are also present in the currently released version
> Don't emit networkErrorOccurred when cancelling operations

- app/qml/project/MMProjectController.qml
- core/merginuserauth.h
1. incorrect "no workspace detected" message
2. endless busy wait on the home tab (unable to switch projects)
3. endless loop of requesting projects in the second tab
The hasAuthData() function is confusing - one may think it returns whether we are logged in, but in fact it only tells whether username+password have been set.
Before:
https://github.com/MerginMaps/mobile/assets/193367/3976e964-ff10-4ae4-89fc-a8c946cdfac6
After:
https://github.com/MerginMaps/mobile/assets/193367/2e65f78f-3244-41f9-a4a1-bef432ea1618
> Fix offline issues in Projects page with no/expired token

- app/qml/components/private/MMBaseSingleLineInput.qml
Let's bind `enabled` property of left/right content mouse area to the `editState === "enabled"` so that we do not need to bind it individually in each input/editor
> Bind left/right content mouse areas to enabled state by default

- app/qml/components/MMSwitch.qml
- app/qml/components/private/MMBaseSingleLineInput.qml
- app/qml/form/editors/MMFormNumberEditor.qml
- app/qml/form/editors/MMFormSwitchEditor.qml
- app/qml/inputs/MMSwitchInput.qml
- app/qml/inputs/MMTextInput.qml
- app/qml/layers/MMLayerDetailPage.qml
Rework of Switch.
The Switch is not visible in Form unless `&& rightContentGroup.children[0].visible` check is removed in `rightContentGroupContainer`.
> MMSwitchInput, MMSwitchFormEditor

- app/mmstyle.h
- app/qml/CMakeLists.txt
- app/qml/form/components/photo/MMPhotoAttachment.qml
- app/qml/form/components/photo/MMPhotoPreview.qml
- app/qml/form/editors/MMFormPhotoEditor.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
- gallery/qml.qrc
- gallery/qml/pages/EditorsPage.qml
- gallery/qml/pages/PhotosPage.qml
I moved two photo editor-related files from `./components` to `./form/components/photo`.
There are a bunch of things that could be changed but I think it is fine for now :)
> Rework MMFormPhotoEditor

- app/qml/form/editors/MMFormTextMultilineEditor.qml
Fixes warning in the console like:
```
QML Rectangle: The current style does not support customization of this control (property: "background" item: QQuickRectangle(0x6000035e42a0, parent=0x0, geometry=0,0 0x0)). Please customize a non-native style (such as Basic, Fusion, Material, etc). For more information, see: https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#customization-reference
```
We use the same fix in other places too.
> Fix console warnings with import

- app/qml/form/editors/MMFormRelationEditor.qml
Also adds an additional mouse area - when a user clicks on the white background, it opens the features list. It was behaving like this even before, but we had forgotten about that in the new implementation.
> Rework MMFromRelationEditor

- app/qml/form/editors/MMFormRelationReferenceEditor.qml
We were missing several properties to capture, it was likely not working before
> Rework MMRelationReferenceEditor

- app/qml/components/private/MMBaseInput.qml
- app/qml/components/private/MMBaseSingleLineInput.qml
- app/qml/form/components/photo/MMPhotoPreview.qml
- app/qml/form/editors/MMFormCalendarEditor.qml
- app/qml/inputs/MMComboboxInput.qml
- app/qml/map/MMMapController.qml
- app/qml/project/components/MMProjectWizardDelegate.qml
- app/qml/settings/components/MMSettingsInput.qml
> Fixes after editors rework 2

- app/appsettings.cpp
- app/appsettings.h
- app/inputhelp.cpp
- app/main.cpp
- app/test/testposition.cpp
- core/coreutils.cpp
- core/coreutils.h
- core/merginapi.cpp
Add GUID to each HTTP request and also show it in the diagnosis log. GUID is generated on first run or the app.
We use `X-Device-Id` with uuid as custom header
> send uuid in HTTP request

- app/qml/form/editors/MMFormTextMultilineEditor.qml
Binding to the `TextArea::text` property led to a loop. `_fieldValueIsNull` was still false when `_fieldValue` was changed and it blocked the new string to appear. 
The binding is now the same as it was previously.
Fixes #3361
> Fix multiline editor

- .github/workflows/ios.yml
Changes version numbers from `24.04.xyz` to `24.4.xyz`. This makes it easier to search for versions in AppStoreConnect as Apple considers the numbers to be integers.
> Remove leading zero in month number for iOS versions

- app/qml/dialogs/MMMissingAuthDialog.qml
- app/qml/dialogs/MMNoPermissionsDialog.qml
- app/qml/dialogs/MMRemoveProjectDialog.qml
- app/qml/dialogs/MMSyncFailedDialog.qml
- app/qml/main.qml
- app/qml/project/MMProjectList.qml
- app/qml/project/components/MMProjectDelegate.qml
- app/synchronizationmanager.h
> use UK english

- app/qml/components/MMDrawerHeader.qml
Following https://github.com/MerginMaps/mobile/issues/3324, the fix now ensures that the closeBtn is no longer within the safe area while in landscape mode.
> Fixing issue where the close button is rendered within the safe area in landscape mode

- app/qml/main.qml
When syncing from the Home/Projects page, the project does not open automatically after the synchronization is completed.
Fixes #3358
> Unabling project reloading after project sync in home/projects page

- app/qml/components/MMListDrawer.qml
- app/qml/components/MMListMultiselectDrawer.qml
MMListDrawer and MMListMultiselectDrawer closure via dragging is now disabled when the listViewContent's interactive property is set to true (contentHeight > height). This change impacts drawers like MMMapThemeDrawer and featurePairSelection (features list drawer).
Fixes #3412
> Conditioning closing through dragging in MMListDrawer and MMListMultiselectDrawer

- app/qml/form/editors/MMFormPhotoEditor.qml
| Indication of the missing photo |
|--------|
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/b009bc55-d63d-4b34-8ece-13361fd52566" width="300">|
Partially fixes #3405
> Handling a missing photo in photo field

- app/qml/main.qml
https://github.com/MerginMaps/mobile/pull/3401 was a good effort for fixing https://github.com/MerginMaps/mobile/issues/3358, however the correct solution was not to remove the code, but move it from `onProjectReloaded` to `onLoadingFinished` -> this signal is not emitted when doing reload of active project.
Resolves https://github.com/MerginMaps/mobile/issues/3358
Resolves https://github.com/MerginMaps/mobile/issues/3422
> Fix project opening

- app/qml/CMakeLists.txt
- app/qml/account/MMHowYouFoundUsPage.qml
- app/qml/components/MMListDrawer.qml
- app/qml/components/MMListMultiselectDrawer.qml
- app/qml/components/MMListView.qml
- app/qml/components/MMToolbar.qml
- app/qml/form/MMFormPage.qml
- app/qml/form/MMPreviewDrawer.qml
- app/qml/form/components/MMFeaturesListPageDrawer.qml
- app/qml/form/editors/MMFormGalleryEditor.qml
- app/qml/gps/MMPositionProviderPage.qml
- app/qml/layers/MMFeaturesListPage.qml
- app/qml/layers/MMLayersList.qml
- app/qml/project/MMProjectIssuesPage.qml
- app/qml/project/MMProjectList.qml
- app/qml/project/MMProjectStatusPage.qml
- app/qml/project/MMProjectWizardPage.qml
- app/qml/settings/MMChangelogPage.qml
(hot)fixes  #3417 and fixes #3428 
We are disabling cache in ListViews, it proves to fix the scrolling issue. We will need to dig deeper then to understand what is actually happening + report to Qt.
> Disable cache for list views

- app/main.cpp
Set QT_ANDROID_DISABLE_ACCESSIBILITY environment variable to disable accessibility features and prevent ANRs.
Fixes #3431
> Fixing QtNativeAccessibility related ANRs

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos_arm64.yml
- .github/workflows/win.yml
- CMakeLists.txt
- README.md
- app/CMakeLists.txt
- cmake/FindZstd.cmake
arm64 macOS, zstd support (@saberraz @roelofvandijkO )
> arm64 macOS, zstd support

- app/android/res/xml/file_paths.xml
- app/android/src/uk/co/lutraconsulting/InputActivity.java
- app/androidutils.cpp
- app/androidutils.h
- app/inpututils.cpp
- app/inpututils.h
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/ios/iosutils.mm
- app/qml/form/editors/MMFormRichTextViewer.qml
- app/qml/form/editors/MMFormTextMultilineEditor.qml
- cmake_templates/AndroidManifest.xml.in
This feature can be used to open PDF files using the user’s system default application viewer, and can open formats such as links, PDFs, Docx, etc.
1. In a form that allows multiline entries, add text to the "Form Layout" widgets. This can be done in the "Default Value" section, or within the "HtmlWidget" field.
2. To embed a PDF file in the project, use the following HTML format:
-    For the "Default Value" section, enter:
-    **`'<a href="project://dummy.pdf">Open File</a>' `** (include the HTML code inside single quotes).
-    For direct entry in the "HtmlWidget", use:
-    **`<a href="project://dummy.pdf">Open File</a>`** (able to enter the HTML code without quotes).
3. After synchronizing the project, check the app to ensure that the fields display the link reference correctly.
4. …
> PDF Viewing Feature

- app/inpututils.cpp
- app/inpututils.h
- app/qml/form/MMFormPage.qml
Fixing check for whether `FormItem::name` has `nogallery` flag in the form's label name in `Relation Editor` widget type.
Fixes #3452
> Fixing override of relations editor bug

- app/synchronizationmanager.cpp
- app/synchronizationmanager.h
- core/merginapi.cpp
When attempting to upload a local only project, if the workspace project limit has been reached, the project is now removed from the synchronization pending list and is completely deleted if the project is removed by the user.
https://github.com/MerginMaps/mobile/assets/155513369/73233041-f390-4cc7-b0c3-9a7b7402fe09
Fixes #3403
> Handling attempt to upload a project after reaching the project limit

- app/qml/form/components/photo/MMPhotoAttachment.qml
- app/qml/form/editors/MMFormPhotoEditor.qml
Fixes #3405 
Also hides the texts for input when the editor is empty and the form is read-only
| Empty state - editable | Empty state - readonly |
| <img width="343" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/295c6c26-800e-444c-a499-4abaf7f336cd"> | <img width="356" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/8494fd02-47d6-49be-881a-f4b72c54d9e3"> | 
The resolution for #3405:
- we were checking the state of QML Image component when setting its source -> this is wrong as the last state should not have any impact on the new source that is to be set. Not sure why we were doing that, but this should fix it now.
> Photo editor fixes

- core/merginapi.cpp
Small fix in https://github.com/MerginMaps/mobile/pull/3450.
> Small fix in emitting projectCreated signal

- app/notificationmodel.cpp
- app/notificationmodel.h
- app/qml/main.qml
When a sync error of type "willRetry" (maintenance mode) occurs and its notification is displayed, the syncFailedDialog opens upon clicking it.
https://github.com/MerginMaps/mobile/assets/155513369/f00a57e0-015d-4f23-a54c-0fa4818e7606
Fixes #3451
> Open sync failed dialog when "willRetry" notification is clicked

- app/qml/account/MMAccountController.qml
Changed the generic error message, it is visible if the server is unavailable or the app does not have an internet connection. Previously the text did not mention the possibility of no internet connection.
> Update generic error message in login screen

- app/qml/account/MMAccountController.qml
- app/qml/account/MMLoginPage.qml
| Default Server | Placeholder Text After Deleting Default Server |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/d7690066-e8a7-477b-b0fb-0e06bc9e8c60" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/91b6eee0-97c9-4673-8787-f1acac863a67" width="300"> |
| Server Name Without "/" Then "Confirm" | Auto-Fixed Path With "/" At The End |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/af26432b-7720-41f9-b116-810351c72c99" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/db41b1c6-7765-4c34-9f3a-aa0b36ddd187" width="300"> |
Fixes #3437
> Custom server UX enhancement

- app/qml/project/MMProjectHomeTab.qml
- app/qml/project/MMProjectServerTab.qml
Weird bug here.. When we were trying to set `visible` property of the entire project controller (`MMProjectController.qml`) to false while `searchBar` had focus, the app would freeze (ANR). I spent a few hours debugging and have not found anything interesting. I believe this is coming from Qt (most likely https://bugreports.qt.io/browse/QTBUG-123876) as it started to appear in Qt 6.6.0 and even more in 6.6.3.
Ideally, the best fix would be to have the `MMProjectController` instantiated dynamically when needed and not play around with the `visible` property. However, that would be a massive change for now.
Resolves #3027 
Thanks @raherin for all the details in the bug report, they helped a lot! Can you please try this build and see if it fixes the issue also for your phone?
> Fix ANR when opening project with searchbar focus

- app/main.cpp
- app/qml/account/MMLoginPage.qml
- app/qml/account/MMSignUpPage.qml
- app/qml/components/private/MMBaseSingleLineInput.qml
- app/qml/form/editors/MMFormTextEditor.qml
- app/qml/form/editors/MMFormTextMultilineEditor.qml
- app/qml/inputs/MMPasswordInput.qml
- app/qml/settings/components/MMSettingsInput.qml
It seems to be working fine for me now with Qt 6.6.3 without any special hacks we had before. I tested Samsung and Google keyboards and they are working just fine with any type of editors in the form.
> Note: to disable predictive text on Android, one needs to either set `QT_ANDROID_ENABLE_WORKAROUND_TO_DISABLE_PREDICTIVE_TEXT` env variable (this then applies to all inputs) or set `Qt.ImhNoPredictiveText | Qt.ImhSensitiveData` as `inputMethodHints` (this then applies only to that one input). See https://bugreports.qt.io/browse/QTBUG-86982?focusedId=706751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-706751 for more info
Resolves #3434 
If the tests are ok, we can close https://github.com/MerginMaps/mobile/issues/1768, …
> Enable predictive text on Android

- app/qml/project/MMProjectList.qml
| Fixed BusyIndicator position | Second option: centered horizontally only (not applied) |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/00278f96-5718-4db7-a6c6-5c53db7cba90" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/fd338b99-6be5-4942-b3dd-4cb4d0275e32" width="300"> |
Fixes #3356
> Fixing BusyIndicator position in ProjectList

- app/qml/main.qml
Note: When we press "More options" (three dots) -> "Upload" on the homepage, it may take a while for the projectLimitDialog to appear. However, it will eventually show up after some time, depending on the connection quality.
Fixes #3364
> Fixing project limit hit problem 

- app/qml/form/MMFormPage.qml
> Fixing section headers' wrapping and eliding 

- app/CMakeLists.txt
- app/android/src/uk/co/lutraconsulting/MMAndroidPosition.java
- app/position/positionkit.cpp
- app/position/providers/androidpositionprovider.cpp
- app/position/providers/androidpositionprovider.h
- app/position/providers/internalpositionprovider.cpp
- app/position/providers/positionprovidersmodel.cpp
- app/qml/main.qml
- app/qml/settings/MMSettingsPage.qml
- cmake_templates/build.gradle.in
Initial version of the support for fused location provider:
- fused provider is opt-in only: nothing should change for the existing users if they do not switch to the "fused" provider. The app remembers whether user wants fused provider or not. The usual position provider is called just "Internal", the fused one is called "Internal (fused)"
- if the fused location provider is not available (due to Google Play services missing, outdated, disabled or invalid), we detect that and fall back to the internal gps-only provider (based on Qt Positioning)
- in a future release, we may want to switch to fused location as the default
- the implementation also adds "Internal (gps)" provider, which is based on Android's `LocationManager` just like the implementation in Qt Positioning - it is currently …
> Android: fused location provider

- app/attributes/attributepreviewcontroller.cpp
- app/test/testattributepreviewcontroller.cpp
- app/test/testattributepreviewcontroller.h
`AttributePreviewController::mapTipImage()` now supports multiline text with expressions.
E.g.:
```
file:///[%@project_folder%]/mapTip/[%
CASE WHEN "Checkbox" THEN
'bear.png'
ELSE
'beaver.png'
END
%]
```
In app:
Fixes #1106
> Support for multiple lines in map tip for images

- app/qml/components/MMToolbar.qml
Prevent freezing by clearing focus from all elements when `MMToolbar` is clicked on short button delegate(Home, Projects or Explore buttons).
Fixes #3389
> Fixing app freeze when switching pages

- app/appsettings.cpp
- app/appsettings.h
- app/qml/map/MMMapController.qml
- app/qml/map/MMRecordingTools.qml
- app/qml/settings/MMSettingsPage.qml
https://github.com/MerginMaps/mobile/assets/155513369/d7778a9e-b9ae-4637-b5e7-801d9840088e
Development and functionality of the feature based on: https://github.com/MerginMaps/mobile/issues/3506
Resolves  #3506
> Reintroduction of centering to GPS when starting to record new feature

- app/inpututils.cpp
- core/coreutils.cpp
- core/coreutils.h
- core/merginapi.cpp
Available storage is now added to diagnostic logs at the start of syncing.
Download and upload information is already available and logged in:
https://github.com/MerginMaps/mobile/blob/33ff5a8da0b04a55a83056cced9a5ed9952a8a1b/core/merginapi.cpp#L2418
https://github.com/MerginMaps/mobile/blob/33ff5a8da0b04a55a83056cced9a5ed9952a8a1b/core/merginapi.cpp#L2746
Resolves #3522
> Report available storage before syncing in diagnostic logs

- app/featuresmodel.cpp
It seems there is some edge-case scenario where a referenced layer in the value relation field is not available (probably a missing layer or some other project misconfiguration ... I could not reproduce it with my projects)
Logs are indicating that `mTitleField` is empty, thus we continue to `FeaturesModel::FeatureTitle` with `pair->layer()` as nullptr. See https://github.com/MerginMaps/mobile/blob/dd05acc2fbc4a55e65715b799810e37368cf83b0/app/valuerelationfeaturesmodel.cpp#L87-L96
See bug report logs for more details -> Fixes #3535
> Fix invalid layer in value relation field

- app/qml/components/private/MMBaseSingleLineInput.qml
- app/qml/form/MMFormPage.qml
- app/qml/form/editors/MMFormGalleryEditor.qml
Small fix in `MMBaseSingleLineInput.qml` to prevent app freeze in the first method of reproducing issue.
Fixes (Partially) #3538
> Fixing app freeze related to MMBaseSingleLineInput

- app/mmstyle.h
- app/qml/form/MMFormPage.qml
- app/qml/form/components/MMFormTabBar.qml
- gallery/qml/pages/FormPage.qml
We kept having issues with TabBar when project had multiple tabs, for example:
Solution: use `ListView` instead of `TabBar` 🙃 
ListView is set to mimic the behaviour of TabBar (horizontal orientation), the same project now looks like this:
There is a behavioural change for sections - I limited it to use only `ViewSection.InlineLabels`, because `CurrentLabelAtStart` was also producing some issues (see https://doc.qt.io/qt-6/qml-qtquick-listview.html#section-prop)
> Fix TabBar issues with multiple tabs

- app/qml/form/MMFormPage.qml
When editing The Unsaved changes" dialog was not showing up if the cancelled using the header back arrow  instead of the system back button. Therefore user could lost their changes 
This PR solve the issue and display the dialog when editing or adding a new feature
solve #3525
> Fix : Unsaved changes dialog not displayed when using back button

- app/attributes/attributecontroller.cpp
There was an issue (probably for ages) that behaved like this:
- have a layer (layer A) with a field that has unique constraint set
- add relations between this layer and some other layer (layer B)
- open a form of layer A to add a new feature, fill in details to the field with unique constraint (so that the validation passes - the value is unique)
- click to add a new child feature 
- validation is triggered when acquiring fid for the parent feature
- unique constraint validation fails -> this is because we run the validation while `QgsVectorLayer::commit` is in progress (when `QgsVectorLayer::featureAdded` is called), but the old feature (with `FID_IS_NEW`) is not yet removed from the layer. Thus, QGIS detects that there are two features with the same value and returns a unique …
> Fix wrong evaluation of unique constraint when creating child feature

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
MerginApi::parseVersion would cause app to crash, as indicated by crash report. Fix includes additional checks to ensure valid inputs and conversions, aiming to preventing crashes.
Resolves #3541
> Fixing crashes related to MerginApi::parseVersion 

- INSTALL.md
Update build instructions on GNU/Ubuntu
* The path of `DQGIS_QUICK_DATA_PATH` was still using the former name of the MerginMaps mobile app
* And the output name was not capitalized correctly
Remarque: It's already the case but the build instructions assume you build from a `build` folder located in the root for exemple `mobile/build/`
> Update build instructions on GNU/Ubuntu

- app/main.cpp
Setting `QGIS_USE_SHARED_MEMORY_KEEP_ALIVE` environment variable can significantly enhance performance and stability when working with large WFS layers by preventing frequent allocation and deallocation of shared memory, making projects smoother.
Before:
https://github.com/user-attachments/assets/6cdcdd80-1ea5-4aea-8503-d5ffefb06fde
After:
https://github.com/user-attachments/assets/fb84423c-faef-428c-8be0-b75ffb1b9322
Resolves #3558
> Optimize WFS layers handling on iOS

- app/qml/components/private/MMToolbarShortButton.qml
Text font for `MMToolbarShortButton` can change from t4 to t5 when the button text is too long and needs a better fit, resolvin text wrapping issue and also setting a maximum number of lines to 2, eliding it right after that.
| Portrait Before | Portrait After  |
|<img src="https://github.com/user-attachments/assets/b8c4905b-82d1-4403-b0e1-2ccc83f5e13c" width="150">| <img src="https://github.com/user-attachments/assets/5a15ef2c-7400-49ae-acfe-5f8b873904e7" width="150"> |
| Landscape Before| Landscape After |
|<img src="https://github.com/user-attachments/assets/ab733b93-ba52-4f7a-89cf-cdbf2652f90c" width="300">| <img src="https://github.com/user-attachments/assets/28efbc1d-9c3d-4f66-9b52-b40df811aa2a" width="300"> |
Fixes #3547
> Fixing text wrapping in MMToolbar

- app/guidelinecontroller.h
- app/qml/map/MMSplittingTools.qml
This PR fix #2320 where the guideline from last point to cursor wasn't showing in the splitting tool
The root issue was that the `GuidelineController::buildGuideline` was cancelled at the beginning of the function, because of the `allowed` property. So I turned allowed to be always true for the splitting tool
I wanted to show clearly to the users that the actual splitting line were the one to the last point and not  to the cursor.
So I updated the visual to match the way it works when adding a new line geometry
Let me know if it's working for the user experience otherwise I will revert that part
> Fix #2320 Split geometry visual problems

- cmake_templates/AndroidManifest.xml.in
Changes in `AndroidManifest.xml` to ensure that newer versions of Android can open more types of documents, such as XLSX, DOCX, and PNG, provided there is an application that can open these documents. See [reference.](https://stackoverflow.com/questions/11068648/launching-an-intent-for-file-and-mime-type)
> Handling XLSX and DOCX files in file viewing system for newer Android versions

- app/qml/project/MMProjectLoadingPage.qml
Before:
After
| Landscape | Portrait |
|<img src="https://github.com/user-attachments/assets/6ed5e920-4e6f-45ec-b0b1-38d7dc42248b" width="300">| <img src="https://github.com/user-attachments/assets/42340a4c-6e33-4115-9c44-6a661b2e7e98" width="200"> |
> Adjusting MMProjectLoadingPage text to respect safe area

- app/qml/map/MMRecordingTools.qml
In `MMRecordingTools`, `MMHighlights` are loaded only when they match the layer's geometry, improving performance by eliminating the need to load unnecessary components.
https://github.com/user-attachments/assets/f8cbac6d-de6b-4bfe-a71a-933513a3146b
Partially Resolves #[2980](https://github.com/MerginMaps/mobile/issues/2980)
> Adding Loaders to Highlights in Recording Tools

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- INSTALL.md
We dropped test.dev server env. I updated credentials for app.dev. See https://github.com/MerginMaps/python-api-client/commit/621c5ffe2bbfc3103894ee6f63b26a88ea963551
> Fix CI tests

- app/qml/map/MMMapController.qml
Following Figma, recording message `Mark the geometry on the map and click Record` has been added when recording mode is opened:
> Adding informational message on recording

- app/qml/account/MMAcceptInvitationPage.qml
- app/qml/account/MMAccountController.qml
- app/qml/account/MMCreateWorkspacePage.qml
- app/qml/dialogs/MMCloseAccountDialog.qml
- app/qml/dialogs/MMMissingAuthDialog.qml
- app/qml/dialogs/MMPositionTrackingDialog.qml
- app/qml/dialogs/MMWelcomeToNewDesignDialog.qml
- app/qml/gps/MMPositionProviderPage.qml
- app/qml/project/MMProjectHomeTab.qml
- app/qml/project/MMProjectList.qml
- app/qml/settings/MMAboutPage.qml
- gallery/qml/pages/MiscPage.qml
To enhance maintainability, reusability and other key attributes, we have replaced occurrences of `Mergin Maps` in notifications and tool/action descriptions within the app with more generic terms.
> Renaming "Mergin Maps" occurrences

- app/featuresmodel.cpp
- app/featuresproxymodel.cpp
- app/test/testmodels.cpp
In _MMFeaturesListPage_, when `FeaturesProxyModel::setFeaturesSourceModel( &model );` is called, the model layer is not yet defined, 
This led to `FeaturesModel::sortingEnabled()` always returning `false` and no sorting taking place.
With this PR, when the model's layer is changed, `FeaturesModel::setupSorting()` is also called followed by `FeaturesProxyModel::updateSorting()`
Test was adjusted to handle this.
@tomasMizera do you think it would be better if `FeaturesModel::sortingEnabled()` would implicitly call `FeaturesModel::setupSorting()` first instead?
Fixes #3604
> Fix FeaturesProxyModel sorting when model layer is set after setting the sourceModel

- app/qml/layers/MMFeaturesListPage.qml
Added `layerIsReadOnly` property as a condition for visibility of `Add Feature` button. If a layer is non-spatial and not read-only, the button will be visible.
| Read-only | Editable |
|<img src="https://github.com/user-attachments/assets/2340fd2d-1341-44dd-a5fb-1c9615d4a8ef" width="300">| <img src="https://github.com/user-attachments/assets/21fe116d-910e-40d8-b8c3-10adcbd1a45d" width="300"> |
Fix #3633
> Fix inconsistent UI/UX for read-only non-spatial layers

- core/merginprojectmetadata.cpp
- core/merginprojectmetadata.h
Luckily, it was read as an optional key so there is no need to keep the server compatible :)
> Remove deprecated reference to writernames

- .github/workflows/android.yml
- .github/workflows/gallery.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/macos_arm64.yml
- .github/workflows/win.yml
This PR bump the upload-artifact action to v4 because previous version are deprecated at the end of the month
In the case of the mobile repository, the naive bump to v4 worked without change. and the artifacts content are similar on the few I checked (android, windows, linux, and the gallery app artifacts)
> Bump upload-artifact action to v4

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
Implements a retry mechanism for failed downloads during project downloads, with a maximum of 5 retries per transaction. Individual file downloads now retry on network issues, being re-added to the download queue. Added a `downloadItemRetried` signal to track retry attempts. Added a getter/setter for the Mergin API's QNetworkAccessManager to support testing.
Retry system for downloads diagram:
Transaction download queue replies handling:
Resolves #3644
> Retry failed download requests implementation

- core/merginapi.cpp
- core/merginapi.h
- core/merginuserauth.cpp
- core/merginuserauth.h
In `reloadProjectRole`, we check if user is logged with new method `isLoggedIn` before proceeding, preventing `missingAuthorizationError` and `MMMissingAuthDialog` from popping up.
> Fix incorrect missing authentication dialog trigger

- app/qml/map/MMMapController.qml
`LayersProxyModel` previously did not reset its `mQgsProject` reference upon a project change, resulting in dangling pointers. To address this, the solution involves connecting to `projectChanged` signal emitted by `ActiveLayer` and resetting `mQgsProject` accordingly.
> Fix dangling pointer in LayersProxyModel

- app/qml/account/MMAccountController.qml
- app/qml/account/MMSignUpPage.qml
- app/test/testmerginapi.cpp
- core/merginapi.cpp
- core/merginapi.h
- core/merginerrortypes.h
- gallery/qml/pages/OnboardingPage.qml
Remove `username` and `password confirm` in the Sign up and user registration flow. 
Resolves #3702
> Remove username and password repetition from sign up flow

- app/icons/RemoteImageLoadError.svg
- app/icons/icons.qrc
- app/inpututils.cpp
- app/inpututils.h
- app/mmstyle.h
- app/qml/components/MMPhoto.qml
- app/qml/form/editors/MMFormPhotoEditor.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
- app/test/testutils.cpp
- app/test/testutils.h
- gallery/qml/pages/IconsPage.qml
When loading a photo, we now also verify if it's a url. If the url is valid, we consider it a valid image and proceed to load it. Since some urls might take longer to load, which is beyond our control, a `MMBusyIndicator` has been added to `MMPhoto` to enhance user experience in cases where loading images from urls might take a while.
https://github.com/user-attachments/assets/810a6e98-955f-4b70-b66a-2bc64040d051
| Remote image loading with error |
|--------|
Resolves #2718
> Online image preview support

- app/projectsmodel.cpp
- app/synchronizationmanager.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
- core/project.cpp
- core/project.h
Files listed on the server are now filtered before retrieving local changes status, ensuring that files excluded by selective sync are not compared. This prevents a permanent pending sync status when selective sync is enabled.
Resolves #3129
> Fix permanently pending synchronization issue for projects with selective sync enabled

- CMakeLists.txt
- INSTALL.md
- README.md
- cmake/FindAbsl.cmake
This PR fixes some minor things after the update:
- fix Absl typo, which generated CMake warning
- fix and update `INSTALL.md`
- clean up some more "input" references
> Tidy up after update to Qt 6.8.3

- app/test/testmerginapi.cpp
Introduce a delay after file operation to ensure consistent test behavior, particularly on Linux, where ocasional failures have been observed.
> Fix testHasLocalProjectChanges on Linux

- app/qml/components/MMListDelegate.qml
- app/qml/components/MMPageHeader.qml
- app/qml/form/MMPreviewDrawer.qml
Fixes #3760 and also some unintended HTML parsing
| bug | old version | new version |
| --- | --- | --- |
| Multi line feature name overflows | ![image](https://github.com/user-attachments/assets/c361bb21-40ae-4142-9957-1dc56795755a) | ![image](https://github.com/user-attachments/assets/d24a494b-0959-41d8-9b8c-6968c93af918) |
| Feature name with html tag in form page | ![image](https://github.com/user-attachments/assets/dcd5df24-78f6-4829-b0f7-2965ae80174d) | ![image](https://github.com/user-attachments/assets/2e731c30-ab4d-4151-83b1-473f8e6426b9) |
| Feature name with html tag in form preview & Feature field with html tag in form preview | ![image](https://github.com/user-attachments/assets/3e192a2c-6db6-4c2d-9ac5-2edb04933fb7) | …
> Fix multiline feature title breaking eliding & unintended HTML tags parsing 

- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/ios/iosutils.mm
- app/main.cpp
- cmake_templates/iOSInfo.plist.in
2 bug fixes / workarounds for iOS
1. We were reading safe area margins on app start (in `main.cpp`). With the latest Qt and Xcode iOS API upgrade, the values returned at this stage are empty. The fix is to query the margins once the event loop is running, the `UIWindow` should be all initialized then and return correct safe area margins.
2. When opening the app in landscape mode, the `orientation changed` information is received only after the `main.qml` is constructed. This would not be an issue, but is seems that `ApplicationWindow`'s `width` and `height` properties do not emit the `valueChanged` signal, leaving out components that depend on it (which is most of our components) not repainted. Summary: the `width` and `height` properties are updated, but without value changed signal. …
> Fix ios bugs after qt upgrade

- app/CMakeLists.txt
This PR fixes CMake warnings from QT policies.
- Sets QT policy [QTP0002](https://doc.qt.io/qt-6/qt-cmake-policy-qtp0002.html) to `NEW` as the old one is getting deprecated. We are not using either the old or new specific way to give paths.
- Sets QT policy [QTP0004](https://doc.qt.io/qt-6/qt-cmake-policy-qtp0004.html) to `NEW` as the old one is getting deprecated.
- Removes `set_source_files_properties` line. As far as I know `InputStyle.qml` doesn't exist anymore.
Fixes #3461
> Fix cmake warnings

- core/merginapi.cpp
Fixes #3734 
We replace the outdated hint with new hint.
Also part of this PR will be seeing this hint, when the password check fails on server (which actually does the whole check) and not just notification that password is not strong enough.
> Fix password hint

- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/account/MMAccountController.qml
- app/qml/account/MMLoginPage.qml
- app/qml/settings/MMSettingsController.qml
- app/test/testlinks.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
Api root will not include the trailing slash(es) from now on. URLs in api calls must start with `/`
Fixes #3862
> Api root should not end with slash

- app/qml/project/MMProjectList.qml
Scrolling was allowed beyond project list items end due to excessive height contributed by loading spinner component.
Behavior with issue:
https://github.com/user-attachments/assets/d596973f-ee1a-4a99-a0e3-a7de0ad0d71c
After fix:
https://github.com/user-attachments/assets/da8edf10-f1c6-446f-9805-8bbd37bad30b
> Fix project list scrolling

- app/qml/form/MMFormPage.qml
Save/cancel callbacks on `MMFormPage` have been renamed to match existing methods in `MMFormPhotoEditor`, `callbackOnFormSaved` and `callbackOnFormCanceled`. `onSaved()` and `onCanceled()` methods now invoke these callbacks properly. 
Fixes #3786
> Minimal fix for photo deletion 

- app/test/testvariablesmanager.cpp
- app/test/testvariablesmanager.h
- app/variablesmanager.cpp
- app/variablesmanager.h
- test/CMakeLists.txt
Fixes #3799 
This PR adds new QGIS expression variable `mergin_full_name`, which gives users name. Also we change the format of variables from `mergin_variable` to `mm_variable`. We keep the old format for backward compatibility.
> Introduce new QGIS expression variables

- app/main.cpp
Qt regression 6.8.0->6.8.2, on devices with Power VR.
See https://bugreports.qt.io/browse/QTBUG-134089
> Fix rendering issue on some Android devices

- app/test/testmerginapi.cpp
In fourth scenario, add a new file instead of modifying existing one.
> Fix testHasLocalProjectChanges 

- app/inpututils.cpp
- app/scalebarkit.cpp
This PR adds an exception when `screenUnitsToMeters` method fails in order to prevent app crashes.
> Throw exception on transform error

- app/qml/main.qml
- core/merginapi.cpp
- core/merginapi.h
Added a new error notification when a user tries to first upload a project to the server but lacks sufficient permissions in the current workspace and for generic project creation errors. Also halts syncing animation in the UI during project creation errors.
Resolves #3817, Resolves #3910
> Notify users of permission issues during project creation

- app/variablesmanager.cpp
This is a follow-up after changes in the plugin https://github.com/MerginMaps/qgis-plugin/pull/696. `mergin_project_owner` and `mm_project_owner` did not bear any value with the current DB structure.
> Drop project owner variable

- app/activeproject.cpp
This PR make the app follow the layer rendering order if it's manually overwritten in QGIS in the `Layer Order` Panel
Fix #3816
And might solve #1974 but to be confirmed
> Respect custom rendering order from QGIS

- app/layer/layertreesortfiltermodel.cpp
- app/layer/layertreesortfiltermodel.h
- app/test/testlayertree.cpp
Respect qgis layer panel order unless specified otherwise in the mergin configuration
See also https://github.com/MerginMaps/qgis-plugin/pull/756
> Sort layer order in the controller either by qgis order or by alphabetical order based on the setting

- app/inputhelp.cpp
fixes #4036 
instead of deciding what server is using, send request in both formats and let server decide
> Fix diagnostic log request

- app/invitationsmodel.cpp
- app/notificationmodel.cpp
- app/notificationmodel.h
- app/qml/account/MMAccountController.qml
- app/qml/components/MMNotification.qml
- app/qml/project/MMProjectController.qml
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
- core/merginuserinfo.cpp
- core/merginuserinfo.h
- Added `workspaceId` to `InvitationsModel` after `/v1/workspace/invitations` endpoint began including this field with each invitation. After accepting a workspace invitation, app now switches to accepted workspace and navigates to its project list if server version is bigger than `2025.4.1` ( see https://github.com/MerginMaps/server-private/issues/2936 ). 
- Added a new method `serverVersionIsAtLeast` to check whether server version meets or exceeds a required minimum version.
- Changed icon of `addIcon` method in `NotificationModel` from `WaitingIcon` to `InfoIcon`.
Resolves #3847
> Switch workspace on invitation accepted

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/photosketchingcontroller.cpp
- app/photosketchingcontroller.h
- app/qml/form/editors/MMFormPhotoEditor.qml
- app/test/testattributecontroller.cpp
- app/test/testattributecontroller.h
- app/test/testsketching.cpp
- app/test/testutils.cpp
- app/test/testutils.h
fixes #4057 
fixes #4056 (I didn't observe this bug anymore, it might be a side effect from the other bug)
- photo sketches now get saved into project subfolder in `temp`
- photo sketches get saved to original by `AttributeController` instead of `PhotoSketchingController`
- rework tests
> Fix photo sketching bugs

- app/qml/dialogs/MMSyncFailedDialog.qml
- app/qml/main.qml
Added the hasDetails flag to show or hide details component.
Set detailedText only if error message exists
Loader is used so details block is created only when needed
> Make detail dialog only visible if errorMessage exists

- app/qml/form/components/photo/MMPhotoPreview.qml
- Replaced pinch.target scaling with Flickable and PinchArea.
- On pinch, map center -> adjust contentX and Y so zoom focuses under fingers.
- Added _clamp() to keep content within bounds
- Changed photoUrl from alias -> plain url (avoid circular binding).
fixes #3563 
https://github.com/user-attachments/assets/b0183ddb-f873-454e-b09d-58c839564a9d
> Fix panning in image preview

- app/attributes/attributepreviewcontroller.cpp
- app/attributes/attributepreviewcontroller.h
fix #4031
When the user specifies the mapTooltip in QGIS on Windows, we don't remove the `\r` line delimiter, while parsing the field names. Thus no field names matches except the last one.
> Fix preview panel fields parsing

- app/layerfeaturesmodel.cpp
- app/layerfeaturesmodel.h
Very long running feature requests would keep running in background thread even if the caller model was destroyed.
We could also increment `mNextSearchId` upon destruction to cancel pending request, but passing a `QgsFeedback` pointer is clearer.
> cancel running background feature requests on model destruction

- app/android/src/uk/co/lutraconsulting/InputActivity.java
fixes #4047 
On some manufacturer devices (Samsung) the native method `vibrate(VibrationEffect vibe, VibrationAttributes attributes)` is not supported even though the android version should support it. However some other devices don't support `vibrate(VibrationEffect vibe)` while supporting the previous overload. Thus we use both variants and one execution should trigger the actual vibration.
Android Vibrator API has `areEffectsSupported(int... effectIds)` method, however on tested devices it returned the same value even though the behavior was different. And even this value is not final as the vibrator should have a fallback vibration even if it returns `unsupported`.
I was not able to reproduce the sound issue, but @IvaKuklica was. I'll have to investigate further with her.
> Fix haptic vibration

- .github/workflows/android.yml
- .zenodo.json
- CITATION.cff
- CMakeLists.txt
- cmake_templates/build.gradle.in
- vcpkg.json
- fix android AAB building in CI
- Update version to  `2025.7.0`
> Fix android CI
