MerginMaps/mobile

- app/img/home.svg
- app/img/pics.qrc
- app/loader.cpp
- app/loader.h
- app/qml/MainPanel.qml
- app/qml/main.qml
The button is temporally set to MainPanel with broken design. Design fix has been omitted on purpose for later work.
> Added home button with zoom to layers extent functionality

- app/qml/main.qml
Design is according Scalebar and will be most likely changed
closes #13
> Added gps accuracy label using positionKit

- app/config.pri.default
- app/input.pro
- app/main.cpp
This makes it easier to do changes in QGIS without having to run 'make install'
> Make it possible to run Input using QGIS from build dir

- app/input.pro
- app/main.cpp
Android includes only for android.
> Android extras extra extracted from the rest

- app/qml/main.qml
Changed mode of identifying features.
> Changed mode of identify tool

- app/qml/ActiveLayerPanel.qml
- app/qml/ExtendedMenuItem.qml
- app/qml/MapThemePanel.qml
> Highlight of MapTheme and Layer

- app/qml/FeaturePanel.qml
- app/qml/FeatureToolbar.qml
> Enabled delete button in the feature form

- app/android/assets/qgis-data/survey/demo.qgs
Added aerial photo and a theme for it in the demo project
> closes #95

- app/loader.cpp
- app/loader.h
- app/main.cpp
- app/qml/main.qml
This PR is related with changes in `QgsQuickPositionKit`, where `QgsQuickPositionKit::requestUpdates` function has been added to enable switch auto updates of position (PR for this hasnt been created to QGIS yet).
Closes #80 
NOTE: depends on https://github.com/qgis/QGIS/pull/8622
> GPS autoswitch depending on app activity

- app/qml/MapThemePanel.qml
> Close map theme panel after any theme is selected

- app/loader.cpp
> Fixed map extent with proper transformation

- .travis.yml
- app/android/AndroidManifest.xml
closes #132 and should fix build problem related to licence agreement
> Updated SDK and minimum android version to api 21 (android 5)

- app/loader.cpp
- app/loader.h
- app/qml/FeaturePanel.qml
- app/qml/PreviewPanel.qml
- project_config.md
Now supporting three modes: HTML, image, fields
See more in project_config.md
Closes #138
> Improve how feature preview panel interprets map tip content

- app/androidutils.cpp
- app/androidutils.h
- app/main.cpp
- publishing.md
Added docs about publishing the app to Google play.
> Added permissions requirements from code

- app/qml/FeaturePanel.qml
Added FeatureFormStyling to Feature panel.
NOTE: PR depends on changes in QGIS after https://github.com/qgis/QGIS/pull/9062
closes #156
closes #155 
closes #109 
closes #102
closes #101 
closes #72
> [QgsQuick] FeatureForm fixes

- app/qml/MainPanel.qml
- app/qml/ProjectDelegateItem.qml
- app/qml/ProjectPanel.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
The last opened one is set as default.
closes #161
> Deleted option for setting a default project - 

- app/qml/ActiveLayerPanel.qml
> minor spelling fix

- app/androidutils.cpp
- app/androidutils.h
- app/input.pro
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/qml/ExternalResourceBundle.qml
- app/qml/FeaturePanel.qml
- app/qml/qml.qrc
Added preview, delete and add from gallery functionality.
Depends on [https://github.com/qgis/QGIS/pull/9232](https://github.com/qgis/QGIS/pull/9232)
> ExternalResourceHandler added

- app/appsettings.cpp
- app/appsettings.h
- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/qml/NumberSpin.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
Each time after this period a point will be added to recordedPoints according the current position of QgsQuickPositionKit while recording.
closes #176
> Added digitizing period setting - 

- app/qml/FeaturePanel.qml
- app/qml/PreviewPanel.qml
- app/qml/ProjectDelegateItem.qml
different color for trash in externalResource widget
Change in title for featurePanel
fixed warning for empty string as AttributeValue
related to https://github.com/qgis/QGIS/pull/9388
> GUI tweaks

- app/android/AndroidManifest.xml
- app/input.pro
Just to keep up-to-date:
Android manifest updated due to last alpha release
removed crystax lib include due to failing build (changed ndk)
> Updated manifest and .pro

- app/qml/MainPanel.qml
Changed extended menu closing policy - any click outside closes it.
closes #210
> Extended menu closing policy

- app/digitizingcontroller.cpp
> Fixed validation when capturing point feature.

- app/loader.cpp
- app/loader.h
Need to go back to using QgsProject singleton...
> Fix handling of @project_folder in virtual fields

- app/appsettings.cpp
- app/layersmodel.cpp
- app/layersmodel.h
- app/qml/ActiveLayerPanel.qml
- app/qml/MainPanel.qml
- app/qml/RecordToolbar.qml
- app/qml/SettingsPanel.qml
- app/qml/main.qml
> Choose layer straight on record panel before recording.

- app/loader.cpp
- app/loader.h
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
Possible improvement could be reload project only if either project or data file has been changed.
closes #219
> Reloads project after successful sync.

- app/android/AndroidManifest.xml
> Increased minimum SDK to 23 (Android 6)

- app/test/testmerginapi.cpp
Small fix of compilation
Related to tests.
> Added toString() to QCompare argument

- app/main.cpp
Moved up setting QCoreApplication properties due to QSettings and .ini file initialization
closes #255
> Bugfix #255 - credentials and default values not stored

- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
Modified merginApiTest due to changes in api.
closes #256
> [WIP] Proper auth request with response

- app/merginapi.cpp
> Auth validation reply handling for non-admin users

- app/qml/ProjectPanel.qml
- app/qml/main.qml
Sometimes index could be the same for different projects.
closes #261
> Forced signals when changing project

- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
Just some simple code formatting as preparation to keep future diffs clean
> Code formatting

- app/qml/main.qml
> Disable autocenter when using zoom to project

- .travis.yml
> updated sdk

- app/qml/PositionMarker.qml
Simple implementation of using compass direction if available
> PositionMarker direction from compass

- .travis.yml
- scripts/upload-artifacts.sh
> fix branches with /

- app/qml/PositionMarker.qml
Compass azimuth kept for later
> Reverted Position Marker

- app/layersmodel.cpp
- app/layersmodel.h
- app/qml/ActiveLayerPanel.qml
> Filter out geometryless layers from digitizing

- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
NOTE: data folder from env. variable so far.
> [WIP] Test/upload

- app/merginapi.cpp
- app/merginapi.h
> Not include modification date of project folder in calculation for sync.

- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Cancel and separate test with modification of a file.
> Upload tests

- app/merginapi.cpp
- app/merginapi.h
> Feature/zero bytes files #343

- app/merginapi.cpp
- app/merginapi.h
- app/qml/MerginProjectPanel.qml
closes #331
related also to: #320
> Feature/project list ux #331

- app/merginapi.cpp
- app/merginapi.h
> Addded a proper error msg from the server reply

- app/qml/MerginProjectPanel.qml
> Added link to docs when a list of local projects is empty

- app/input.pro
- app/inpututils.cpp
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- docs/developers/for_devs.md
A bunch of cleanups of mergin-related tests - see individual commits
> Test improvements

- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
> Mergin api cleanups

- .gitignore
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- docs/developers/for_devs.md
More cleanups of MerginApi and tests - best to review individual commits separately.
> Mergin api cleanups 2

- app/merginapi.cpp
- app/merginapi.h
> Added support for login with email address.

- app/inpututils.cpp
- app/inpututils.h
- app/qml/ExternalResourceBundle.qml
- app/qml/FeaturePanel.qml
Changes required by QgsQuick changes (related to external widget and photopanel)
Can be closed after:  https://github.com/qgis/QGIS/pull/30929
closes: #380
> QgsQuick external resource widget handling

- app/loader.cpp
> Extra CR char removal in map tooltip

- app/merginapi.cpp
- app/qml/AuthPanel.qml
- app/qml/MerginProjectPanel.qml
Added test for empty login details.
Added loading while waiting for authorization, button is disabled.
closes #404
> Some fixes of authorization and the auth panel:

- app/digitizingcontroller.cpp
Using QgsVectorLayerUtils to create a feature - suppose to apply default values (expression)
closes #296
> Default values on feature create

- app/qml/AuthPanel.qml
- app/qml/MerginProjectPanel.qml
Split auth panel into two parts, the first one has flexible height according virtual keyboard height, the other one is static (height is flexible, position is static).
Suppose to improve behavior when a virtual keyboard is visible.
Changed behavior on signal authFailed() of the panel since it was called only when a user closes panel without login.
closes #332
> AuthPanel - better behavior with a virtual keyboard

- app/qml/ProjectDelegateItem.qml
- app/qml/ProjectLoadingScreen.qml
Tweak for project loading GUI + projects list.
Fix import for qt 5.9
> Tiny ui tweaks

- app/input.pro
Build cannot find bundle variable and was using default value
> Added bundle prefix variable

- app/ios.pri
- app/ios/Info.plist
- app/main.cpp
Slightly changed project data location and enable data-sharing through iTunes.
closes #421
> iOS data structure

- app/loader.cpp
- app/loader.h
- app/main.cpp
Creating a file during loading project and handling crash on the next run.
closes #437
> Reset default project after loading crashes

- app/qml/ProjectDelegateItem.qml
> Autoflex width project panel item's text

- .gitignore
- app/input.pro
- app/inpututils.cpp
- app/inpututils.h
- app/iosutils.cpp
- app/iosutils.h
- app/main.cpp
- app/qml/ExternalResourceBundle.qml
- app/qml/main.qml
- app/sources.pri
fix for camera. disable gallery for now on iOS
related to https://github.com/lutraconsulting/input/issues/418
> fix for camera, disable gallery for now [ios]

- app/qml/SettingsPanel.qml
> Removed Mergin section from the Settings page

- app/qml/MerginProjectPanel.qml
- app/qml/PanelHeader.qml
- app/qml/ProjectDelegateItem.qml
> Fixes of overlaping text on small screens

- app/qml/FeaturePanel.qml
> Disable feature panel swipe interactions

- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
- app/projectsmodel.cpp
- app/qml/MerginProjectPanel.qml
- app/test/testmerginapi.cpp
Allow user browse among public projects without authorization.
Eventually using API and applied tags in the request instated of local handling.
closes #449
> Changed the way how list of project is fetched

- app/qml/main.qml
> remove unnecessary workaround

- app/qml/ExternalResourceBundle.qml
- app/qml/FeaturePanel.qml
- app/qml/InputStyle.qml
CurrentValue should be updated with binding, not manually in a handler
Added icon as its all related to one PR [#32175](https://github.com/qgis/QGIS/pull/32175)
> Fixed external resource bundle (handler) that mixes feature's values

- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
> Fix of having multiple version of conflicted file

- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmetadata.cpp
- app/merginprojectmetadata.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
- app/qml/MerginProjectPanel.qml
> Allow download/update public projects without authorization

- app/loader.cpp
> Fix for one point and empty projects

- app/loader.cpp
- app/qml/ActiveLayerPanel.qml
- app/qml/MapThemePanel.qml
- app/qml/PanelHeader.qml
Active layer panel's layers are overflowing when dragging down for projects that has many layers. I added `clip:true `for list view. Another issue is when dragging down, the panel sometimes closes interactively. I turned it off and added `PanelHeader` with back button.
> Fixing overflowing issue for Active Layer Panel

- .travis.yml
- app/appsettings.cpp
- app/appsettings.h
- app/layersmodel.cpp
- app/layersmodel.h
- app/loader.cpp
- app/loader.h
- app/main.cpp
- app/mapthemesmodel.cpp
- app/mapthemesmodel.h
- app/qml/ActiveLayerPanel.qml
- app/qml/MapThemePanel.qml
- app/qml/RecordToolbar.qml
- app/qml/main.qml
Refactored code - moved handling of active layer and map theme to cpp code (models)
Travis build config updated due to error.
closes #535
> Fix of wrong and not connected choosing mapTheme with a record layer

- app/android/assets/demo-projects/survey/demo.qgs
Updated the demo survey project
> fixes #598

- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/merginprojectmodel.h
List of projects has been whole replaced regardless pending state of some of the projects.
closes #582 closes #565 closes #371
> Do not forget pending status of a project

- app/input.pro
- app/merginapi.h
Some changes to make local build passing.
Note: QSet include is complained only by iOS build
> Input build 20.04.2020

- scripts/build_win.cmd
fix #612
missing libprotobuf and szip
> fix win build

- .travis.yml
when android-10 is present on dropbox, travis restarted, resulting APK should work
> use new SDK with Qt 5.14.2 on docker

- .travis.yml
To use the latest qgis for fixes related to forms
> update to android-sdk-11

- docs/developers/manual_test_plan.md
maybe we should have platform versions too?
> added platforms to test plan

- app/input.pro
- app/linux.pri
- docs/developers/linux.md
Together with @PeterPetrik we successfully compiled and ran input on Linux. I am adding the packages I needed to install (and some changes) in order to run it.
> Update build dependencies on Linux

- docs/developers/index.md
- docs/developers/linux.md
Add sqlite3 and forgotten link to index.md
> Add sqlite3 and update index

- .travis.yml
with fix on qgis quick for out of bound gps location crash
> update to android-sdk-13

- app/qml/MerginProjectPanel.qml
> translate default message

- app/qml/MerginProjectPanel.qml
Issue caused by not updated currently selected project index.
closes #578
> Fix of selecting project after download

- .travis.yml
Best to review and merge this first:
https://github.com/lutraconsulting/input-sdk/pull/25
> update to android-sdk-14

- app/loader.cpp
- app/loader.h
- app/localprojectsmanager.cpp
- app/localprojectsmanager.h
- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/qml/main.qml
After sync, its called reloadProject which tried to force reload current project if its the one which has been synced. Does nothing if synced project haven't been opened.
closes #542
> Forced reloading project after its sync

- app/qml/BrowseDataPanel.qml
- app/qml/LayerAttributesPanel.qml
- app/qml/LayersListPanel.qml
- app/qml/MainPanel.qml
- app/qml/main.qml
- app/qml/qml.qrc
Icon to open `browseDataPanel`
Stackview for layers list and layer attributes
> Attribute table skeleton (part 1)

- app/qml/ActiveLayerPanel.qml
- app/qml/LayerList.qml
- app/qml/LayersListPanel.qml
- app/qml/qml.qrc
Refactored LayerList and used in Attribute Table layer selection page
related to #766
> Generic LayerList

- .travis.yml
fixes geodiff issue and 32-bit build
> update to android-sdk-15

- app/qml/AccountPage.qml
- app/qml/MerginProjectPanel.qml
- app/qml/RecordToolbar.qml
Clicks were propagated to inner elements.
Closes #752
> Catch propagation of clicks, fixes #752

- app/qml/SubscribePage.qml
NOTE: Each sentence is not on a new line as it was, just a whole text got wrapped according available width.
> Fixed subscribe notice text overflow

- app/featuresmodel.cpp
- app/featuresmodel.h
- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/BrowseDataPanel.qml
- app/qml/MerginProjectPanel.qml
- app/qml/SearchBar.qml
- app/qml/qml.qrc
Closes #784 
- adding searchbar (UI change)
- propagate text change to BE after defined time
- Separated searchbar from `MerginProjectsPanel` to `SearchBar` component
> Add search bar to attribute table

- app/featuresmodel.cpp
- app/featuresmodel.h
- app/qml/BrowseDataFeaturesPanel.qml
- app/qml/BrowseDataPanel.qml
- app/qml/BrowseDataView.qml
- app/qml/MerginProjectPanel.qml
- app/qml/SearchBar.qml
- app/qml/main.qml
Closes #795 
- Search bar logic for searching within features.
- So far we allow search in text and number attributes. 
- name of found attribute together with its value is shown next to description text
> Attr table search logic #795

- app/qml/SearchBar.qml
Now searchbar works after each key hit.
Closes #838
> fix textfield typing ignorance - now works after each type

- app/ios/iospurchasing.h
- app/ios/iospurchasing.mm
- app/main.cpp
- app/merginapi.cpp
- app/merginsubscriptiontype.cpp
- app/merginsubscriptiontype.h
- app/merginuserinfo.cpp
- app/merginuserinfo.h
- app/purchasing.cpp
- app/purchasing.h
- app/qml/AccountPage.qml
- app/qml/TextWithIcon.qml
- app/sources.pri
- app/test/testingpurchasingbackend.cpp
- app/test/testingpurchasingbackend.h
- docs/developers/macos.md
fixes #800 
fixes #803 for already paid subscriptions (next billing price)
> Apple fixes

- app/ios/iospurchasing.mm
- app/main.cpp
- app/merginapi.cpp
- app/merginsubscriptionstatus.h
- app/merginsubscriptiontype.cpp
- app/merginsubscriptiontype.h
- app/merginuserauth.cpp
- app/merginuserinfo.cpp
- app/merginuserinfo.h
- app/purchasing.cpp
- app/qml/AccountPage.qml
- app/test/testingpurchasingbackend.cpp
- app/test/testingpurchasingbackend.h
- app/test/testmerginapi.cpp
- app/test/testpurchasing.cpp
- app/test/testpurchasing.h
- app/test/testutils.h
- app/variablesmanager.cpp
> Apple fixes2

- app/purchasing.cpp
- app/purchasing.h
- app/qml/MerginProjectPanel.qml
- app/qml/SubscribePage.qml
- app/qml/SubscribePlanItem.qml
- app/qml/qml.qrc
- app/test/testingpurchasingbackend.cpp
- app/test/testingpurchasingbackend.h
- app/test/testpurchasing.cpp
> Allow to buy individual and professional plan

- docs/users/project_config.md
Related to new fixes for Date/Time and attachment widget.
> Added user docs related to QgsQuick forms

- app/purchasing.cpp
Changed link to follow Mergin API
discussion: https://lutraconsulting.slack.com/archives/CC95JK1T9/p1600866820003600
> Changed subscription link to reflect mergin api

- app/merginapi.cpp
- app/merginprojectmetadata.cpp
- app/merginprojectmetadata.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Due to changes on the Mergin server
closes #569
> Use writersname instead if writers (user) id

- app/merginapi.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Input did not generate chunk ID when file size was 0.
Closes #851
> Fix empty file upload crash #851

- app/merginapi.cpp
- app/merginapi.h
- app/test/testmerginapi.cpp
Note: Do not merge without passing tests!
closes #787
> Added mergin username and local version to a conflict filename

- app/inputhelp.cpp
- app/inputhelp.h
- app/inpututils.cpp
- app/inpututils.h
- app/main.cpp
- app/merginsubscriptionstatus.cpp
- app/merginsubscriptionstatus.h
- app/qml/LogPanel.qml
- app/qml/SettingsPanel.qml
- app/qml/SubscribePlanItem.qml
- app/qml/main.qml
- app/qml/qml.qrc
- app/test/testlinks.cpp
- app/test/testlinks.h
> add log panel

- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/LogPanel.qml
- app/qml/SettingsPanel.qml
- non-inverted order
- no extra char at line start in log
- renaming of user visible strings
> Assorted fixes to log panel

- app/qml/AccountPage.qml
> Added visibility conditions to restore purchasing according the issue

- app/merginapi.cpp
- app/qml/MerginProjectPanel.qml
> Fixed RegisterForm after successful registration

- app/qml/AccountPage.qml
> Restoring a purchase can be done without active subscription

- app/qml/RegistrationForm.qml
> updated the link to EULA

- app/merginapi.cpp
- app/merginapi.h
- app/qml/MerginProjectPanel.qml
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
> Removed local check for write access

- app/qml/ProjectDelegateItem.qml
> Enlarged project item from project lists by removing project icon

- app/qml/SettingsPanel.qml
Added between About and Diagnostic log
closes #987
> Added help external link under Settings

- app/qml/FeaturePanel.qml
- app/qml/FeatureToolbar.qml
heavily related to https://github.com/qgis/QGIS/pull/38742
closes #458 
closes #831
> Disable save button when hard constraints are not met

- app/qml/MerginProjectPanel.qml
> Check has been removed and reverted back by rebase

- app/merginapi.cpp
- app/merginapi.h
If registration is successful, takes user back to "my projects" view 
Resolves #954
> Log in after sign up

- .travis.yml
- app/android.pri
- qgsquick/from_qgis/qgsquickfeatureslistmodel.cpp
- qgsquick/from_qgis/qgsquickfeatureslistmodel.h
- scripts/check_all.bash
- scripts/copy_to_qgis.bash
@tomasMizera please restart (close and open PR) when you have andoid-18 uploaded. thanks
> Fix android

- docs/developers/android.md
- scripts/build-qgsquick-android.bash
Script to build `qgsquick` and edited docs
> Android script and docs

- qgsquick/from_qgis/plugin/editor/qgsquickvaluerelation.qml
> Center value relation icon

- .github/workflows/ios.yml
- app/activelayer.cpp
- app/ios.pri
- scripts/ci/ios/exportOptions.plist
partially fixes https://github.com/lutraconsulting/input/issues/1020
> fix ios crashes when adding new feature

- app/activelayer.cpp
- app/qml/main.qml
> fix crash on opening the project

- app/qml/NumberSpin.qml
- app/qml/PanelHeader.qml
- app/qml/SearchBar.qml
- app/qml/SettingsPanel.qml
Enlarged touch areas as seen on this picture (red zones represents mouse areas):
Resolves #1054 
Update: Enlarged also area around clear text in the same manner as in number spin
> Enlarge clickable areas

- app/qml/LoginForm.qml
maybe @mostlyAtNight can advise on the correct text to display?
> add some explanatory text to help out users understand what mergin is

- app/linux.pri
- qgsquick/CMakeLists.txt
Added necessary directories for build to both qgsquick and Input﻿
> Fix Linux desktop build

- qgsquick/from_qgis/attributes/qgsquickattributeformmodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributeformmodel.h
- qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.cpp
- qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.h
- qgsquick/from_qgis/plugin/ios/qgsquick.qrc
- qgsquick/from_qgis/plugin/ios/qmldir
Fixes ios build by adding new checkbox component to ios qml dir.
> Add checkbox component to ios dir

- app/projectwizard.cpp
- app/projectwizard.h
> Style for wizard projects

- app/projectwizard.cpp
Changed the point type so the Z value will be captured too.
fixes #1166
> Use PointZ in wizard

- qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
Might not covered some edge cases (editing)
> Enabled hyperlink in TextEdit widget

- qgsquick/from_qgis/plugin/components/qgsquickicontextitem.qml
- qgsquick/from_qgis/plugin/editor/qgsquickexternalresource.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
Redesigned photo widget based on [proposed design](https://www.dropbox.com/home/_Projects/input/graphic%20materials/2021-02/edit%20form?preview=_input_app_Edit_Feature-001.png)
<table>
<tr>
<th>Old</th>
<td><img src="https://user-images.githubusercontent.com/22449698/109304591-c7c6d680-783c-11eb-9eb8-82437a579afb.jpg" width=300></td>
</tr>
<tr>
<th>New</th>
<td><img src="https://user-images.githubusercontent.com/22449698/109304390-80404a80-783c-11eb-9463-228a38ee6041.jpg" width=300> <img src="https://user-images.githubusercontent.com/22449698/109304393-80d8e100-783c-11eb-901e-4e6ab5f842e0.jpg" width=300></td>
</tr>
</table>
Resolves #1150
> Redesigned photo widget

- app/qml/ActiveLayerPanel.qml
- app/qml/FeaturePanel.qml
- app/qml/MapThemePanel.qml
- app/qml/PanelHeader.qml
Code cleaned from unnecessary references for back text in the header.
> Removed "back" text from PanelHeader

- app/linux.pri
Added ZXing to INCLUDEPATH and path to lib, so that Linux can compile.
﻿
> Add ZXing to linux.pri

- app/qml/FeaturePanel.qml
> Different feature form header for edit/view

- app/qml/FeaturePanel.qml
- app/qml/InputStyle.qml
- app/qml/ProjectWizardPage.qml
- app/qml/components/DelegateButton.qml
- app/qml/components/FieldRow.qml
- app/qml/components/InputTextField.qml
- app/qml/components/SimpleTextWithIcon.qml
- app/qml/qml.qrc
> Project wizard form fixes

- app/localprojectsmanager.cpp
- app/localprojectsmanager.h
- app/merginapi.cpp
- app/merginapi.h
- app/merginprojectmodel.cpp
- app/models/projectsmodel_future.cpp
- app/models/projectsmodel_future.h
- app/models/projectsproxymodel_future.cpp
- app/models/projectsproxymodel_future.h
- app/project_future.cpp
- app/project_future.h
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/sources.pri
C++ part of listing projects implemented.
- Local and Remote projects merging after `listProjects` or `listProjectsByName` API finished
Based on proposed https://docs.google.com/document/d/16UYzt-1YGOZyFbXvewK2ehQVAa4dRnUHc1yMQ77HnI4/edit#heading=h.uv0wbgj210je
> [Refactoring] Listing projects logic

- app/qml/ProjectWizardPage.qml
> Use displayText instead of text for project name field in ProjectWizard

- app/main.cpp
- app/merginapi.cpp
- app/merginapi.h
- app/project.h
- app/projectsmodel.cpp
- app/projectsmodel.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Fixed tests for MerginAPI.
What remains from refactoring are the todos mentioned in previous PR (#1293)
> [Refactoring] Fix tests

- qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
related to https://github.com/qgis/QGIS/pull/42692
> Updates variable due to change in QGIS Quick because of spelling

- app/compass.cpp
- app/compass.h
- app/ios/iosimagepicker.cpp
- app/ios/iosimagepicker.h
- app/ios/iosimagepicker.mm
- app/ios/iosinterface.h
- app/ios/iosinterface.mm
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/main.cpp
- app/positiondirection.cpp
- app/positiondirection.h
- app/qml/PositionMarker.qml
- app/qml/main.qml
- app/sources.pri
Implementation of EXIF for iOS using Camera. 
GPS data used from QgsQuickPositionKit and QCompass.
https://user-images.githubusercontent.com/6735606/114743968-7c657a80-9d4d-11eb-939f-a9c79a3d2d94.MP4
> EXIF data for ios camera

- qgsquick/from_qgis/CMakeLists.txt
- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
- qgsquick/from_qgis/attributes/qgsquickattributemodel.h
- qgsquick/from_qgis/plugin/CMakeLists.txt
- qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
- qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
- qgsquick/from_qgis/plugin/qgsquickplugin.h
- qgsquick/from_qgis/qgsquickcoordinatetransformer.h
- qgsquick/from_qgis/qgsquickfeaturehighlight.h
- qgsquick/from_qgis/qgsquickfeaturelayerpair.h
- qgsquick/from_qgis/qgsquickfeatureslistmodel.h
- qgsquick/from_qgis/qgsquickhighlightsgnode.h
- qgsquick/from_qgis/qgsquickidentifykit.h
- qgsquick/from_qgis/qgsquickmapcanvasmap.h
- qgsquick/from_qgis/qgsquickmapsettings.h
- qgsquick/from_qgis/qgsquickmaptransform.h
- qgsquick/from_qgis/qgsquickmessagelogmodel.h
- qgsquick/from_qgis/qgsquickpositionkit.h
- qgsquick/from_qgis/qgsquickscalebarkit.h
- qgsquick/from_qgis/qgsquickutils.h
Some extra touches were required for QGS Quick PR: https://github.com/qgis/QGIS/pull/42804
> QgsQuick changes to keep up with QGS

- qgsquick/from_qgis/attributes/qgsquickattributemodel.cpp
related to #1281
related to #1233
> Do not crash when switching the projects

- docs/developers/secrets.md
Due to change in the path of merginsecrets.cpp
> Updated secret docs

- app/qml/ProjectPanel.qml
Found small bug - component doesn't exists anymore.
> Changed outdated reference in a condition

- core/coreutils.cpp
- core/coreutils.h
required for https://github.com/lutraconsulting/mergin-cpp-client/pull/6
> more_log_options

- app/qml/components/ProjectDelegateItem.qml
Only font color is greyed out.
closes #1345
> Changed bg color for an invalid project in Project list

- core/project.cpp
When a project with a geopackage is opened, the header of gpkg file is modified. Therefore gpkg modified timestamp is updated as well. That causes the issue that project acts like there is something to be uploaded.
closes #1320
> Added an extra check if project status is "modified"

- app/qml/AuthPanel.qml
- app/qml/LoginForm.qml
- Added ScrollView to Login form similarly as it is in Registration form.
- Fixed also `root` references to have independent Login form component.
- Set bottom padding of AuthPanel to 0 to save a bit of space for landscape mode and to prevent rendering components on bottom padding white space (kind of clipping).
- Note that the text field for Mergin link is anchored to bottom and basically it acts like a static footer of AuthPanel - not sure if its better to have it like this or rather not. Anyway, I kept it as it was for now.
- Centered Sing up and Forgot password buttons by removing an extra Column wrapper around each of them.
> Scrollable Login form

- app/linux.pri
- app/macx.pri
Added core folders to fix build. 
I added folders also `macx.pri`, they were not there but I am not sure if builed worked or not. @sklencar can you please test if the mac build is working and if not check if this helps?
> Fix Linux (and possible Mac) build

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/digitizingcontroller.cpp
- app/digitizingcontroller.h
- app/inpututils.cpp
- app/main.cpp
- app/positionkit.cpp
- app/positionkit.h
- app/qml/FeaturePanel.qml
- app/qml/main.qml
- app/variablesmanager.cpp
- app/variablesmanager.h
Implementation of Position variables according docs: https://github.com/lutraconsulting/input-docs/pull/31
Manual tests (C) added to: https://github.com/lutraconsulting/input-manual-tests/issues/6 
Most of the values for position variables are obtained from QGeoPositionInfoSource - note that some of the attributes might be missing/not available. Direction is from compass sensor. 
Also registration of exif functions has been moved to VariablesManager.
Note that (position) attributes are not updated after geometry is edited - bug ticket https://github.com/lutraconsulting/input/issues/1416
TODO: automatic tests
closes #547
> WIP: Position variables

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
> Fix of evaluating default values

- app/inputhelp.cpp
pointing to the correct terms of service page
> fixes #1485

- docs/developers/linux.md
Removed qgsquick dependency and added ZXing build
> Update linux build steps after qgsquick removal

- app/androidutils.cpp
- app/inputhelp.cpp
- app/ios/iosimagepicker.cpp
- app/ios/iosimagepicker.h
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/main.cpp
- app/qml/RegistrationForm.qml
- app/qml/form/FeatureForm.qml
- changed TOS link
- fixed remember last value checkboxes
- notification about incorrect photo path
> Some bugfixes

- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/AboutPanel.qml
- app/qml/LoginForm.qml
- app/qml/RegistrationForm.qml
- app/test/testlinks.h
Added UTM tags to links that directs to inputapp / public mergin websites.
If user has custom server deployed / dev.dev, UTM tags are **not included**, is this correct @mostlyAtNight ?
Resolves #1593
> Add UTM tags to links

- app/config.pri.default
- app/linux.pri
- docs/developers/linux.md
Update of docs for developers on Linux.
> Update dev docs for linux

- .github/workflows/code_style.yml
Disabled QML formatting check for now until we get all PRs merged and format manually several files.
> Disable qml check for now

- app/loader.cpp
This PR addresses this issue:
https://github.com/lutraconsulting/input/issues/1046
I'm not sure if it's very correct to use project extent instead of WMS extent all the time and I'm just assuming it will just work...
> use project extent instead of WMS extent [1046]

- .github/workflows/linux.yml
There was a wrong condition in the linux workflow. `linux`->`!mac`
> Fix linux CI build

- scripts/copy_qgsquick.bash
Script was checking existence of files we just removed (quick utils). Replaced it with map canvas.
> [CI] QgsQuick check - compare to existing files

- .github/workflows/i18n.yml
- scripts/update_i18n_ts.bash
Translations CI was failing due to a missing package on ubuntu apt for older Qt version. Fixed this by using separate action (jurplel) to install Qt.
> Fix i18n CI

- app/loader.cpp
- app/loader.h
- app/projectwizard.cpp
- app/qml/Banner.qml
- app/qml/InputStyle.qml
- app/qml/LogPanel.qml
- app/qml/NotificationBanner.qml
- app/qml/ProjectIssuesPanel.qml
- app/qml/components/TextWithIcon.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/qml.qrc
Addresses https://github.com/lutraconsulting/input/issues/1263
When some of the project's layers are invalid, a notification is displayed saying that some layers are invalid:
Maybe I should find a way to display a notification the same way the GPS accuracy warning is displayed?
> Display notification when some layers are invalid [1263]

- app/inputhelp.cpp
Update links to help pages to point to the new website.
TODO: resolve utm tags
> Update help links to new docs website

- docs/developers/linux.md
> Rework linux build instructions

- app/qml/components/MapFloatButton.qml
What do you think if we make the drop shadow a bit more subtle?
Before:
After:
> Small adjustment to the floating button shadow

- app/qml/NotificationBanner.qml
replacement for @NEDJIMAbelgacem https://github.com/lutraconsulting/input/pull/1801
> Missing layers warning scaling fix (rebased)

- app/test/testscalebarkit.cpp
- app/test/testutilsfunctions.cpp
Tested values needed to be updated since now PROJ is working on macos :)
> Update autotests after PROJ path fix

- .gitignore
- app/android.pri
- app/config.pri.default
- docs/developers/android.md
> crash on 32b start

- app/android.pri
https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding
> add shared libraries after unwind as per docs

- .github/workflows/macos.yml
Test server was redeployed and db was reset, that fixed autotests. We previously tried to add different test user, but that di not work out.
> Fix autotests

- app/inputhelp.cpp
Links to new docs should end with `/`
> Add trailing slashes to help links

- .github/workflows/ios.yml
- .github/workflows/linux.yml
- app/inpututils.cpp
- app/inpututils.h
- app/qml/ProjectPanel.qml
- app/qml/components/ProjectList.qml
- core/localprojectsmanager.cpp
- core/localprojectsmanager.h
PR adds new logs for mentioned events and few helper functions.
Closes #1911
> Add logs for created/removed local project event

- core/merginapi.cpp
Added missing error reporting for some cases of failed sync.
Also remove the diff files created on such failures.
Fix #1849
> Report server errors

- app/qml/NavigationPanel.qml
Minor changes to `NavigationPanel`'s code. I am using bindings rather than direct assignments. Also adds a comment to how x/y coordinates are computed for gps marker in close-range mode.
Does nothing new visually.
> modernize code for navigation panel

- app/activeproject.cpp
- app/activeproject.h
- app/main.cpp
- app/projectsmodel.cpp
- app/qml/Banner.qml
- app/qml/InputStyle.qml
- app/qml/MainPanel.qml
- app/qml/ProjectPanel.qml
- app/qml/SettingsPanel.qml
- app/qml/banners/AutoHideBanner.qml
- app/qml/components/MapFloatButton.qml
- app/qml/dialogs/MigrateToMerginDialog.qml
- app/qml/dialogs/MissingAuthDialog.qml
- app/qml/dialogs/NoPermissionsDialog.qml
- app/qml/dialogs/SyncFailedDialog.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/qml.qrc
- app/sources.pri
- app/synchronizationerror.cpp
- app/synchronizationerror.h
- app/synchronizationmanager.cpp
- app/synchronizationmanager.h
- app/synchronizationoptions.h
- app/test/testmerginapi.cpp
- core/merginapi.cpp
- core/merginapi.h
- core/project.cpp
- core/project.h
PR adds two parts of Autosync: GUI and retry of sync when it fails. 
**Retry**  
Retry is handled by `SynchronizationManager`, it has an internal array of `syncProcesses` that holds a sync proceses during the whole time of sync (sync start, failure, waiting for another sync, sync again, finish).
**GUI**, some screenshots:
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/160770620-872e4141-1ce1-49d1-84ad-8c195201cb5d.jpeg" width="300"/></td>
<td><img src="https://user-images.githubusercontent.com/22449698/160770622-771f69d0-a154-4a47-a734-792d4bdfe001.jpeg"  width="300"/></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22449698/160770625-0b4c48f9-c09d-43bd-952d-f0cff7e7647d.jpeg" width="300"/></td>
<td><img …
> Autosync - repeat syncs & GUI

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/qml/form/FeatureForm.qml
- app/qml/form/FeatureFormPage.qml
Show small warning banner when committing changes to vector layer fails.
Fixes #1797.
> Show error message when adding/editing/removing feature fails (fix #1797) 

- app/guidelinecontroller.cpp
- app/guidelinecontroller.h
- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/maptools/splittingmaptool.cpp
- app/maptools/splittingmaptool.h
- app/position/mapposition.cpp
- app/qml/map/Crosshair.qml
- app/qml/map/RecordingTools.qml
- app/qml/map/SplittingTools.qml
- app/snaputils.cpp
- app/snaputils.h
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
Better comparison of old and new snapped positions.
> Fixes for snapping issues

- app/main.cpp
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/map/RecordingToolbar.qml
- app/qml/map/RecordingTools.qml
- app/test/testmaptools.cpp
Fixes recodring of polygons after switching to direct geometry editing. Also fix centering map on the clicked vertex.
> Fix recording of polygons

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/valuerelationfeaturesmodel.h
Unify vertex editing (adding/removing) functions. This is first step and more work needed to handle case when geometry is completely redrawn.
> Unify vertex editing functions

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
Added `start`/`end` handles handling and more fixes
> changes in recording map tool, remove / add vertex

- app/guidelinecontroller.cpp
- app/guidelinecontroller.h
- app/maptools/recordingmaptool.cpp
- app/qml/map/RecordingTools.qml
More work on the geometry editing:
- fixes recording and editing of points
- fix guideline when handle point is selected
- attempt to fix removal of non-existent vertex
> Fix vertex editing and handling of handles

- app/guidelinecontroller.cpp
- app/maptools/recordingmaptool.cpp
- app/qml/map/RecordingTools.qml
Hopefuly fix all remaining issues:
- vertex removal in lines
- visual glitch with line highlight when end handle is selected
- hide point highlight when editing its geometry
> Fixes for geometry editing

- app/img/minus.svg
- app/maptools/recordingmaptool.cpp
- app/qml/InputStyle.qml
- app/qml/map/RecordingToolbar.qml
Handle cases:
- releasing point if polygon contains only 2 or 1 points
- releasing first/last line vertex after removing handle
Also change "Remove" button icon.
> Handle more edge cases

- .github/workflows/ios.yml
- .github/workflows/linux.yml
- app/img/eraser.svg
- app/img/pics.qrc
- app/qml/FormsStackManager.qml
- app/qml/InputStyle.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FeatureToolbar.qml
- app/qml/form/FormWrapper.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
Adds redraw geometry functionality. Original geometry is not hidden yet.
> redraw geometry

- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/qml/map/RecordingTools.qml
- app/test/testlinks.cpp
- app/test/testutilsfunctions.cpp
Add check for geometry validity which works also for multipart lines/polygons
Display "Done" button when editing multipoint layers
> Fix TODOs and some minor improvements

- README.md
the old link in readme was dead...
> Fix transifex link

- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FeatureToolbar.qml
- app/qml/map/RecordingTools.qml
Includes following changes:
- fix crash in `updateVisibleItems()`
- hide "Advanced" menu for non-spatial layers
- another attempt to commit/rollback on Done/Cancel (not working properly yet)
> Edit buffer support (pt 4) 

- app/inpututils.cpp
- app/inpututils.h
- app/maptools/recordingmaptool.cpp
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FeatureToolbar.qml
- app/qml/map/RecordingTools.qml
- app/test/testmaptools.cpp
- app/test/testmaptools.h
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
- enable previously disable tests
- fix issues revealed by tests
- add tests to move/delete vertex
- fix some crashes revealed by tests
- try to fix #2233
- try to fix #2234
- try to fix #2248
- try to fix #2239
> Edit buffer support (pt 5) 

- app/guidelinecontroller.cpp
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/form/FeatureToolbar.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingToolbar.qml
- app/qml/map/RecordingTools.qml
Move undo button to the floating button in edit mode.
Also fix following issues:
- #2255 
- #2236
- #2239
- #2264
- #2265
- #2235
> Edit buffer support (pt 6) 

- app/qml/form/FeatureFormPage.qml
> initialize controllers before calling their methods (fix #1938)

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/form/FeatureFormPage.qml
> Geoedit fixes

- app/inpututils.cpp
- app/inpututils.h
- app/qml/form/FeatureForm.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/map/MapWrapper.qml
Store original feature when editing geometry and restore it on cancel.
> restore previous state when hitting cancel in the form

- app/inpututils.cpp
- app/maptools/recordingmaptool.cpp
- app/test/testutilsfunctions.cpp
> handle Z/M values when creating geometry (fix #2281)

- app/attributes/attributecontroller.cpp
- app/attributes/attributecontroller.h
- app/attributes/rememberattributescontroller.cpp
- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/qml/form/FeatureForm.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/form/FeatureToolbar.qml
- app/qml/form/FormWrapper.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingTools.qml
> fix reusing last enetered attribute values (fix #2285)

- app/android.pri
- app/androidutils.cpp
- app/androidutils.h
- app/ios.pri
- app/main.cpp
- app/qml/CodeScannerOverlay.qml
- app/qml/ExternalResourceBundle.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/map/RecordingTools.qml
- scripts/android-aab.bash
- scripts/android-apk.bash
Fix QR code scanner.
Use new API and fix deprecations warnings.
> Qt6 support (pt2)

- app/maptools/recordingmaptool.cpp
- app/test/testmaptools.cpp
- app/test/testmaptools.h
> fix adding points when wkb type is not flat (fix #2309)

- app/maptools/recordingmaptool.cpp
- app/maptools/recordingmaptool.h
- app/test/testmaptools.cpp
> add M coordinate to geometry if layer has M values (fix #2312)

- app/qml/map/MapWrapper.qml
- app/qml/map/SplittingToolbar.qml
Fixes:
- #2319
- #2279
- non-functional back button when digitizing child feature as reported in clickup
> Fix back button

- app/qml/AccountPage.qml
- app/qml/AuthPanel.qml
- app/qml/Banner.qml
- app/qml/LoginForm.qml
- app/qml/NotificationBanner.qml
- app/qml/PhotoPanel.qml
- app/qml/ProjectPanel.qml
- app/qml/ProjectWizardPage.qml
- app/qml/components/ProjectList.qml
- app/qml/form/FeatureForm.qml
- app/qml/layers/LayerDetail.qml
- app/qml/layers/LayersListPageV2.qml
- app/qml/layers/LayersListSearchPage.qml
- app/qml/layers/LayersPanelV2.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/misc/LegacyFolderMigration.qml
- app/qml/misc/PositionProviderPage.qml
Fixes more slot connections, type comparison coercions and download project dialog
Fixes #2364 and partially fixes the login page issue (blank screen when typing in login credentials).
> Random Qt6 qml fixes

- .github/workflows/qgsquick.yml
- app/main.cpp
- app/qml/map/RecordingTools.qml
- qgsquick/plugin/qgsquickmapcanvas.qml
- qgsquick/qgsquick.pri
- qgsquick/qgsquickmapcanvasmap.cpp
- qgsquick/qgsquickmapcanvasmap.h
- qgsquick/qgsquickmapsettings.cpp
- qgsquick/qgsquickmapsettings.h
- qgsquick/qgsquickutils.cpp
- qgsquick/qgsquickutils.h
An attempt to MQGA (Make the Qgsquick check Green Again)
It updates the code from QgsQuick and adds our animation there.
PRs that must be merged first:
- https://github.com/qgis/QGIS/pull/50809
- https://github.com/qgis/QGIS/pull/50810
TODO:
> Update qgs quick (fix qgsquick check)

- app/qml/components/InputComboBox.qml
- app/qml/components/ProjectList.qml
- app/qml/editor/inputvaluerelationpage.qml
- app/qml/layers/LayersListSearchPage.qml
- app/qml/map/ActiveLayerPanel.qml
Just fixing more parameter injections to keep Qt6 silent 🙂
> Fix another set of parameter injections in QML

- qgsquick/plugin/qgsquickmapcanvas.qml
Qt6 `TapHandler` in combination with `PinchHandler` might end up in an invalid state after zooming in/out a few times.
In this state, `TapHandler` ignores events coming to it with error:
```js
W qt.quick.touch.target: : QQuickTapHandler(0x77693800c0) pointId 1 is missing from current event, but was neither canceled nor released
```
This PR is a workaround, real fix must be done in Qt code.
The workaround destroys and instantiates new `TapHandler` each time pinch gesture finishes.
See the Qt bug report here: QTBUG-108689
> [Fix] Canvas sometimes ignores taps

- app/android/build.gradle
It was upgraded in Qt https://github.com/qt/qtbase/blob/dev/src/android/templates/build.gradle#L8
> Upgrade gradle to 7.2.1

- app/activeproject.cpp
Fixes failing active project test
> fix failing test

- app/map/inputmapcanvasmap.cpp
- app/map/inputmapsettings.cpp
> Remove translation from log strings

- app/qml/AccountPage.qml
- app/qml/ExternalResourceBundle.qml
- app/qml/components/ProjectList.qml
- app/qml/dialogs/MigrateToMerginDialog.qml
- app/qml/dialogs/MissingAuthDialog.qml
- app/qml/dialogs/NoPermissionsDialog.qml
- app/qml/dialogs/SplittingFailedDialog.qml
- app/qml/dialogs/SyncFailedDialog.qml
- app/qml/form/FeatureFormPage.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
- app/qml/misc/LegacyFolderMigration.qml
- app/qml/misc/PositionProviderPage.qml
- core/merginapi.cpp
Adds manual call to `close` MessageDialog components.
Some of these are slightly refactored.
#31vb28n
Resolves #2395 
Resolves #2392
> Qt6 fixes/fix message dialogs closing

- docs/README.md
- docs/translations.md
These docs got removed during cmake transition by mistake
> Bring back docs about translations

- app/qml/editor/inputvaluerelationcombobox.qml
> Fix parameter injection in combobox

- app/qml/components/PanelHeaderV2.qml
- app/qml/components/SearchBoxV2.qml
- app/qml/components/ToolbarButton.qml
- app/qml/layers/FeaturesListPageV2.qml
- app/qml/layers/LayerDetail.qml
- app/qml/layers/LayersListPageV2.qml
- app/qml/layers/LayersListSearchPage.qml
- app/qml/layers/LayersListV2.qml
- app/qml/layers/LayersPanelV2.qml
- app/qml/main.qml
- app/qml/map/RecordingTools.qml
Some imports were still with versions - version numbers are obsolete now
> Qt6 fixes/Remove import versions of qt libs

- app/androidutils.cpp
- app/fieldsmodel.cpp
> fix crash when duplicate fields added (fix #2440)

- app/androidutils.cpp
Fixes `shouldShowRequestPermissionRationale` call.
Refs #2432
> try to fix issue with camera permission

- app/androidutils.cpp
> fix crash when requesting gallery permission (fix #2461)

- app/qml/components/MainPanelButton.qml
Hopefully fixes issue with clicking on the "Create project" button and freezes during digitizing (#2441, #2446)
> try to fix freezes when buttons are pressed too fast and too often

- app/qml/ProjectPanel.qml
> rename My Projects to Projects

- core/merginapi.cpp
- core/merginapi.h
Emited if we use default server AND previous server type was OLD AND new server type is SAAS.
> add signal to notify about server upgrade

- app/qml/WorkspaceAccountPage.qml
> show switch workspace button in the account page only for saas and ee

- app/qml/CreateWorkspacePage.qml
- app/qml/ProjectPanel.qml
- app/qml/RegistrationFinishPage.qml
- core/merginapi.cpp
Needs fix on the server side: error response should have 409 code.
> when user creates a new workspace warn if workspace with this name already exists

- app/appsettings.cpp
- app/appsettings.h
- app/inputhelp.cpp
- app/inputhelp.h
- app/qml/CMakeLists.txt
- app/qml/CreateWorkspacePage.qml
- app/qml/InputStyle.qml
- app/qml/WhatsNewDialog.qml
- app/qml/main.qml
- app/test/testlinks.h
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
Show what's new dialog when server upgraded.
@tomasMizera may I ask you for help with the UI, can't figure out what's wrong with the text
> What's new dialog

- cmake_templates/iOSInfo.plist.in
https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations?language=objc
https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption?language=objc
> Add NonExemptEncryption consent to Info.plist

- app/inputhelp.cpp
- app/qml/CreateWorkspacePage.qml
- app/qml/ManageInvitationsPage.qml
- app/qml/ProjectPanel.qml
- blog link
- removal of logo and hello text
- hide create button in manage invitations
> Merge 2.0.1 integration branch

- app/inputhelp.cpp
- core/merginapi.cpp
- core/merginapi.h
TOS has moved to https://merginmaps.com/terms-of-service - PR reflects that
> Change TOS url

- app/qml/SettingsPanel.qml
We are Mergin Maps, not Mergin! 🙂 Thanks @alex-cit
> Update TOS button after rebranding

- app/workspacesproxymodel.cpp
> make workspace search case insensitive (fix #2555)

- app/maptools/recordingmaptool.cpp
> don't create handle for one point (fix 2612)

- app/qml/ProjectPanel.qml
- core/merginapi.cpp
- core/merginapi.h
If you have 0 workspaces and accept invitation ➝ switch to that workspace
If you have n (>0) workspaces and accept invitation ➝ open SwitchWorkspace page
> Invitations handling

- app/projectsmodel.cpp
- app/projectsproxymodel.cpp
- app/qml/components/ProjectList.qml
Use client-side filtering only for local projects, all other pages use server-side filtering.
> fix requesting wrong page when filtering project list

- app/qml/SettingsPanel.qml
> do not show new badge for streaming mode settings

- app/qml/components/SearchBoxV2.qml
Set `Qt.ImhNoPredictiveText` and use `displayText` as a filter text.
> fix feature search (refs #2646)

- app/featuresmodel.h
- app/position/positiondirection.h
- core/merginapi.h
- core/project.h
Got a wrong description on `FEATURE_LIMIT`, grep'ed and fixed some other occurrences too
> repair inline docstrings

- app/inpututils.cpp
workaround for https://bugreports.qt.io/browse/QTBUG-114219
> fix cp of files on android for qt  651

- app/projectwizard.cpp
> use zipped QGIS project file by default

- app/main.cpp
- app/qml/CMakeLists.txt
- app/qml/InputStyle.qml
- app/qml/ProjectPanel.qml
- app/qml/RegistrationForm.qml
- app/qml/components/ErrorText.qml
- app/qml/components/LeftCheckBox.qml
- app/qml/components/PasswordField.qml
- app/qml/main.qml
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
Updated style of the error messages in the registration form
Fixes #2274
> New: CU-2ub0937 Added error message when a registration step is not OK

- app/qml/ExternalResourceBundle.qml
Screencast of how it looks:
https://github.com/MerginMaps/input/assets/72412563/11e56649-8a23-41d3-bbe4-c55c0f75ffff
> Added zoom and rotation to pictures in feature form

- app/qml/dialogs/MigrateToMerginDialog.qml
> Changed sync button OK->YES

- app/qml/layers/FeaturesListPageV2.qml
> Fixed feature text overflow

- app/qml/InputStyle.qml
- app/qml/main.qml
- app/qml/map/MapWrapper.qml
Added a green strap when tracking is running.
_Note: I needed to move some things around in the MapWrapper to ensure all other items like banners, GPS marker and toolbars stay in their correct position. Essentially, I nested the map canvas in a deeper component._
The review is quite impossible this way, if you want to have a look at the code, please open `MapWrapper.qml` -> I added the first `ColumnLayout` and the `trackingIndicator` rectangle.
**Preview:**
https://github.com/MerginMaps/input/assets/22449698/d66e84a3-755e-4ab5-ae0c-ecad97cf81a5
> Add indicator when tracking is running

- .github/workflows/ios.yml
- CMakeLists.txt
- INSTALL.md
- app/CMakeLists.txt
- app/attributes/attributecontroller.cpp
- app/main.cpp
- app/qml/ExternalResourceBundle.qml
- app/qml/editor/inputvaluerelationpage.qml
- app/qml/form/FeatureForm.qml
- app/qml/main.qml
Fixes a bunch of warnings/runtime errors.
One fix per commit.
Target branch is set to `use-automatic-signing-ios` just because I need that fix for my local build :) We can retarget once that one is merged
> Fix qt652 warnings

- .github/workflows/android.yml
- CMakeLists.txt
fix https://github.com/MerginMaps/input/issues/2762
> Set Android target SDK to 33

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- app/test/testutilsfunctions.cpp
- enable tests on lnx too
- move lcov to lnx build from macOS
> Lcov to lnx

- app/map/inputmapcanvasmap.cpp
tnx for the fix to Qfield team
> fix mapcanvas memory leak

- app/CMakeLists.txt
- app/enumhelper.h
- app/qml/CMakeLists.txt
- app/qml/ProjectLimitDialog.qml
- app/qml/main.qml
- core/merginapi.cpp
- core/merginapi.h
Show this popup with a link to update the plan, instead of a simple toast, in case of max. number projects is reached
Fixed code to show this popup with a link to update the plan in case of max. size of projects is reached
> Show dialog when max. number of projects was reached

- app/qml/layers/FeaturesListPageV2.qml
Showing feature names and description in one row
CU-861n6vx85
> Fixed showing multiline features

- app/qml/ExternalResourceBundle.qml
All iOS problems with photo subfolders should be solved:
fixes #2393 
fixes #2353
fixes #1266
> iOS: Fixed problems with subfolders for photos

- app/qml/editor/inputtextedit.qml
- app/qml/form/FeatureForm.qml
> Fixed app freezing when feature edit was canceled

- app/qml/editor/inputvaluerelationcombobox.qml
Hopefully the last occurrence (v2 final final finalest)
> Fix deprecated parameter injection

- app/maptools/recordingmaptool.cpp
> fix digitizing polygon undo crash

- .github/workflows/android.yml
- .github/workflows/code_style.yml
- .github/workflows/gallery.yml
- .github/workflows/i18n.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/win.yml
- CMakeLists.txt
- INSTALL.md
- app/ios/iosinterface.mm
- app/ios/iosviewdelegate.h
QT 6.5.3 has problem with `ScrollView->Repeater`, `ScrollView->Column` and CRS on iOS, revert for now: 
revert of https://github.com/MerginMaps/input/commit/a1ff0c4dfad61d2dade099c4a646d260c521bfa6
see https://github.com/MerginMaps/input/pull/2895
fix #2893
fix #2892
fix #2891
fix #2887
> revert to qt652

- core/merginapi.cpp
- core/merginapi.h
This will try to do up to 5 parallel download requests during the sync...
Fixes #330
> Download data in parallel during sync

- app/main.cpp
add notification to log about app start with version (useful for seeing when app was upgraded or crashed)
fix #2911
> add notification to log about app start

- app/qmlV2/component/MMButtonInput.qml
- app/qmlV2/component/MMInput.qml
- app/qmlV2/component/MMPasswordInput.qml
- app/qmlV2/component/MMSwitch.qml
- gallery/qml/pages/InputsPage.qml
[](url)2 improvements:
- updated slider design
- added title for all Input
> Added title for Inputs. Updated Switch design.

- app/mmstyle.h
- app/qml/inputs/MMAbstractEditor.qml
- app/qml/inputs/MMCheckBox.qml
- app/qml/inputs/MMInputEditor.qml
- app/qml/inputs/MMPasswordEditor.qml
- app/qml/inputs/MMSliderEditor.qml
- gallery/qml.qrc
- gallery/qml/Main.qml
- gallery/qml/pages/ChecksPage.qml
- gallery/qml/pages/EditorsPage.qml
MMSliderEditor {
title: "MMSliderEditor"
width: parent.width
from: -100
to: 100
parentValue: -100
suffix: " s"
onEditorValueChanged: function(newValue) { errorMsg = newValue > 0 ? "" : "Set positive value!" }
hasCheckbox: true
checkboxChecked: true
}
MMInputEditor {
title: "MMInputEditor"
width: parent.width
parentValue: "Text"
hasCheckbox: true
}
MMInputEditor {
title: "MMInputEditor"
width: parent.width
placeholderText: "Placeholder"
warningMsg: text.length > 0 ? "" : "Write something"
}
MMPasswordEditor {
title: "MMPasswordEditor"
width: parent.width
parentValue: "Password"
errorMsg: "Password must contain at least 6 characters\nMinimum 1 number, uppercase and lowercase letter and special character"
}
> Dev redesign inputs

- app/attributes/attributecontroller.cpp
> fix #2947 (fix delete return)

- app/mmstyle.h
- app/qml/components/MMIconCheckBoxHorizontal.qml
- app/qml/components/MMIconCheckBoxVertical.qml
- app/qml/onboarding/MMAcceptInvitation.qml
- app/qml/onboarding/MMCreateWorkspace.qml
- app/qml/onboarding/MMHowYouFoundUs.qml
- app/qml/onboarding/MMLogin.qml
- app/qml/onboarding/MMSignUp.qml
- app/qml/onboarding/MMWhichIndustry.qml
- gallery/qml/pages/OnboardingPage.qml
Finished all onboard screens, also for tablets.
There are a few known visual issues, but they are not important for the implementation of the Input app.
> Onboarding adjusted for tablets

- app/position/tracking/androidtrackingbackend.cpp
- app/position/tracking/androidtrackingbroadcast.cpp
- app/qml/components/MMCodeScanner.qml
- app/qml/inputs/MMQrCodeEditor.qml
- gallery/CMakeLists.txt
- gallery/inpututils.h
- gallery/main.cpp
- gallery/qml.qrc
- gallery/qml/pages/EditorsPage.qml
- gallery/qrcodedecoder.h
MMQrCodeEditor {
title: "MMQrCodeEditor"
placeholderText: "QR code"
warningMsg: text.length > 0 ? "" : "Click to icon and scan the code"
onEditorValueChanged: function(newValue, isNull) { console.log("QR code: " + newValue) }
}
> QR code input

- app/qml/components/MMNotification.qml
- app/qml/components/MMNotificationView.qml
- gallery/qml/pages/NotificationPage.qml
Notifications are lined up on top of each other now. The newest is on the top. Visible is only the last notification.
> Notifications position

- app/qml/map/MMMapScaleBar.qml
- gallery/CMakeLists.txt
- gallery/main.cpp
- gallery/qml.qrc
- gallery/qml/pages/MapPage.qml
- gallery/scalebarkit.h
```
MMMapScaleBar {
sourceItem: map
}
```
> Map scale bar

- app/qml/CMakeLists.txt
- app/qml/form/MMFormTabBar.qml
- gallery/qml.qrc
- gallery/qml/Main.qml
- gallery/qml/pages/FormPage.qml
Added feature form scrollable tab bar into the gallery app.
Also added a new page into the gallery app - `FormPage.qml` - where I will add the whole form component overtime
How to use:
```qml
MMFormTabBar {
tabButtonsModel: ListModel {
ListElement { Name: "Address of the object" }
ListElement { Name: "Description of the object xyz" }
}
}
```
> Add feature form tab bar into gallery

- gallery/qml/pages/FormPage.qml
**Please first merge https://github.com/MerginMaps/mobile/pull/3032**
Adds feature form into the gallery - I will follow a similar approach when doing it in the actual app
> Feature form in gallery

- app/qml/components/MMListDrawerItem.qml
- app/qml/components/MMMapLabel.qml
- app/qml/components/MMMapPicker.qml
- app/qml/components/MMProjectItem.qml
- app/qml/map/MapWrapper.qml
- gallery/qml/pages/MapPage.qml
> Bunch of visual icon fixes 

- app/qml/components/MMDropdownDrawer.qml
- app/qml/inputs/MMDropdownInput.qml
- app/qml/project/MMProjectWizardFieldRow.qml
- app/qml/project/MMProjectWizardPage.qml
- gallery/qml/pages/InputsPage.qml
```
MMDropdownInput {
valueRole: "value"
textRole: "text"
dataModel: ListModel {
ListElement {
value: 1
text: "Text 1"
}
ListElement {
value: 2
text: "Text 2"
}
ListElement {
value: 3
text: "Text 3"
}
}
}
```
> Extended DropdownInput

- app/qml/components/MMDropdownDrawer.qml
- app/qml/components/MMSettingDropdown.qml
- app/qml/components/MMSettingInput.qml
- app/qml/components/MMSettingItem.qml
- app/qml/components/MMSettingSwitch.qml
- app/qml/settings/MMSettingsPanel.qml
- gallery/CMakeLists.txt
- gallery/formfeaturesmodel.h
- gallery/inpututils.h
- gallery/main.cpp
- gallery/qml.qrc
- gallery/qml/pages/PagesPage.qml
- gallery/streamingintervaltype.h
Added new SettingsPanel with new editable components:
- MMSettingInput
- MMSettingDropdown
- MMSettingSwitch
https://github.com/MerginMaps/mobile/assets/72412563/f268f1a3-a5a9-4a31-a95b-4c3d462d749f
> New SettingsPanel

- app/android/src/uk/co/lutraconsulting/InputActivity.java
- app/androidutils.cpp
- app/androidutils.h
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/ios/iosutils.mm
- app/main.cpp
- app/mmstyle.h
- app/qml/main.qml
🎉 Content shown edge-to-edge
Todo:
> Edge-to-edge in Mergin Maps

- app/qml/account/MMCreateWorkspacePage.qml
- app/qml/account/MMHowYouFoundUsPage.qml
- app/qml/account/MMSwitchWorkspacePage.qml
- app/qml/account/MMWhichIndustryPage.qml
- app/qml/components/MMMenuDrawer.qml
- app/qml/form/MMForm.qml
- app/qml/gps/MMGpsDataDrawer.qml
- app/qml/map/MMMapThemeDrawer.qml
- app/qml/project/MMProjectController.qml
- gallery/qml/pages/FormPage.qml
Removed `TODOs` (old `rightMarginShift`), see #3104
> Fix page headers

- app/mmstyle.h
- app/qml/CMakeLists.txt
- app/qml/account/MMAccountPage.qml
- app/qml/account/components/MMAccountHeadItem.qml
- app/qml/account/components/MMAccountPageItem.qml
- gallery/qml.qrc
Updated layout of the account page
> Fix layout in the account page

- app/qml/CMakeLists.txt
- app/qml/dialogs/MMFormDeleteFeatureDialog.qml
- app/qml/dialogs/MMFormEditFailedDialog.qml
- app/qml/form/MMFormPage.qml
- gallery/qml.qrc
- gallery/qml/pages/DrawerPage.qml
MMFormEditFailedDialog
MMFormDeleteFeatureDialog
> MMFormEditFailedDialog and MMFormDeleteFeatureDialog

- app/mmstyle.h
- app/qml/CMakeLists.txt
- app/qml/account/MMAccountPage.qml
- app/qml/account/MMSwitchWorkspacePage.qml
- app/qml/account/components/MMIconCheckBoxHorizontal.qml
- app/qml/account/components/MMIconCheckBoxVertical.qml
- app/qml/account/components/MMWorkspaceDelegate.qml
- app/qml/account/components/MMWorkspaceInvitationDelegate.qml
- app/qml/components/MMListSpacer.qml
- app/qml/components/MMScrollView.qml
- app/qml/components/MMTextBubble.qml
- app/qml/components/MMWarningBubble.qml
- app/qml/form/editors/MMFormRichTextViewer.qml
- app/qml/inputs/MMBaseInput.qml
- app/qml/inputs/MMSearchInput.qml
- app/qml/layers/MMLayerDetailPage.qml
- app/qml/project/MMProjectController.qml
- app/qml/settings/MMSettingsPage.qml
- app/workspacesproxymodel.cpp
- gallery/qml.qrc
- gallery/qml/pages/PagesPage.qml
- Fixed layout of the switch workspace page
- Introduced `MMScrollView` -> convenient class to use for scrollable MMPage's
- Introduced `MMListSpacer` -> convenient class for custom spaces in lists
- Fixes #2976 
Best to go over commits one by one
> Fix layout of the switch workspace page

- app/qml/CMakeLists.txt
- app/qml/components/MMDrawerDialog.qml
- app/qml/dialogs/MMDiscardGeometryChangesDialog.qml
- app/qml/dialogs/MMOutOfDateCustomServerDialog.qml
- app/qml/dialogs/MMProjErrorDialog.qml
- app/qml/dialogs/MMProjectLoadErrorDialog.qml
- app/qml/main.qml
- app/qml/map/MMMapController.qml
- gallery/qml.qrc
- gallery/qml/pages/DrawerPage.qml
- ```MMDrawerDialog.qml``` fields description and boundedDescription now accept links.
| MMProjErrorDialog | MMOutOfDateCustomServerDialog |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/9c1ad6f3-b2ee-4705-a692-08cf0d662341" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/84e4ea8a-87e1-4c1c-8636-ddbc8e372ee2" width="300"> |
| MMProjectLoadErrorDialog | MMDiscardGeometryChangesDialog |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/8bac491d-6d44-4141-ab15-f21bc0f9afdf" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/5165e9b6-1996-47b1-9daf-024ce6b7f437" width="300"> |
> MMProjErrorDialog, MMOutOfDateCustomServerDialog, MMProjectLoadErrorDialog and MMDiscardGeometryChangesDialog

- app/qml/CMakeLists.txt
- app/qml/dialogs/MMProviderRemoveReceiverDialog.qml
- app/qml/gps/MMPositionProviderPage.qml
- gallery/qml.qrc
- gallery/qml/pages/DrawerPage.qml
| MMProviderRemoveReceiverDialog |
|--------|
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/da3c1492-5ad3-47bb-b769-c2dd9e836a0b" width="300">|
> MMProviderRemoveReceiverDialog

- app/qml/CMakeLists.txt
- app/qml/components/MMPhoto.qml
- app/qml/components/MMPhotoAttachment.qml
- app/qml/components/MMPhotoPreview.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
- gallery/qml.qrc
- gallery/qml/pages/PhotosPage.qml
https://github.com/MerginMaps/mobile/assets/72412563/04b6da61-6170-4840-a1f3-224fff625035
https://github.com/MerginMaps/mobile/assets/72412563/308188b6-2640-4863-99e6-69c521ab70cc
> Photo attachment and Preview

- app/appsettings.cpp
- app/appsettings.h
- app/icons/FollowGPS-nocoloroverlay.svg
- app/icons/icons.qrc
- app/mmstyle.h
- app/qml/components/MMToolbar.qml
- app/qml/form/MMFormController.qml
- app/qml/form/MMFormPage.qml
- app/qml/form/editors/MMFormValueRelationEditor.qml
- app/qml/main.qml
- app/qml/map/MMMapCanvas.qml
- app/qml/map/MMMapController.qml
- app/qml/map/MMRecordingTools.qml
- app/qml/settings/MMSettingsPage.qml
- gallery/inpututils.h
- gallery/qml/pages/IconsPage.qml
> Formfixes1

- gallery/qml/EditorItem.qml
- gallery/qml/pages/EditorsPage.qml
Test links in multiline editor:
`
See something powerfull <a href='https://merginmaps.com/docs/' style='color: green;'>Mergin Maps documentation</a>, for more information continue <a href='https://merginmaps.com/docs/'>here</a>."`
> Lnks in multiline editor

- app/qml/inputs/MMSearchInput.qml
- gallery/qml/pages/InputsPage.qml
Added x button to clear searched text
> Clear Search

- app/qml/account/MMHowYouFoundUsPage.qml
Show the social submenu when clicking on 'Social media' menu
> 'Social media' submenu

- app/mmstyle.h
- app/qml/CMakeLists.txt
- app/qml/account/MMAccountController.qml
- app/qml/account/MMLoginPage.qml
- app/qml/account/MMSignUpPage.qml
- app/qml/account/components/MMAuthPageBackground.qml
- app/qml/components/MMButton.qml
- app/qml/components/MMCheckBox.qml
- app/qml/components/MMDrawer.qml
- app/qml/components/MMHlineText.qml
- app/qml/components/MMListVerticalFillSpacer.qml
- app/qml/components/MMMessage.qml
- app/qml/components/MMPageHeader.qml
- app/qml/dialogs/MMCloseAccountDialog.qml
- app/qml/project/MMProjectController.qml
- app/qml/project/MMProjectHomeTab.qml
- app/qml/project/MMProjectWizardPage.qml
- gallery/qml.qrc
- gallery/qml/pages/ButtonsPage.qml
> Fix auth pages layout

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/macos.yml
See https://github.com/actions/runner-images/issues/4020
See https://github.com/actions/runner-images/issues/8838
> [HOTFIX] Fix mobile CI builds

- app/qml/components/MMCalendarDrawer.qml
- app/qml/form/editors/MMFormCalendarEditor.qml
- gallery/qml/pages/EditorsPage.qml
> Calendar adjustments

- app/qml/project/MMProjectWizardPage.qml
MMProjectWizardPage.qml adjustments
> Project Wizard Page adjustments

- app/qml/components/MMPhotoPreview.qml
- app/qml/form/editors/MMFormPhotoViewer.qml
> Photo preview fix

- app/mmstyle.h
- app/qml/account/MMAcceptInvitationPage.qml
- app/qml/account/MMAccountController.qml
- app/qml/account/MMHowYouFoundUsPage.qml
- app/qml/account/MMWhichIndustryPage.qml
- app/qml/account/components/MMIconCheckBoxHorizontal.qml
- app/qml/components/MMPage.qml
> Fix onboarding pages 2

- app/notificationmodel.h
- app/qml/project/MMProjectList.qml
- app/qml/project/components/MMProjectDelegate.qml
> Do not try to open broken projects

- app/mmstyle.h
Example: ```Q_PROPERTY( double fontLineHeight22 READ fontLineHeight22 CONSTANT )``` changed to ```Q_PROPERTY( double fontLineHeight22 READ number22 CONSTANT )```
> Defining numbers from 1 to 150 and specific values for mmstyle.h

- .github/workflows/linux.yml
- CMakeLists.txt
- app/CMakeLists.txt
This depends on https://github.com/MerginMaps/mobile-sdk/pull/108
> Do not link to glib on linux

- app/qml/components/MMToolbar.qml
- app/qml/components/MMToolbarButton.qml
- app/qml/components/MMToolbarMenuButton.qml
- app/qml/map/MMRecordingTools.qml
- gallery/qml/pages/ToolbarPage.qml
toolbarbutton with enabled/visible state
fix recording toolbar buttons
fix ISS-85 Recording buttons should be disabled when they have no action like "undo" or "remove"
> Fix recording tools 

- app/inputprojutils.cpp
ISS-86 -> it works for me for desktop & iOS, on iPhone it is tricky to close app (so it is not just minimized)
> do not use Input in message dialogs for PROJ

- app/qml/components/MMDrawer.qml
- app/qml/gps/MMStakeoutPanel.qml
When the ESC key or back button is pressed, or when the closeButton is clicked, the MMStakeoutPanel closes correctly.
> Get the correct closing of MMStakeoutPanel and correct state update

- app/mmstyle.h
- app/qml/components/MMBusyIndicator.qml
- app/qml/map/MMMapController.qml
- app/qml/map/components/MMBlurBox.qml
- app/qml/map/components/MMMapBlurLabel.qml
- app/qml/map/components/MMMapLabel.qml
- app/qml/map/components/MMMapScaleBar.qml
> Fix layout on map canvas + fix map loading indicator

- app/qml/form/MMFormPage.qml
- gallery/qml/pages/ButtonsPage.qml
> use red button when hard constrains are not met

- app/qml/settings/MMSettingsPage.qml
Bug fix: ISS-87
| Time Elapsed | Distance Traveled |
|<img src="https://github.com/MerginMaps/mobile/assets/155513369/8a6ddb68-b77f-4683-a645-0a41043dc7b1" width="300">| <img src="https://github.com/MerginMaps/mobile/assets/155513369/5e4c0511-b87e-499f-b954-4fce6b8c6992" width="300"> |
> Fixing selection of "Distance Traveled" or "Time elapsed" in MMSettingsPage

- app/changelogmodel.cpp
- app/changelogmodel.h
- app/qml/settings/MMChangelogPage.qml
- gallery/qml/pages/PagesPage.qml
https://github.com/MerginMaps/mobile/assets/804608/4bd46f1a-756f-4a84-bcae-8116bc843bf6
> add loading indicator when we are waiting for network request

- app/qml/components/MMListDelegate.qml
- app/qml/components/MMPage.qml
- app/qml/layers/MMFeaturesListPage.qml
- app/qml/layers/MMLayerDetailPage.qml
- app/qml/layers/MMLayersList.qml
- app/qml/layers/MMLayersListPage.qml
- app/qml/layers/MMLayersListSearchPage.qml
it looks like pageSpacing on MMPage was not used @tomasMizera ?
> LayersPanel with MMPage and MMListDrawer

- app/inpututils.cpp
- app/inpututils.h
- app/inpututils_p.cpp
- app/inpututils_p.h
- app/notificationmodel.cpp
- app/qml/account/MMAcceptInvitationPage.qml
- app/qml/account/MMAccountController.qml
- app/qml/components/MMMessage.qml
- app/qml/components/MMNotification.qml
- app/qml/dialogs/MMOutOfDateCustomServerDialog.qml
- app/qml/dialogs/MMProjectLoadErrorDialog.qml
- app/qml/main.qml
- app/qml/map/MMMapThemeDrawer.qml
- app/test/testutilsfunctions.cpp
- app/test/testutilsfunctions.h
- gallery/CMakeLists.txt
- gallery/inpututils.h
- gallery/qml/pages/NotificationPage.qml
allow links in Notification and fix project issues warning notification
add html link generator to inpututils
> fix project load issue panel 

- app/qml/components/MMListDrawer.qml
- app/qml/dialogs/MMProviderRemoveReceiverDialog.qml
- app/qml/gps/MMAddPositionProviderDrawer.qml
- app/qml/gps/MMBluetoothConnectionDrawer.qml
- app/qml/gps/MMPositionProviderPage.qml
- app/qml/map/MMMapController.qml
- app/qml/settings/MMSettingsController.qml
> Fix layout of the position providers pages and drawers

- app/qml/form/MMPreviewDrawer.qml
Photos and the background of the row of buttons were not clickable
> Fix preview panel clickable area

- app/qml/inputs/MMSearchInput.qml
- app/qml/inputs/MMSwitchInput.qml
- app/qml/layers/MMFeaturesListPage.qml
- app/qml/layers/MMLayerDetailPage.qml
- app/qml/layers/MMLayersController.qml
- app/qml/layers/MMLayersList.qml
- app/qml/layers/MMLayersListPage.qml
- app/qml/layers/MMLayersListSearchPage.qml
> Fix layers pages

- app/qml/account/MMHowYouFoundUsPage.qml
Bug fix: ISS-114
In ```MMHowYouFoundUsPage.qml```, after selecting an option, you can press the ```Continue``` button to proceed to ```MMWhichIndustryPage.qml```.
> Choose an option and hit continue on MMHowYouFoundUsPage

- app/qml/main.qml
- app/qml/project/MMProjectStatusPage.qml
Adjust: ISS-120
In main.qml, changed the icon from WaitingIcon to CheckIcon if it is already up to date.
> Up to date image adjustment

- app/qml/map/MMMapController.qml
- app/qml/map/MMRecordingTools.qml
- fix redraw crosshair
- reworked more menu during editing
- fix crash for redraw points
> fix recording

- app/qml/gps/MMStakeoutDrawer.qml
Bug fix: ISS-126
Stakeout feature activation fixed.
> Enabling stakeout feature

- app/qml/account/MMAccountPage.qml
> fix right margin on account page for diskspace

- app/qml/form/editors/MMFormGalleryEditor.qml
> Correct spacing of the gallery photos

- app/android/src/uk/co/lutraconsulting/InputActivity.java
- app/androidutils.cpp
- app/androidutils.h
- app/qml/main.qml
In this test version, pressing the sync button opens the test PDF file at "https://www.orimi.com/pdf-test.pdf" using the default Android PDF viewer.
> Working test version of Android PDF viewer

- app/qml/map/MMMapController.qml
> Map buttons to the top of Map highlight and gps marker

- app/qml/components/private/MMToolbarShortButton.qml
> inactive buttons in toolbar grayed

- app/main.cpp
- gallery/main.cpp
This allows stepping through code in qml files.
> Enable qml debugging

- app/qml/CMakeLists.txt
- app/qml/map/MMMapController.qml
- app/qml/map/components/MMHidingBox.qml
- app/qml/map/components/MMMapHidingLabel.qml
- app/qml/map/components/MMMapScaleBar.qml
- gallery/qml.qrc
- gallery/qml/pages/MapPage.qml
> do not use blur effect for scalebar and label

- app/attributes/attributecontroller.cpp
- app/qml/components/MMToolbar.qml
- app/qml/components/MMToolbarButton.qml
- app/qml/components/private/MMToolbarLongButton.qml
- app/qml/form/MMFormPage.qml
- gallery/qml/pages/ToolbarPage.qml
> Fix no geometry layers feature deletion

- app/qml/map/MMMapController.qml
> fix streaming button when adding features

- app/qml/project/MMProjectHomeTab.qml
- app/qml/project/MMProjectList.qml
This fixes problems (1) and (3) from #3210
This is how (1) looks like now:
> Fix offline GUI issues

- app/qml/components/MMToolbar.qml
- app/qml/map/MMRecordingTools.qml
fix https://github.com/MerginMaps/mobile/issues/3279
> Fix toolbar signal binding

- app/qml/main.qml
> disable gps receivers button when staking out

- app/qml/form/MMPreviewDrawer.qml
- app/qml/form/editors/MMFormTextEditor.qml
- app/qml/form/editors/MMFormTextMultilineEditor.qml
- app/qml/inputs/MMTextInput.qml
fix https://github.com/MerginMaps/mobile/issues/3289
fix https://github.com/MerginMaps/mobile/issues/3275
> allow links in form text editors and preview panels

- app/qml/main.qml
- app/qml/project/MMProjectController.qml
- app/qml/project/components/MMProjectStatusItem.qml
> Fixes minor issues in Project Status page

- app/qml/components/MMListDrawer.qml
- app/qml/main.qml
fix https://github.com/MerginMaps/mobile/issues/3220
fix https://github.com/MerginMaps/mobile/issues/3244
> Maptheme dialog fixes

- app/qml/form/MMFormPage.qml
- gallery/qml/pages/FormPage.qml
> Fix feature form width when tab bar has many tabs

- .github/workflows/android.yml
- .github/workflows/code_style.yml
- .github/workflows/gallery.yml
- .github/workflows/i18n.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/win.yml
- CMakeLists.txt
- INSTALL.md
- scripts/update_qt_version.bash
- let's see if Qt 6.6.3 will help with #3296
- small fix in `update_qt_version.bash` (with `\'` sed does not work for me on linux)
Fixes #3296
> Try Qt 6.6.3

- app/main.cpp
- app/qml/CMakeLists.txt
- app/qml/dialogs/MMWelcomeToNewDesignDialog.qml
- app/qml/main.qml
- gallery/qml/pages/DrawerPage.qml
It gets shown upon start, but only first time the app is run after upgrade from < 2024.x.y release.
Fixes #3255
> Add welcome to new design dialog

- app/mmstyle.h
- app/qml/account/MMHowYouFoundUsPage.qml
- app/qml/account/MMLoginPage.qml
- app/qml/account/MMSignUpPage.qml
- app/qml/account/MMWhichIndustryPage.qml
- app/qml/components/MMButton.qml
- app/qml/components/MMRoundButton.qml
- app/qml/dialogs/MMCloseAccountDialog.qml
- gallery/qml/pages/ButtonsPage.qml
fix: https://github.com/MerginMaps/mobile/issues/3207
> Disabled negative button on remove account

- app/mmstyle.h
- app/qml/account/MMCreateWorkspacePage.qml
- app/qml/components/MMCodeScanner.qml
- app/qml/components/MMPage.qml
- app/qml/components/MMPhotoPreview.qml
- gallery/qml/pages/MiscPage.qml
fix https://github.com/MerginMaps/mobile/issues/3277
fix https://github.com/MerginMaps/mobile/issues/3300
Note: photopreview now differs from Figma!
> Fix photo popups and create workspace overlapping button

- core/merginapi.cpp
Fixes #3261 
Ugly but works :zany_face:
> Fix annoying error message when starting app with expired token

- app/qml/form/editors/MMFormComboboxBaseEditor.qml
- app/qml/form/editors/MMFormValueMapEditor.qml
- app/qml/form/editors/MMFormValueRelationEditor.qml
> Update MMFormValueMapEditor and MMFormValueRelationEditor

- app/qml/form/editors/MMFormTextMultilineEditor.qml
- gallery/qml/pages/EditorsPage.qml
> Rework MMFormTextMultilineEditor

- app/mmstyle.h
- app/qml/form/editors/MMFormSliderEditor.qml
> Rework MMFormSliderEditor

- app/qml/components/MMSwitch.qml
- app/qml/components/private/MMBaseSingleLineInput.qml
- app/qml/form/components/photo/MMPhotoPreview.qml
- app/qml/form/editors/MMFormCalendarEditor.qml
- app/qml/form/editors/MMFormComboboxBaseEditor.qml
- app/qml/form/editors/MMFormNumberEditor.qml
- app/qml/form/editors/MMFormRelationEditor.qml
- app/qml/form/editors/MMFormRelationReferenceEditor.qml
- app/qml/form/editors/MMFormScannerEditor.qml
- app/qml/form/editors/MMFormSliderEditor.qml
- app/qml/inputs/MMComboboxInput.qml
- app/qml/inputs/MMPasswordInput.qml
- app/qml/inputs/MMSearchInput.qml
- app/qml/inputs/MMSwitchInput.qml
- app/qml/inputs/MMTextInput.qml
- gallery/qml/pages/ChecksPage.qml
- gallery/qml/pages/EditorsPage.qml
Fixes colours and also several merge issues.
> Fix editor and input icon colours

- app/qml/account/MMLoginPage.qml
- app/qml/form/components/photo/MMPhotoAttachment.qml
- app/qml/project/MMProjectHomeTab.qml
> Fixes after editors rework

- app/position/tracking/positiontrackingmanager.cpp
- app/position/tracking/positiontrackingmanager.h
- app/projectwizard.cpp
- app/qml/dialogs/MMPositionTrackingDialog.qml
- app/qml/main.qml
- app/qml/map/MMMapController.qml
- add tracking layer to new projects
- show elapsed time when tracking is active (instead of time when tracking started)
- fixed formatting of hours/minutes/seconds for tracking time
https://github.com/MerginMaps/mobile/assets/193367/ff1ac626-125d-4426-b578-d2c56037e9f6
> Tracking tweaks

- INSTALL.md
Updated Android and MacOS install steps.
> Update install notes

- app/android/src/uk/co/lutraconsulting/InputActivity.java
- app/androidutils.cpp
- app/androidutils.h
- app/inputhelp.cpp
- app/inpututils.cpp
- app/inpututils.h
- app/ios/iosutils.cpp
- app/ios/iosutils.h
- app/ios/iosutils.mm
Android:
iOS:
Desktop:
Fixes #2983 and Fixes #2978
> Workspace and hardware Info in diagnostic log file

- app/qml/form/editors/MMFormCalendarEditor.qml
https://github.com/MerginMaps/mobile/assets/155513369/d69a1103-abdf-407e-a019-fdbbcfd4c08f
Fixes #3425
> Set current date when clicking on calendar icon

- .github/workflows/ios.yml
We set it to upload only from master branch ~2 months ago because of the amount of commits. Let's revert back so that we can test things from PRs
> Upload IPA from all commits/branches

- app/qml/form/MMFormPage.qml
See https://github.com/MerginMaps/mobile/commit/396c128b9f9c9cd2c9356c9f5cc753fa4d7de61c#r142053291
> Remove debug code from MMFormPage

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/macos_arm64.yml
- .github/workflows/win.yml
- CMakeLists.txt
Setting USE_MM_SERVER_API_KEY=No as default and enable it in CI.
> Enhancing USE_MM_SERVER_API_KEY usage

- app/android/src/uk/co/lutraconsulting/PositionTrackingBroadcastMiddleware.java
- app/android/src/uk/co/lutraconsulting/PositionTrackingService.java
- cmake_templates/AndroidManifest.xml.in
Handling newly required permissions after SDK update from version 33 to 34.
Fixes #3641
> Fix position tracking after SDK update

- app/activeproject.cpp
- app/activeproject.h
- app/fieldsmodel.cpp
- app/fieldsmodel.h
- app/mmstyle.h
- scripts/cppcheck.bash
Fixed script following the latest Cppcheck library update (https://formulae.brew.sh/formula/cppcheck) by addressing corrections for `"functionConst"` warning.
> Fix cppcheck script

- app/mmstyle.h
- app/qml/form/MMFormController.qml
- app/qml/form/MMPreviewDrawer.qml
> Add form button to read only feature previews

- app/qml/project/components/MMProjectDelegate.qml
> Fix click area not filling whole parent bug

- app/qml/form/editors/MMFormGalleryEditor.qml
- app/qml/form/editors/MMFormRelationEditor.qml
Fixes #3733 
| Readers | Editors |
| --- | --- |
| ![Screenshot_20250407_211536](https://github.com/user-attachments/assets/ea240414-62df-4f03-8b61-8aed9592e5ee) | ![Screenshot_20250407_211723](https://github.com/user-attachments/assets/bb423ad6-1b6c-409d-8148-2a614f039485) |
| ![Screenshot_20250407_211608](https://github.com/user-attachments/assets/a6e3c83f-9092-4314-80d4-f50ec52ec6de) | ![Screenshot_20250407_211653](https://github.com/user-attachments/assets/46f6b2e6-87c8-41ba-ab88-b211984e7536) |
> Hide adding relations button for readers

- app/attributes/rememberattributescontroller.cpp
- app/attributes/rememberattributescontroller.h
- app/qml/form/MMFormController.qml
Minimal fix for #3784
Fix #3784
> Minimal fix for reuse last value

- app/qml/components/MMCodeScanner.qml
Seems like `CaptureSession` needs to be in visual children (worked with previous Qt version)
> Fix qr code by moving capture session in view port

- CMakeLists.txt
- cmake_templates/AndroidManifest.xml.in
- cmake_templates/build.gradle.in
Updates our config files based on the latest examples in Qt:
- https://github.com/qt/qtbase/blob/v6.8.3/src/android/templates/AndroidManifest.xml
- https://github.com/qt/qtbase/blob/v6.8.3/src/android/templates/build.gradle
> Update Android's manifest and build gradle files based on Qt 6.8.3

- cmake_templates/AndroidManifest.xml.in
- cmake_templates/build.gradle.in
This reverts commit 811c9b322cd725ee849d9239d0d4e0f77fd05993 to allow Google Play release. We'll investigate further on the size of AABs.
> Revert "Update Android's manifest and build gradle files based on Qt 6.8.3"

- app/invitationsmodel.cpp
- app/workspacesmodel.cpp
Extended fix to all remaining occurrences. 
(See https://github.com/MerginMaps/mobile/pull/3883)
> Fix additional occurrences of incorrect reset model sequence

- app/inputhelp.cpp
- app/main.cpp
- app/test/testmerginapi.cpp
- app/test/testmerginapi.h
- core/merginapi.cpp
- core/merginapi.h
> Allow sending diagnostic logs to host server

- app/identifykit.cpp
> Add missing context scopes when identifying features

- .github/workflows/ios.yml
Made too much noise + nobody uses it as this point
> Drop iOS CI build comments

- app/appsettings.h
Fixes the bug where on mobile devices the haptics used were opposite to what users selected.
> Fix haptics

- app/inputhelp.cpp
- app/inputhelp.h
> Lower log size to fit into AWS

- app/attributes/attributecontroller.cpp
> Fix photo name expression collisions

- app/inpututils.cpp
- app/inpututils.h
Unused and even with wrong logic..
> Remove unused updateFeature method
